Repository FabricMC/fabric, pull requests merged in 2019-09, with the labels that each got.

#319 Cooler dimension API, #309
  fabric-dimensions-v1/build.gradle
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/api/dimension/v1/EntityPlacer.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/api/dimension/v1/FabricDimensionType.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/api/dimension/v1/FabricDimensions.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/impl/dimension/DimensionIdsFixer.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/impl/dimension/DimensionIdsHolder.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/impl/dimension/DimensionRemapException.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/impl/dimension/FabricDimensionClientInit.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/impl/dimension/FabricDimensionInternals.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/EntityHooks.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/MixinEntity.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/MixinPortalForcer.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/idremap/MixinDimensionRawIndexFix.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/idremap/MixinLevelProperties.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/idremap/MixinLevelStorage.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/idremap/MixinPlayerManager.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/idremap/MixinUnmodifiableLevelProperties.java
  fabric-dimensions-v1/src/main/resources/fabric-dimensions-v1.mixins.json
  fabric-dimensions-v1/src/main/resources/fabric.mod.json
  settings.gradle
Labels: enhancement, last call

#373 Bring dimension API to 1.15 branch
  build.gradle
  fabric-dimensions-v1/build.gradle
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/api/dimension/v1/EntityPlacer.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/api/dimension/v1/FabricDimensionType.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/api/dimension/v1/FabricDimensions.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/impl/dimension/DimensionIdsFixer.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/impl/dimension/DimensionIdsHolder.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/impl/dimension/DimensionRemapException.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/impl/dimension/FabricDimensionClientInit.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/impl/dimension/FabricDimensionInternals.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/EntityHooks.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/MixinEntity.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/MixinPortalForcer.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/idremap/MixinDimensionRawIndexFix.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/idremap/MixinLevelProperties.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/idremap/MixinLevelStorage.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/idremap/MixinPlayerManager.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/idremap/MixinUnmodifiableLevelProperties.java
  fabric-dimensions-v1/src/main/resources/fabric-dimensions-v1.mixins.json
  fabric-dimensions-v1/src/main/resources/fabric.mod.json
  settings.gradle
Labels: port

#341 Fabric particles v1
  fabric-particles-v1/build.gradle
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/api/client/particle/v1/FabricSpriteProvider.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/api/client/particle/v1/ParticleFactoryRegistry.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/api/particle/v1/FabricParticleTypes.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/impl/client/particle/FabricParticleManager.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/impl/client/particle/ParticleFactoryRegistryImpl.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/impl/client/particle/VanillaParticleManager.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/mixin/client/particle/MixinParticleManager.java
  fabric-particles-v1/src/main/resources/fabric-particles-v1.mixins.json
  fabric-particles-v1/src/main/resources/fabric.mod.json
  fabric-testmods/java/net/fabricmc/fabric/particle/ParticleModClient.java
  fabric-testmods/resources/assets/testmod/particles/custom.json
  fabric-testmods/resources/assets/testmod/particles/simple.json
  settings.gradle
Labels: enhancement, merge me please

#382 Add a sync() method to BlockEntityClientSerializable
  fabric-networking-blockentity-v0/src/main/java/net/fabricmc/fabric/api/block/entity/BlockEntityClientSerializable.java
Labels: enhancement, last call

#367 Attempt to prevent CME due to off-thread block entity updates
  fabric-rendering-data-attachment-v1/build.gradle
  fabric-rendering-data-attachment-v1/src/main/java/net/fabricmc/fabric/mixin/rendering/data/client/MixinChunkRendererRegion.java
Labels: bug, reviews needed
