Repository FabricMC/fabric, pull requests merged in 2020-04, with the labels that each got.

#550 Fix javadoc jar generation and javadoc building
  build.gradle
  fabric-api-base/src/main/java/net/fabricmc/fabric/api/util/NbtType.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/api/dimension/v1/EntityPlacer.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/api/client/particle/v1/FabricSpriteProvider.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/api/particle/v1/FabricParticleTypes.java
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/api/renderer/v1/material/BlendMode.java
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/api/renderer/v1/material/RenderMaterial.java
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/api/renderer/v1/mesh/MutableQuadView.java
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/api/renderer/v1/model/FabricBakedModel.java
  fabric-rendering-fluids-v1/src/main/java/net/fabricmc/fabric/api/client/render/fluid/v1/FluidRenderHandler.java
Labels: bug, enhancement, reviews needed

#559 Make resource-loader-v0's generated resource packs use the latest data version
  fabric-resource-loader-v0/build.gradle
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackUtil.java
Labels: bug, reviews needed

#574 Check the Fabric box when uploading to curseforge
  build.gradle
Labels: enhancement, merge me please

#533 Fix FabricMaterialBuilder#notSolid returning the wrong builder type
  fabric-object-builders-v0/src/main/java/net/fabricmc/fabric/api/block/FabricMaterialBuilder.java
Labels: bug, enhancement, merge me please

#535 Fix particle API javadocs
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/api/client/particle/v1/FabricSpriteProvider.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/api/particle/v1/FabricParticleTypes.java
Labels: bug, merge me please

#558 fabric-climbable-api-v1 - Re-implementing minecraft:climbable on 1.15
  build.gradle
  fabric-climbable-api-v1/build.gradle
  fabric-climbable-api-v1/src/main/java/net/fabricmc/fabric/impl/climbable/FabricClimbableImpl.java
  fabric-climbable-api-v1/src/main/java/net/fabricmc/fabric/mixin/climbable/MixinLivingEntity.java
  fabric-climbable-api-v1/src/main/resources/fabric-climbable-api-v1.mixins.json
  fabric-climbable-api-v1/src/main/resources/fabric.mod.json
  settings.gradle
Labels: enhancement, merge me please, new module

#568 Entity attribute registry
  fabric-object-builders-v0/src/main/java/net/fabricmc/fabric/api/entity/FabricDefaultAttributeRegistry.java
  fabric-object-builders-v0/src/main/java/net/fabricmc/fabric/api/entity/FabricEntityTypeBuilder.java
  fabric-object-builders-v0/src/main/java/net/fabricmc/fabric/mixin/object/builder/DefaultAttributeRegistryAccessor.java
  fabric-object-builders-v0/src/main/java/net/fabricmc/fabric/mixin/object/builder/DefaultAttributeRegistryMixin.java
  fabric-object-builders-v0/src/main/resources/fabric-object-builders-v0.mixins.json
Labels: enhancement, last call

#563 Add a hook for BuiltinModelItemRenderer
  fabric-rendering-v1/build.gradle
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/api/client/rendering/v1/BuiltinItemRenderer.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/api/client/rendering/v1/BuiltinItemRendererRegistry.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/impl/client/rendering/BuiltinItemRendererRegistryImpl.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/MixinBuiltinModelItemRenderer.java
  fabric-rendering-v1/src/main/resources/fabric-rendering-v1.mixins.json
Labels: enhancement, last call
