Repository FabricMC/fabric, pull requests merged in 2020-05, with the labels that each got.

#604 Fix commands on servers.
  build.gradle
  fabric-command-api-v1/build.gradle
  fabric-command-api-v1/src/main/java/net/fabricmc/fabric/mixin/command/MixinCommandManager.java
  fabric-command-api-v1/src/main/java/net/fabricmc/fabric/mixin/command/MixinMinecraftDedicatedServer.java
  fabric-command-api-v1/src/main/resources/fabric-command-api-v1.mixins.json
Labels: bug

#593 Restart Testmods
  build.gradle
  checkstyle.xml
  fabric-item-groups-v0/src/testmod/java/net/fabricmc/fabric/test/item/group/ItemGroupTest.java
  fabric-item-groups-v0/src/testmod/resources/fabric.mod.json
  fabric-testmods/java/net/fabricmc/fabric/block/FireMod.java
  fabric-testmods/java/net/fabricmc/fabric/colormapper/ColorProviderMod.java
  fabric-testmods/java/net/fabricmc/fabric/commands/CommandMod.java
  fabric-testmods/java/net/fabricmc/fabric/containers/ContainerMod.java
  fabric-testmods/java/net/fabricmc/fabric/containers/ContainerModClient.java
  fabric-testmods/java/net/fabricmc/fabric/events/PickBlockEventModClient.java
  fabric-testmods/java/net/fabricmc/fabric/events/ServerEventMod.java
  fabric-testmods/java/net/fabricmc/fabric/fluidrender/FluidRendererModClient.java
  fabric-testmods/java/net/fabricmc/fabric/item/FuelMod.java
  fabric-testmods/java/net/fabricmc/fabric/itemgroup/ItemGroupMod.java
  fabric-testmods/java/net/fabricmc/fabric/keybinding/KeyBindingModClient.java
  fabric-testmods/java/net/fabricmc/fabric/loot/LootEntryMod.java
  fabric-testmods/java/net/fabricmc/fabric/loot/LootTableMod.java
  fabric-testmods/java/net/fabricmc/fabric/model/ModelModClient.java
  fabric-testmods/java/net/fabricmc/fabric/particle/ParticleModClient.java
  fabric-testmods/java/net/fabricmc/fabric/resources/ResourceReloadModClient.java
  fabric-testmods/resources/assets/testmod/particles/custom.json
  fabric-testmods/resources/assets/testmod/particles/simple.json
  fabric-testmods/resources/data/minecraft/loot_tables/blocks/stone.json
  fabric-testmods/resources/mod.json
Labels: enhancement, reviews needed

#609 Add netherite tools to tool tags
  fabric-tool-attribute-api-v1/build.gradle
  fabric-tool-attribute-api-v1/src/main/resources/data/fabric/tags/items/axes.json
  fabric-tool-attribute-api-v1/src/main/resources/data/fabric/tags/items/hoes.json
  fabric-tool-attribute-api-v1/src/main/resources/data/fabric/tags/items/pickaxes.json
  fabric-tool-attribute-api-v1/src/main/resources/data/fabric/tags/items/shovels.json
  fabric-tool-attribute-api-v1/src/main/resources/data/fabric/tags/items/swords.json
Labels: enhancement, small change

#611 Fix duplicate input class from object builder mixins
  fabric-object-builders-v0/src/main/java/net/fabricmc/fabric/mixin/object/builder/OldMixinBlock.java
  fabric-object-builders-v0/src/main/java/net/fabricmc/fabric/mixin/object/builder/OldMixinItem.java
  fabric-object-builders-v0/src/main/resources/fabric-object-builders-v0.mixins.json
Labels: bug, small change

#607 Create command api test mod
  fabric-command-api-v1/build.gradle
  fabric-command-api-v1/src/testmod/java/net/fabricmc/fabric/test/command/CommandTest.java
  fabric-command-api-v1/src/testmod/resources/fabric.mod.json
Labels: test

#644 Use a Slice over the Shift.BEFORE by -6
  fabric-rendering-v1/build.gradle
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/MixinInGameHud.java
Labels: enhancement, reviews needed, small change

#647 Make the create method public on villager profession builder
  build.gradle
  fabric-object-builder-api-v1/build.gradle
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/villager/VillagerProfessionBuilder.java
Labels: bug, small change

#649 Make villager profession builder create method public [1.15]
  build.gradle
  fabric-object-builder-api-v1/build.gradle
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/villager/VillagerProfessionBuilder.java
Labels: bug, small change
