Repository FabricMC/fabric, pull requests merged in 2020-10, with the labels that each got.

#1109 Write a proper readme
  README.md
Labels: enhancement, merge me please

#305 Add FabricChunkGeneratorType
  fabric-object-builders-v0/src/main/java/net/fabricmc/fabric/api/world/v1/gen/FabricChunkGeneratorType.java
Labels: enhancement, merge me please, reviews needed

#1076 Add helper methods to create custom villager types.
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/villager/VillagerTypeHelper.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/VillagerTypeAccessor.java
  fabric-object-builder-api-v1/src/main/resources/fabric-object-builder-v1.mixins.json
Labels: enhancement, merge me please

#1043 Tristate extensions
  fabric-api-base/src/main/java/net/fabricmc/fabric/api/util/BooleanFunction.java
  fabric-api-base/src/main/java/net/fabricmc/fabric/api/util/TriState.java
Labels: enhancement, merge me please

#1029 DynamicRegistryEvents
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/api/event/registry/DynamicRegistrySetupCallback.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/DynamicRegistryManagerMixin.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/MixinIdRegistry.java
  fabric-registry-sync-v0/src/main/resources/fabric-registry-sync-v0.mixins.json
  fabric-registry-sync-v0/src/main/resources/fabric.mod.json
  fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/RegistrySyncTest.java
Labels: enhancement, merge me please, new module

#1116 Use `"` consistently in main gradle buildscript and some deprecation
  build.gradle
Labels: small change

#1122 Fix QuadEmitter#square and Indigo uv locking
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/api/renderer/v1/mesh/QuadEmitter.java
  fabric-renderer-indigo/src/main/java/net/fabricmc/fabric/impl/client/indigo/renderer/helper/TextureHelper.java
Labels: bug, indigo, reviews needed

#1073 Clean up to tool-attributes, add annotations and add test for custom …
  fabric-tool-attribute-api-v1/build.gradle
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/api/tool/attribute/v1/DynamicAttributeTool.java
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/impl/tool/attribute/ToolManagerImpl.java
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/impl/tool/attribute/handlers/ModdedToolsModdedBlocksToolHandler.java
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/impl/tool/attribute/handlers/ModdedToolsVanillaBlocksToolHandler.java
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/impl/tool/attribute/handlers/ShearsVanillaBlocksToolHandler.java
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/impl/tool/attribute/handlers/VanillaToolsModdedBlocksToolHandler.java
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/impl/tool/attribute/handlers/package-info.java
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/impl/tool/attribute/package-info.java
  fabric-tool-attribute-api-v1/src/testmod/java/net/fabricmc/fabric/test/tool/attribute/ToolAttributeTest.java
  fabric-tool-attribute-api-v1/src/testmod/resources/data/fabric-tool-attribute-api-v1-testmod/tags/items/taters.json
Labels: merge me please, small change, test

#1128 Add Turkish language string
  fabric-item-groups-v0/src/main/resources/assets/fabric/lang/tr_tr.json
Labels: enhancement, merge me please, reviews needed

#1127 Update yarn mappings
  build.gradle
  fabric-game-rule-api-v1/src/main/java/net/fabricmc/fabric/mixin/gamerule/client/RuleListWidgetMixin.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/FabricBlockSettings.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/AbstractBlockSettingsAccessor.java
  fabric-object-builders-v0/src/main/java/net/fabricmc/fabric/api/block/BlockSettingsExtensions.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/DynamicRegistryManagerMixin.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/MixinLevelStorageSession.java
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/api/renderer/v1/model/ModelHelper.java
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/impl/renderer/SpriteFinderImpl.java
  fabric-renderer-indigo/src/main/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/ItemRenderContext.java
  fabric-textures-v0/src/main/java/net/fabricmc/fabric/api/event/client/ClientSpriteRegistryCallback.java
Labels: merge me please, small change

#1094 Tweak entity type builder generics to eliminate explicit type arguments
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/entity/FabricEntityTypeBuilder.java
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/EntityTypeBuilderGenericsTest.java
Labels: enhancement, merge me please, small change, test

#1140 Update command api to use new non-tail constructor inject
  build.gradle
  fabric-command-api-v1/build.gradle
  fabric-command-api-v1/src/main/java/net/fabricmc/fabric/mixin/command/CommandManagerMixin.java
  fabric-command-api-v1/src/main/resources/assets/fabric-command-api-v1/icon.png
  fabric-command-api-v1/src/main/resources/fabric-command-api-v1.mixins.json
  fabric-command-api-v1/src/main/resources/fabric.mod.json
  fabric-command-api-v1/src/testmod/java/net/fabricmc/fabric/test/command/CommandTest.java
Labels: enhancement, small change

#1097 Biome Modification API
  fabric-biome-api-v1/build.gradle
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeModification.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeModificationContext.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeModifications.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeSelectionContext.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeSelectors.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/ModificationPhase.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/NetherBiomes.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/OverworldBiomes.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/OverworldClimate.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/InternalBiomeData.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationContextImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationTracker.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeSelectionContextImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BuiltInRegistryKeys.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/BiomeAccessor.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/BiomeEffectsAccessor.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/BiomeWeatherAccessor.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/DynamicRegistryManagerImplMixin.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/GenerationSettingsAccessor.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/RegistryOpsMixin.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/SpawnDensityAccessor.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/SpawnSettingsAccessor.java
  fabric-biome-api-v1/src/main/resources/fabric-biome-api-v1.accesswidener
  fabric-biome-api-v1/src/main/resources/fabric-biome-api-v1.mixins.json
  fabric-biome-api-v1/src/main/resources/fabric.mod.json
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/FabricBiomeTest.java
Labels: enhancement, last call
