Repository FabricMC/fabric, pull requests merged in 2020-02, with the labels that each got.

#500 Indigo: Check cullface after transforming vanilla model
  fabric-renderer-indigo/src/main/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/TerrainFallbackConsumer.java
Labels: bug, indigo, reviews needed

#496 Add nether biomes API
  build.gradle
  fabric-biomes-v1/build.gradle
  fabric-biomes-v1/src/main/java/net/fabricmc/fabric/api/biomes/v1/NetherBiomes.java
  fabric-biomes-v1/src/main/java/net/fabricmc/fabric/impl/biome/InternalBiomeData.java
  fabric-biomes-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MixinTheNetherDimension.java
  fabric-biomes-v1/src/main/resources/fabric-biomes-v1.mixins.json
  fabric-biomes-v1/src/main/resources/fabric.mod.json
Labels: enhancement, last call

#503 Publish a fat javadoc jar to maven
  build.gradle
Labels: enhancement, reviews needed

#502 Fix ForwardingBakedModel not forwarding isSideLit. Closes #501
  fabric-renderer-api-v1/build.gradle
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/api/renderer/v1/model/ForwardingBakedModel.java
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/impl/renderer/DamageModel.java
Labels: bug, indigo
