Repository FabricMC/fabric, pull requests merged in 2021-11, with the labels that each got.

#1669 Add event phases
  fabric-api-base/src/main/java/net/fabricmc/fabric/api/event/Event.java
  fabric-api-base/src/main/java/net/fabricmc/fabric/api/event/EventFactory.java
  fabric-api-base/src/main/java/net/fabricmc/fabric/impl/base/event/ArrayBackedEvent.java
  fabric-api-base/src/main/java/net/fabricmc/fabric/impl/base/event/EventFactoryImpl.java
  fabric-api-base/src/main/java/net/fabricmc/fabric/impl/base/event/EventPhaseData.java
  fabric-api-base/src/main/java/net/fabricmc/fabric/impl/base/event/PhaseSorting.java
  fabric-api-base/src/testmod/java/net/fabricmc/fabric/test/base/EventTests.java
  fabric-api-base/src/testmod/java/net/fabricmc/fabric/test/base/FabricApiBaseTestInit.java
  fabric-api-base/src/testmod/java/net/fabricmc/fabric/test/base/graph.png
Labels: enhancement, last call, reviews needed, merge me please, priority:low

#1727 Environmental renderers
  fabric-dimensions-v1/src/testmod/resources/data/fabric_dimension/dimension_type/void_type.json
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/api/client/rendering/v1/DimensionRenderingRegistry.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/impl/client/rendering/DimensionRenderingRegistryImpl.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/DimensionEffectsAccessor.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/MixinWorldRenderer.java
  fabric-rendering-v1/src/main/resources/fabric-rendering-v1.mixins.json
  fabric-rendering-v1/src/testmod/java/net/fabricmc/fabric/test/rendering/client/DimensionalRenderingTest.java
  fabric-rendering-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call, reviews needed, merge me please

#1801 Another wave of transfer API improvements
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/client/fluid/FluidVariantRenderHandler.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/client/fluid/FluidVariantRendering.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/context/ContainerItemContext.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidStorage.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/item/ItemStorage.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/StorageUtil.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/StorageView.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/base/FilteringStorage.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/item/PlayerInventoryStorageImpl.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/ingame/client/FluidVariantRenderTest.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/unittests/FluidItemTests.java
Labels: merge me please

#1687 Custom fluid renderers and enhanced vanilla fluid renderer customization
  fabric-rendering-fluids-v1/build.gradle
  fabric-rendering-fluids-v1/src/main/java/net/fabricmc/fabric/api/client/render/fluid/v1/FluidRenderHandler.java
  fabric-rendering-fluids-v1/src/main/java/net/fabricmc/fabric/api/client/render/fluid/v1/FluidRenderHandlerRegistry.java
  fabric-rendering-fluids-v1/src/main/java/net/fabricmc/fabric/api/client/render/fluid/v1/SimpleFluidRenderHandler.java
  fabric-rendering-fluids-v1/src/main/java/net/fabricmc/fabric/impl/client/rendering/fluid/FluidRenderHandlerRegistryImpl.java
  fabric-rendering-fluids-v1/src/main/java/net/fabricmc/fabric/impl/client/rendering/fluid/FluidRendererHookContainer.java
  fabric-rendering-fluids-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/fluid/MixinFluidRenderer.java
  fabric-rendering-fluids-v1/src/main/resources/fabric-rendering-fluids-v1.mixins.json
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/CustomFluid.java
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/CustomizedFluidRenderer.java
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/FabricFluidRenderingTestMod.java
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/FabricFluidRenderingTestModClient.java
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/NoOverlayFluid.java
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/OverlayFluid.java
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/TestFluids.java
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/UnregisteredFluid.java
  fabric-rendering-fluids-v1/src/testmod/resources/assets/fabric-rendering-fluids-v1-testmod/textures/block/test_fluid_flowing.png
  fabric-rendering-fluids-v1/src/testmod/resources/assets/fabric-rendering-fluids-v1-testmod/textures/block/test_fluid_flowing.png.mcmeta
  fabric-rendering-fluids-v1/src/testmod/resources/assets/fabric-rendering-fluids-v1-testmod/textures/block/test_fluid_overlay.png
  fabric-rendering-fluids-v1/src/testmod/resources/assets/fabric-rendering-fluids-v1-testmod/textures/block/test_fluid_still.png
  fabric-rendering-fluids-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call, reviews needed, merge me please, priority:low

#1809 Fix shears being the ultimate mining tool
  fabric-mining-level-api-v1/src/main/java/net/fabricmc/fabric/api/mininglevel/v1/MiningLevelManager.java
  fabric-tool-attribute-api-v1/build.gradle
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/impl/tool/attribute/handlers/TaggedToolsModdedBlocksToolHandler.java
  fabric-tool-attribute-api-v1/src/testmod/java/net/fabricmc/fabric/test/tool/attribute/ToolAttributeTest.java
  fabric-tool-attribute-api-v1/src/testmod/resources/data/fabric/tags/blocks/mineable/shears.json
  fabric-tool-attribute-api-v1/src/testmod/resources/data/fabric/tags/blocks/mineable/sword.json
  fabric-tool-attribute-api-v1/src/testmod/resources/data/fabric/tags/items/swords.json
  fabric-tool-attribute-api-v1/src/testmod/resources/data/minecraft/tags/blocks/mineable/axe.json
  fabric-tool-attribute-api-v1/src/testmod/resources/data/minecraft/tags/blocks/mineable/hoe.json
  fabric-tool-attribute-api-v1/src/testmod/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
  fabric-tool-attribute-api-v1/src/testmod/resources/data/minecraft/tags/blocks/mineable/shovel.json
Labels: bug, merge me please, test, small change, priority:high

#1811 A less breaking workaround for https://github.com/FabricMC/fabric/issues/1806
  fabric-rendering-fluids-v1/src/main/java/net/fabricmc/fabric/impl/client/rendering/fluid/FluidRenderingClientInitializer.java
  fabric-rendering-fluids-v1/src/main/resources/fabric.mod.json
Labels: bug, priority:high

#1802 Buildscript cleanup/updates
  .editorconfig
  .github/workflows/build.yml
  .github/workflows/release.yml
  build.gradle
  fabric-api-base/build.gradle
  fabric-api-base/src/testmod/java/net/fabricmc/fabric/test/base/FabricApiBaseGameTest.java
  fabric-api-base/src/testmod/resources/fabric.mod.json
  fabric-api-lookup-api-v1/build.gradle
  fabric-biome-api-v1/build.gradle
  fabric-blockrenderlayer-v1/build.gradle
  fabric-command-api-v1/build.gradle
  fabric-commands-v0/build.gradle
  fabric-containers-v0/build.gradle
  fabric-content-registries-v0/build.gradle
  fabric-crash-report-info-v1/build.gradle
  fabric-dimensions-v1/build.gradle
  fabric-dimensions-v1/src/testmod/java/net/fabricmc/fabric/test/dimension/FabricDimensionTest.java
  fabric-entity-events-v1/build.gradle
  fabric-events-interaction-v0/build.gradle
  fabric-events-lifecycle-v0/build.gradle
  fabric-game-rule-api-v1/build.gradle
  fabric-gametest-api-v1/build.gradle
  fabric-item-api-v1/build.gradle
  fabric-item-groups-v0/build.gradle
  fabric-key-binding-api-v1/build.gradle
  fabric-keybindings-v0/build.gradle
  fabric-lifecycle-events-v1/build.gradle
  fabric-loot-tables-v1/build.gradle
  fabric-mining-level-api-v1/build.gradle
  fabric-mining-levels-v0/build.gradle
  fabric-models-v0/build.gradle
  fabric-networking-api-v1/build.gradle
  fabric-networking-blockentity-v0/build.gradle
  fabric-networking-v0/build.gradle
  fabric-object-builder-api-v1/build.gradle
  fabric-object-builders-v0/build.gradle
  fabric-particles-v1/build.gradle
  fabric-registry-sync-v0/build.gradle
  fabric-renderer-api-v1/build.gradle
  fabric-renderer-indigo/build.gradle
  fabric-renderer-registries-v1/build.gradle
  fabric-rendering-data-attachment-v1/build.gradle
  fabric-rendering-fluids-v1/build.gradle
  fabric-rendering-v0/build.gradle
  fabric-rendering-v1/build.gradle
  fabric-resource-loader-v0/build.gradle
  fabric-screen-api-v1/build.gradle
  fabric-screen-handler-api-v1/build.gradle
  fabric-structure-api-v1/build.gradle
  fabric-tag-extensions-v0/build.gradle
  fabric-textures-v0/build.gradle
  fabric-tool-attribute-api-v1/build.gradle
  fabric-transfer-api-v1/build.gradle
  gradle.properties
  gradle/module-versioning.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: enhancement, reviews needed, test

#1820 Fix missing some chunk unloads events leading to a memory leak.
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/client/ClientChunkManagerMixin.java
Labels: bug, merge me please, priority:high

#1834 Restored Nether/End- and Biome Modification API
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeModificationContext.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeModifications.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeSelectionContext.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationContextImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeSelectionContextImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BuiltInRegistryKeys.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MixinMultiNoiseBiomeSource.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/BiomeAccessor.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/BiomeEffectsAccessor.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/BiomeWeatherAccessor.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/GenerationSettingsAccessor.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/SpawnDensityAccessor.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/SpawnSettingsAccessor.java
  fabric-biome-api-v1/src/main/resources/fabric-biome-api-v1.accesswidener
  fabric-biome-api-v1/src/main/resources/fabric-biome-api-v1.mixins.json
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/FabricBiomeTest.java
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/mixin/DecoratorsAccessor.java
  fabric-biome-api-v1/src/testmod/resources/fabric-biome-testmod-api-v1.mixins.json
  fabric-biome-api-v1/src/testmod/resources/fabric.mod.json
  settings.gradle
Labels: enhancement

#1839 Fixes double-invoking of the client start event
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/client/MinecraftClientMixin.java
  fabric-lifecycle-events-v1/src/testmod/java/net/fabricmc/fabric/test/event/lifecycle/client/ClientLifecycleTests.java
Labels: bug, merge me please, priority:high

#1832 Oxidizable and Waxable Blocks registries
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/OxidizableBlocksRegistry.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/mixin/content/registry/HoneycombItemMixin.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/mixin/content/registry/OxidizableMixin.java
  fabric-content-registries-v0/src/main/resources/fabric-content-registries-v0.mixins.json
  fabric-content-registries-v0/src/testmod/java/net/fabricmc/fabric/test/content/registry/ContentRegistryTest.java
Labels: enhancement, last call, reviews needed, merge me please, priority:low

#1815 Add an API to enable elytra flight
  fabric-entity-events-v1/build.gradle
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/EntityElytraEvents.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/FabricElytraItem.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/elytra/ClientPlayerEntityMixin.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/elytra/LivingEntityMixin.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/elytra/PlayerEntityMixin.java
  fabric-entity-events-v1/src/main/resources/fabric-entity-events-v1.mixins.json
  fabric-entity-events-v1/src/testmod/java/net/fabricmc/fabric/test/entity/event/DiamondElytraItem.java
  fabric-entity-events-v1/src/testmod/java/net/fabricmc/fabric/test/entity/event/EntityEventTests.java
  fabric-entity-events-v1/src/testmod/java/net/fabricmc/fabric/test/entity/event/client/EntityEventTestsClient.java
  fabric-entity-events-v1/src/testmod/resources/fabric.mod.json
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/api/client/rendering/v1/LivingEntityFeatureRenderEvents.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/CapeFeatureRendererMixin.java
  fabric-rendering-v1/src/main/resources/fabric-rendering-v1.mixins.json
Labels: enhancement, last call, reviews needed, merge me please, priority:medium

#1777 Fix #1772
  fabric-key-binding-api-v1/src/main/java/net/fabricmc/fabric/impl/client/keybinding/KeyBindingRegistryImpl.java
  fabric-key-binding-api-v1/src/testmod/java/net/fabricmc/fabric/test/client/keybinding/KeyBindingsTest.java
  fabric-key-binding-api-v1/src/testmod/resources/assets/fabric-keybindings-v1-testmod/lang/en_us.json
Labels: bug, reviews needed, merge me please, priority:high

#1864 Build script fixes
  .github/workflows/build.yml
  .github/workflows/release.yml
  build.gradle
Labels: bug, priority:high
