Repository FabricMC/fabric, pull requests merged in 2021-07, with the labels that each got.

#1541 Prevent SpriteFinder from returning Missing sprite for wrong atlas
  fabric-renderer-api-v1/build.gradle
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/impl/renderer/SpriteFinderImpl.java
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/mixin/renderer/client/MixinSpriteAtlasTexture.java
Labels: bug, merge me please, small change

#1356 Fabric Transfer API: "fluid only" edition
  build.gradle
  fabric-transfer-api-v1/README.md
  fabric-transfer-api-v1/build.gradle
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/client/fluid/FluidVariantRenderHandler.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/client/fluid/FluidVariantRendering.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/CauldronFluidContent.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidConstants.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidStorage.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidVariant.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/base/SingleFluidStorage.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/package-info.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/Storage.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/StoragePreconditions.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/StorageUtil.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/StorageView.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/TransferVariant.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/base/CombinedStorage.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/base/ExtractionOnlyStorage.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/base/InsertionOnlyStorage.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/base/ResourceAmount.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/base/SingleSlotStorage.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/base/SingleViewIterator.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/transaction/Transaction.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/transaction/TransactionContext.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/transaction/base/SnapshotParticipant.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/TransferApiImpl.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/fluid/CauldronStorage.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/fluid/FluidVariantCache.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/fluid/FluidVariantImpl.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/transaction/TransactionManagerImpl.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/mixin/transfer/FluidMixin.java
  fabric-transfer-api-v1/src/main/resources/fabric-transfer-api-v1.mixins.json
  fabric-transfer-api-v1/src/main/resources/fabric-transfer-api-v1/icon.png
  fabric-transfer-api-v1/src/main/resources/fabric.mod.json
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/fluid/CreativeFluidStorage.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/fluid/ExtractStickItem.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/fluid/FluidChuteBlock.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/fluid/FluidChuteBlockEntity.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/fluid/FluidTransferTest.java
  fabric-transfer-api-v1/src/testmod/resources/assets/fabric-transfer-api-v1-testmod/blockstates/fluid_chute.json
  fabric-transfer-api-v1/src/testmod/resources/assets/fabric-transfer-api-v1-testmod/blockstates/infinite_lava_source.json
  fabric-transfer-api-v1/src/testmod/resources/assets/fabric-transfer-api-v1-testmod/blockstates/infinite_water_source.json
  fabric-transfer-api-v1/src/testmod/resources/assets/fabric-transfer-api-v1-testmod/models/block/fluid_chute.json
  fabric-transfer-api-v1/src/testmod/resources/assets/fabric-transfer-api-v1-testmod/models/block/infinite_lava_source.json
  fabric-transfer-api-v1/src/testmod/resources/assets/fabric-transfer-api-v1-testmod/models/block/infinite_water_source.json
  fabric-transfer-api-v1/src/testmod/resources/assets/fabric-transfer-api-v1-testmod/models/item/extract_stick.json
  fabric-transfer-api-v1/src/testmod/resources/assets/fabric-transfer-api-v1-testmod/models/item/fluid_chute.json
  fabric-transfer-api-v1/src/testmod/resources/assets/fabric-transfer-api-v1-testmod/models/item/infinite_lava_source.json
  fabric-transfer-api-v1/src/testmod/resources/assets/fabric-transfer-api-v1-testmod/models/item/infinite_water_source.json
  fabric-transfer-api-v1/src/testmod/resources/assets/fabric-transfer-api-v1-testmod/textures/block/fluid_chute.png
  fabric-transfer-api-v1/src/testmod/resources/assets/fabric-transfer-api-v1-testmod/textures/block/infinite_lava_source.png
  fabric-transfer-api-v1/src/testmod/resources/assets/fabric-transfer-api-v1-testmod/textures/block/infinite_water_source.png
  fabric-transfer-api-v1/src/testmod/resources/assets/fabric-transfer-api-v1-testmod/textures/item/extract_stick.png
  fabric-transfer-api-v1/src/testmod/resources/fabric.mod.json
  settings.gradle
Labels: enhancement, last call, new module, priority:low, reviews needed

#1592 Generate a changelog
  .github/workflows/release.yml
  build.gradle
Labels: merge me please, small change

#1564 Stop DefaultResourcePack scanning the entire classpath
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/DefaultResourcePackMixin.java
Labels: bug, merge me please, reviews needed, small change

#1518 Add client command source properties
  fabric-command-api-v1/src/main/java/net/fabricmc/fabric/api/client/command/v1/FabricClientCommandSource.java
Labels: enhancement, merge me please
