Repository FabricMC/fabric, pull requests merged in 2021-04, with the labels that each got.

#1418 Add Mexican spanish translation
  fabric-item-groups-v0/src/main/resources/assets/fabric/lang/es_mx.json
Labels: merge me please

#1416 Add Finnish translation
  fabric-item-groups-v0/src/main/resources/assets/fabric/lang/fi_fi.json
  fabric-resource-loader-v0/src/main/resources/assets/fabric-resource-loader-v0/lang/fi_fi.json
Labels: enhancement, merge me please, priority:low, small change

#1403 Add Greek translation
  fabric-item-groups-v0/src/main/resources/assets/fabric/lang/el_gr.json
Labels: merge me please

#1392 Allow more flexibility when registering BERs
  fabric-renderer-registries-v1/src/main/java/net/fabricmc/fabric/api/client/rendereregistry/v1/BlockEntityRendererRegistry.java
  fabric-renderer-registries-v1/src/main/java/net/fabricmc/fabric/impl/client/renderer/registry/BlockEntityRendererRegistryImpl.java
Labels: enhancement, merge me please, priority:medium, reviews needed, small change

#1319 Fix a WorldRenderEvents.BLOCK_OUTLINE bug
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/api/client/rendering/v1/WorldRenderContext.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/impl/client/rendering/WorldRenderContextImpl.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/MixinWorldRenderer.java
  fabric-rendering-v1/src/testmod/java/net/fabricmc/fabric/test/rendering/client/WorldRenderEventsTests.java
  fabric-rendering-v1/src/testmod/resources/fabric.mod.json
Labels: bug, merge me please, priority:high, reviews needed

#1295 Create a simple renderer api testmod
  fabric-renderer-api-v1/build.gradle
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/WorldRenderExtensions.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/mixin/ClientWorldMixin.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/mixin/WorldMixin.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/package-info.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/simple/FrameBlock.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/simple/FrameBlockEntity.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/simple/RendererTest.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/simple/client/FrameBakedModel.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/simple/client/FrameModelResourceProvider.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/simple/client/FrameUnbakedModel.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/simple/client/RendererClientTest.java
  fabric-renderer-api-v1/src/testmod/resources/assets/fabric-renderer-api-v1-testmod/blockstates/frame.json
  fabric-renderer-api-v1/src/testmod/resources/fabric-renderer-api-v1-testmod.mixins.json
  fabric-renderer-api-v1/src/testmod/resources/fabric.mod.json
Labels: merge me please, priority:low, reviews needed, test

#1390 Allow getting BakedModels using Identifiers
  fabric-models-v0/build.gradle
  fabric-models-v0/src/main/java/net/fabricmc/fabric/api/client/model/BakedModelManagerHelper.java
  fabric-models-v0/src/main/java/net/fabricmc/fabric/impl/client/model/BakedModelManagerHooks.java
  fabric-models-v0/src/main/java/net/fabricmc/fabric/mixin/client/model/MixinBakedModelManager.java
  fabric-models-v0/src/main/resources/fabric-models-v0.mixins.json
  fabric-models-v0/src/testmod/java/net/fabricmc/fabric/test/model/BakedModelFeatureRenderer.java
  fabric-models-v0/src/testmod/java/net/fabricmc/fabric/test/model/BakedModelRenderer.java
  fabric-models-v0/src/testmod/java/net/fabricmc/fabric/test/model/ModelTestModClient.java
  fabric-models-v0/src/testmod/java/net/fabricmc/fabric/test/model/SpecificModelReloadListener.java
  fabric-models-v0/src/testmod/resources/assets/fabric-models-v0-testmod/models/half_red_sand.json
  fabric-models-v0/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call, merge me please, priority:low

#1428 Add missing metadata to dimensions api
  fabric-dimensions-v1/src/main/resources/assets/fabric-dimensions-v1/icon.png
  fabric-dimensions-v1/src/main/resources/fabric.mod.json
  settings.gradle
Labels: merge me please, small change

#1355 Update Dynamic Attribute Tool modifier application to fix #1353
  fabric-tool-attribute-api-v1/build.gradle
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/api/tool/attribute/v1/DynamicAttributeTool.java
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/impl/tool/attribute/AttributeManager.java
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/impl/tool/attribute/ItemStackContext.java
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/mixin/tool/attribute/LivingEntityMixin.java
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/mixin/tool/attribute/MixinItemStack.java
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/mixin/tool/attribute/MixinLivingEntity.java
  fabric-tool-attribute-api-v1/src/main/resources/fabric-tool-attribute-api-v1.mixins.json
  fabric-tool-attribute-api-v1/src/testmod/java/net/fabricmc/fabric/test/tool/attribute/ToolAttributeTest.java
  fabric-tool-attribute-api-v1/src/testmod/java/net/fabricmc/fabric/test/tool/attribute/item/TestDynamicCancelItem.java
  fabric-tool-attribute-api-v1/src/testmod/java/net/fabricmc/fabric/test/tool/attribute/item/TestDynamicSwordItem.java
  fabric-tool-attribute-api-v1/src/testmod/java/net/fabricmc/fabric/test/tool/attribute/item/TestDynamicToolItem.java
  fabric-tool-attribute-api-v1/src/testmod/java/net/fabricmc/fabric/test/tool/attribute/item/TestNullableItem.java
Labels: bug, merge me please, priority:high, test

#1433 #1431 - Foce update MCE to fix bad refmap
  build.gradle
Labels: bug, priority:high, small change
