Repository FabricMC/fabric, pull requests merged in 2021-09, with the labels that each got.

#1696 [1.16] Update loom and gradle. Requires J16 to build, still targets J8
  .github/workflows/build.yml
  .github/workflows/release.yml
  build.gradle
  fabric-api-base/build.gradle
  fabric-api-lookup-api-v1/build.gradle
  fabric-biome-api-v1/build.gradle
  fabric-command-api-v1/build.gradle
  fabric-content-registries-v0/build.gradle
  fabric-dimensions-v1/build.gradle
  fabric-game-rule-api-v1/build.gradle
  fabric-key-binding-api-v1/build.gradle
  fabric-models-v0/build.gradle
  fabric-networking-api-v1/build.gradle
  fabric-object-builder-api-v1/build.gradle
  fabric-renderer-api-v1/build.gradle
  fabric-renderer-registries-v1/build.gradle
  fabric-resource-loader-v0/build.gradle
  fabric-screen-handler-api-v1/build.gradle
  fabric-tool-attribute-api-v1/build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: merge me please

#1701 Restore contact of InvalidateRenderStateCallback
  fabric-rendering-v1/build.gradle
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/MixinWorldRenderer.java
Labels: bug, reviews needed, merge me please, small change, priority:medium

#1700 Transfer API: Work around vanilla capturing ItemStack references
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/item/base/SingleStackStorage.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/item/InventorySlotWrapper.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/unittests/ItemTests.java
Labels: merge me please, priority:medium

#1732 Biome API without Overworld for now [1.18]
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeModificationContext.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeSelectionContext.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeSelectors.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/NetherBiomes.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/OverworldBiomes.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/OverworldClimate.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/TheEndBiomes.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/BiomeVariant.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/InternalBiomeData.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/InternalBiomeUtils.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/NetherBiomeData.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/OverworldBiomeData.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/SimpleLayerRandomnessSource.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/TheEndBiomeData.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/VariantTransformer.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/WeightedBiomeEntry.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/WeightedBiomePicker.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationContextImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeSelectionContextImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeStructureStartsImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/AddHillsLayerAccessor.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/BuiltinBiomesAccessor.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MixinAddEdgeBiomesLayer.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MixinAddHillsLayer.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MixinAddRiversLayer.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MixinMultiNoiseBiomeSource.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MixinSetBaseBiomesLayer.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MixinTheEndBiomeSource.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MultiNoiseBiomeSourceAccessor.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/VanillaLayeredBiomeSourceAccessor.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/BiomeAccessor.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/GenerationSettingsAccessor.java
  fabric-biome-api-v1/src/main/resources/fabric-biome-api-v1.accesswidener
  fabric-biome-api-v1/src/main/resources/fabric-biome-api-v1.mixins.json
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/FabricBiomeTest.java
Labels: reviews needed
