Repository FabricMC/fabric, pull requests merged in 2021-02, with the labels that each got.

#1291 Remove all inter-module dependencies on fabric-networking-v0
  README.md
  fabric-containers-v0/build.gradle
  fabric-containers-v0/src/main/java/net/fabricmc/fabric/impl/client/container/ScreenProviderRegistryImpl.java
  fabric-containers-v0/src/main/resources/fabric.mod.json
  fabric-dimensions-v1/src/main/resources/fabric.mod.json
  fabric-screen-handler-api-v1/build.gradle
  fabric-screen-handler-api-v1/src/main/java/net/fabricmc/fabric/impl/screenhandler/Networking.java
  fabric-screen-handler-api-v1/src/main/java/net/fabricmc/fabric/impl/screenhandler/client/ClientNetworking.java
  fabric-screen-handler-api-v1/src/main/resources/fabric.mod.json
Labels: merge me please, priority:low, reviews needed, small change

#1305 Make event registration thread safe
  fabric-api-base/src/main/java/net/fabricmc/fabric/api/event/Event.java
  fabric-api-base/src/main/java/net/fabricmc/fabric/impl/base/event/ArrayBackedEvent.java
Labels: bug, merge me please, priority:high, reviews needed, small change

#1308 Fix material builder
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/FabricMaterialBuilder.java
Labels: bug, merge me please, priority:medium, reviews needed, small change

#1309 Update key-binding-api-v1 example
  fabric-key-binding-api-v1/build.gradle
  fabric-key-binding-api-v1/src/testmod/java/net/fabricmc/fabric/test/client/keybinding/KeyBindingsTest.java
  fabric-key-binding-api-v1/src/testmod/resources/fabric.mod.json
Labels: merge me please, reviews needed, small change, test

#1197 Add registry for creating entity model layers and texture data
  fabric-renderer-registries-v1/src/main/java/net/fabricmc/fabric/api/client/rendereregistry/v1/EntityModelLayerRegistry.java
  fabric-renderer-registries-v1/src/main/java/net/fabricmc/fabric/api/client/rendereregistry/v1/EntityRendererRegistry.java
  fabric-renderer-registries-v1/src/main/java/net/fabricmc/fabric/impl/client/renderer/registry/EntityModelLayerImpl.java
  fabric-renderer-registries-v1/src/main/java/net/fabricmc/fabric/mixin/client/renderer/registry/EntityModelLayersAccessor.java
  fabric-renderer-registries-v1/src/main/java/net/fabricmc/fabric/mixin/client/renderer/registry/EntityModelsMixin.java
  fabric-renderer-registries-v1/src/main/resources/fabric-renderer-registries-v1.mixins.json
Labels: enhancement, last call, priority:high

#1115 Client-sided commands
  fabric-command-api-v1/src/main/java/net/fabricmc/fabric/api/client/command/v1/ClientCommandManager.java
  fabric-command-api-v1/src/main/java/net/fabricmc/fabric/api/client/command/v1/FabricClientCommandSource.java
  fabric-command-api-v1/src/main/java/net/fabricmc/fabric/api/client/command/v1/package-info.java
  fabric-command-api-v1/src/main/java/net/fabricmc/fabric/impl/command/client/ClientCommandInternals.java
  fabric-command-api-v1/src/main/java/net/fabricmc/fabric/mixin/command/HelpCommandAccessor.java
  fabric-command-api-v1/src/main/java/net/fabricmc/fabric/mixin/command/client/ClientCommandSourceMixin.java
  fabric-command-api-v1/src/main/java/net/fabricmc/fabric/mixin/command/client/ClientPlayNetworkHandlerMixin.java
  fabric-command-api-v1/src/main/java/net/fabricmc/fabric/mixin/command/client/ClientPlayerEntityMixin.java
  fabric-command-api-v1/src/main/java/net/fabricmc/fabric/mixin/command/client/MinecraftClientMixin.java
  fabric-command-api-v1/src/main/resources/fabric-command-api-v1.mixins.json
  fabric-command-api-v1/src/testmod/java/net/fabricmc/fabric/test/command/client/ClientCommandTest.java
  fabric-command-api-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call, merge me please, priority:medium, test
