Repository FabricMC/fabric, pull requests merged in 2021-06, with the labels that each got.

#1301 Fix #1273 (Make MultipartBakedModel and WeightedBackedModel implement FabricBakedModel properly)
  .gitignore
  fabric-renderer-api-v1/build.gradle
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/mixin/renderer/client/MixinMultipartBakedModel.java
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/mixin/renderer/client/MixinWeightedBakedModel.java
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/mixin/renderer/client/WeightedBakedModelEntryAccessor.java
  fabric-renderer-api-v1/src/main/resources/fabric-renderer-api-v1.mixins.json
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/simple/FrameBlock.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/simple/FrameBlockEntity.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/simple/RendererTest.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/simple/client/FrameModelResourceProvider.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/simple/client/RendererClientTest.java
  fabric-renderer-api-v1/src/testmod/resources/assets/fabric-renderer-api-v1-testmod/blockstates/frame_multipart.json
  fabric-renderer-api-v1/src/testmod/resources/assets/fabric-renderer-api-v1-testmod/blockstates/frame_weighted.json
Labels: merge me please, priority:medium, reviews needed, small change

#1474 Fix Screen API ButtonList in 1.17
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/impl/client/screen/ButtonList.java
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/mixin/screen/ScreenMixin.java
Labels: bug, merge me please, priority:high, small change

#1486 Make BlockApiLookup expose the API and context classes
  fabric-api-lookup-api-v1/build.gradle
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/block/BlockApiLookup.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/impl/lookup/block/BlockApiLookupImpl.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/FabricApiLookupTest.java
Labels: enhancement, merge me please, priority:low, small change

#1497 Fix screen testmod. Closes #1477
  fabric-screen-api-v1/src/testmod/java/net/fabricmc/fabric/test/screen/ScreenTests.java
Labels: merge me please, reviews needed, small change

#1495 Fix structure config not applying in every case
  fabric-structure-api-v1/build.gradle
  fabric-structure-api-v1/src/main/java/net/fabricmc/fabric/api/structure/v1/FabricStructureBuilder.java
  fabric-structure-api-v1/src/main/java/net/fabricmc/fabric/impl/structure/FabricStructureImpl.java
  fabric-structure-api-v1/src/main/java/net/fabricmc/fabric/impl/structure/FabricStructureUtil.java
  fabric-structure-api-v1/src/main/java/net/fabricmc/fabric/impl/structure/StructuresConfigHooks.java
  fabric-structure-api-v1/src/main/java/net/fabricmc/fabric/mixin/structure/BiomeAccessor.java
  fabric-structure-api-v1/src/main/java/net/fabricmc/fabric/mixin/structure/MixinChunkGeneratorSettings.java
  fabric-structure-api-v1/src/main/java/net/fabricmc/fabric/mixin/structure/MixinStructuresConfig.java
  fabric-structure-api-v1/src/main/java/net/fabricmc/fabric/mixin/structure/StructuresConfigAccessor.java
  fabric-structure-api-v1/src/main/resources/fabric-structure-api-v1.mixins.json
  fabric-structure-api-v1/src/main/resources/fabric.mod.json
Labels: bug, merge me please, priority:high

#1498 Fix ClientPickBlockApplyCallback.EVENT not working as expected Fixes #1493
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/mixin/event/interaction/MixinMinecraftClient.java
  fabric-events-interaction-v0/src/testmod/java/net/fabricmc/fabric/test/event/interaction/PlayerPickBlockTests.java
  fabric-events-interaction-v0/src/testmod/resources/fabric.mod.json
Labels: bug, merge me please, priority:high, small change

#1352 Add ItemApiLookup
  fabric-api-lookup-api-v1/README.md
  fabric-api-lookup-api-v1/build.gradle
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/item/ItemApiLookup.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/package-info.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/impl/lookup/item/ItemApiLookupImpl.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/FabricApiLookupTest.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/item/FabricItemApiLookupTest.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/item/Inspectable.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/item/InspectableItem.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/item/InspectorBlock.java
Labels: enhancement, merge me please, priority:low, reviews needed, test
