Repository FabricMC/fabric, pull requests merged in 2021-12, with the labels that each got.

#1321 Add ability for minecarts to specify their detector rail comparator value
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/entity/MinecartComparatorLogic.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/entity/MinecartComparatorLogicRegistry.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/DetectorRailBlockMixin.java
  fabric-object-builder-api-v1/src/main/resources/fabric-object-builder-v1.mixins.json
Labels: enhancement, reviews needed, merge me please, small change, priority:low

#1790 Allow canceling the NBT update animation and block break reset
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/FabricItem.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ItemMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/client/ClientPlayerInteractionManagerMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/client/HeldItemRendererMixin.java
  fabric-item-api-v1/src/main/resources/fabric-item-api-v1.mixins.json
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/ItemUpdateAnimationTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/UpdatingItem.java
  fabric-item-api-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, reviews needed, merge me please, priority:medium

#1872 Fix AttackBlockCallback on the client not sending a packet to the server
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/mixin/event/interaction/MixinClientPlayerInteractionManager.java
  fabric-events-interaction-v0/src/testmod/java/net/fabricmc/fabric/test/event/interaction/AttackBlockTests.java
  fabric-events-interaction-v0/src/testmod/resources/fabric.mod.json
Labels: bug, reviews needed, merge me please, priority:high

#1844 Add a handful of useful worldgen transitive access-wideners.
  fabric-biome-api-v1/src/main/resources/fabric-biome-api-v1.accesswidener
  fabric-biome-api-v1/src/main/resources/fabric.mod.json
Labels: enhancement, merge me please, small change, priority:low

#1824 Fabric Data Generation API
  build.gradle
  fabric-data-generation-api-v1/.gitignore
  fabric-data-generation-api-v1/build.gradle
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/DataGeneratorEntrypoint.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/FabricDataGenerator.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/package-info.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricAdvancementsProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricBlockLootTablesProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricBlockStateDefinitionProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricLootTableProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricRecipesProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricTagProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/SimpleFabricLootTableProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/FabricDataGenHelper.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/FabricTagBuilder.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/mixin/datagen/BlockStateDefinitionProviderMixin.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/mixin/datagen/TagBuilderMixin.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/mixin/datagen/client/MinecraftClientMixin.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/mixin/datagen/server/MainMixin.java
  fabric-data-generation-api-v1/src/main/resources/assets/fabric-data-generation-api-v1/icon.png
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.mixins.json
  fabric-data-generation-api-v1/src/main/resources/fabric.mod.json
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestContent.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
  fabric-data-generation-api-v1/src/testmod/resources/fabric.mod.json
  fabric-data-generation-api-v1/template.accesswidener
  gradle.properties
  settings.gradle
Labels: enhancement, merge me please, new module

#1923 Synchronize BlockEntityType to the Client
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/FabricRegistryInit.java
Labels: bug, registry-sync, merge me please, priority:high

#1904 Fix missing game test argument types Fixes #1899
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/ArgumentTypesMixin.java
  fabric-gametest-api-v1/src/main/resources/fabric-gametest-api-v1.mixins.json
Labels: bug, merge me please, small change, priority:medium

#1911 Datagen Additions
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricTagProvider.java
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestContent.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
  fabric-data-generation-api-v1/template.accesswidener
Labels: enhancement, reviews needed, merge me please, priority:low

#1866 Add id getter to ApiLookups and expose the BE in BlockApiCache
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/block/BlockApiCache.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/block/BlockApiLookup.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/custom/ApiLookupMap.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/entity/EntityApiLookup.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/item/ItemApiLookup.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/impl/lookup/block/BlockApiCacheImpl.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/impl/lookup/block/BlockApiLookupImpl.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/impl/lookup/custom/ApiLookupMapImpl.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/impl/lookup/entity/EntityApiLookupImpl.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/impl/lookup/item/ItemApiLookupImpl.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/FabricApiLookupTest.java
Labels: enhancement, merge me please

#1890 Add datagen support for dynamic registry tags
  fabric-data-generation-api-v1/build.gradle
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricTagProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/FabricDataGenHelper.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/mixin/datagen/DynamicRegistryManagerAccessor.java
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.mixins.json
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
  fabric-data-generation-api-v1/template.accesswidener
Labels: enhancement, reviews needed, priority:low
