Repository FabricMC/fabric, pull requests merged in 2021-01, with the labels that each got.

#1251 Workaround for shadowed fields from supermixins do not remap.
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/LivingEntityMixin.java
Labels: bug

#1256 Fix nether portal crash
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/EntityMixin.java
Labels: bug

#1270 Fix javadoc and typo
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/api/renderer/v1/render/RenderContext.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/api/client/rendering/v1/WorldRenderEvents.java
Labels: merge me please, small change

#1253 Add custom value denoting module lifecycles.
  build.gradle
  fabric-api-base/src/main/resources/fabric.mod.json
  fabric-biome-api-v1/src/main/resources/fabric.mod.json
  fabric-blockrenderlayer-v1/src/main/resources/fabric.mod.json
  fabric-command-api-v1/src/main/resources/fabric.mod.json
  fabric-commands-v0/src/main/resources/fabric.mod.json
  fabric-containers-v0/src/main/resources/fabric.mod.json
  fabric-content-registries-v0/src/main/resources/fabric.mod.json
  fabric-crash-report-info-v1/src/main/resources/fabric.mod.json
  fabric-dimensions-v1/src/main/resources/fabric.mod.json
  fabric-entity-events-v1/src/main/resources/fabric.mod.json
  fabric-events-interaction-v0/src/main/resources/fabric.mod.json
  fabric-events-lifecycle-v0/src/main/resources/fabric.mod.json
  fabric-game-rule-api-v1/src/main/resources/fabric.mod.json
  fabric-item-api-v1/src/main/resources/fabric.mod.json
  fabric-item-groups-v0/src/main/resources/fabric.mod.json
  fabric-key-binding-api-v1/src/main/resources/fabric.mod.json
  fabric-keybindings-v0/src/main/resources/fabric.mod.json
  fabric-lifecycle-events-v1/src/main/resources/fabric.mod.json
  fabric-loot-tables-v1/src/main/resources/fabric.mod.json
  fabric-mining-levels-v0/src/main/resources/fabric.mod.json
  fabric-models-v0/src/main/resources/fabric.mod.json
  fabric-networking-api-v1/src/main/resources/fabric.mod.json
  fabric-networking-blockentity-v0/src/main/resources/fabric.mod.json
  fabric-networking-v0/src/main/resources/fabric.mod.json
  fabric-object-builder-api-v1/src/main/resources/fabric.mod.json
  fabric-object-builders-v0/src/main/resources/fabric.mod.json
  fabric-particles-v1/src/main/resources/fabric.mod.json
  fabric-registry-sync-v0/src/main/resources/fabric.mod.json
  fabric-renderer-api-v1/src/main/resources/fabric.mod.json
  fabric-renderer-indigo/src/main/resources/fabric.mod.json
  fabric-renderer-registries-v1/src/main/resources/fabric.mod.json
  fabric-rendering-data-attachment-v1/src/main/resources/fabric.mod.json
  fabric-rendering-fluids-v1/src/main/resources/fabric.mod.json
  fabric-rendering-v0/src/main/resources/fabric.mod.json
  fabric-rendering-v1/src/main/resources/fabric.mod.json
  fabric-resource-loader-v0/src/main/resources/fabric.mod.json
  fabric-screen-handler-api-v1/src/main/resources/fabric.mod.json
  fabric-structure-api-v1/src/main/resources/fabric.mod.json
  fabric-tag-extensions-v0/src/main/resources/fabric.mod.json
  fabric-textures-v0/src/main/resources/fabric.mod.json
  fabric-tool-attribute-api-v1/src/main/resources/fabric.mod.json
  gradle/module-validation.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: enhancement, merge me please

#645 Screen API v1
  fabric-screen-api-v1/build.gradle
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/api/client/screen/v1/ScreenEvents.java
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/api/client/screen/v1/ScreenKeyboardEvents.java
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/api/client/screen/v1/ScreenMouseEvents.java
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/api/client/screen/v1/Screens.java
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/api/client/screen/v1/package-info.java
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/impl/client/screen/ButtonList.java
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/impl/client/screen/ScreenEventFactory.java
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/impl/client/screen/ScreenExtensions.java
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/mixin/screen/GameRendererMixin.java
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/mixin/screen/KeyboardMixin.java
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/mixin/screen/MinecraftClientMixin.java
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/mixin/screen/MouseMixin.java
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/mixin/screen/ScreenAccessor.java
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/mixin/screen/ScreenMixin.java
  fabric-screen-api-v1/src/main/resources/assets/fabric-screen-api-v1/icon.png
  fabric-screen-api-v1/src/main/resources/fabric-screen-api-v1.mixins.json
  fabric-screen-api-v1/src/main/resources/fabric.mod.json
  fabric-screen-api-v1/src/testmod/java/net/fabricmc/fabric/test/screen/ScreenTests.java
  fabric-screen-api-v1/src/testmod/java/net/fabricmc/fabric/test/screen/SoundButton.java
  fabric-screen-api-v1/src/testmod/java/net/fabricmc/fabric/test/screen/StopSoundButton.java
  fabric-screen-api-v1/src/testmod/resources/fabric.mod.json
  settings.gradle
Labels: enhancement, merge me please, new module, test

#1280 Upload to modrith from gradle
  .github/workflows/release.yml
  README.md
  build.gradle
Labels: merge me please, small change
