Repository FabricMC/fabric, pull requests merged in 2021-03, with the labels that each got.

#1234 Fabric API Lookup
  checkstyle.xml
  fabric-api-lookup-api-v1/README.md
  fabric-api-lookup-api-v1/build.gradle
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/block/BlockApiCache.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/block/BlockApiLookup.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/custom/ApiLookupMap.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/custom/ApiProviderMap.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/package-info.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/impl/lookup/block/BlockApiCacheImpl.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/impl/lookup/block/BlockApiLookupImpl.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/impl/lookup/block/ServerWorldCache.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/impl/lookup/custom/ApiLookupMapImpl.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/impl/lookup/custom/ApiProviderHashMap.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/mixin/lookup/BlockEntityTypeAccessor.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/mixin/lookup/ServerWorldMixin.java
  fabric-api-lookup-api-v1/src/main/resources/assets/fabric-api-lookup-api-v1/icon.png
  fabric-api-lookup-api-v1/src/main/resources/fabric-api-lookup-api-v1.mixins.json
  fabric-api-lookup-api-v1/src/main/resources/fabric.mod.json
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/ChuteBlock.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/ChuteBlockEntity.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/CobbleGenBlock.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/CobbleGenBlockEntity.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/FabricApiLookupTest.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/api/ItemApis.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/api/ItemExtractable.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/api/ItemInsertable.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/api/ItemUtils.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/compat/InventoryExtractableProvider.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/compat/InventoryInsertableProvider.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/compat/ItemStackUtil.java
  fabric-api-lookup-api-v1/src/testmod/java/net/fabricmc/fabric/test/lookup/compat/WrappedInventory.java
  fabric-api-lookup-api-v1/src/testmod/resources/fabric.mod.json
  settings.gradle
Labels: enhancement, last call, merge me please, new module, priority:low, test

#1364 Fix the onPlayerInteractEntity mixin causing a crash because the target method signature was not specified
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/mixin/event/interaction/MixinServerPlayNetworkHandler.java
Labels: bug, priority:high, reviews needed, small change

#1358 Fix sendError discrepency with client commands
  fabric-command-api-v1/src/main/java/net/fabricmc/fabric/mixin/command/client/ClientCommandSourceMixin.java
Labels: bug, merge me please, priority:medium, small change
