Repository FabricMC/fabric, pull requests merged in 2022-06, with the labels that each got.

#2220 Fabric Message API v1 (experimental)
  fabric-message-api-v1/build.gradle
  fabric-message-api-v1/src/main/java/net/fabricmc/fabric/api/message/v1/ServerMessageDecoratorEvent.java
  fabric-message-api-v1/src/main/java/net/fabricmc/fabric/api/message/v1/ServerMessageEvents.java
  fabric-message-api-v1/src/main/java/net/fabricmc/fabric/mixin/message/MinecraftServerMixin.java
  fabric-message-api-v1/src/main/java/net/fabricmc/fabric/mixin/message/PlayerManagerMixin.java
  fabric-message-api-v1/src/main/resources/assets/fabric-message-api-v1/icon.png
  fabric-message-api-v1/src/main/resources/fabric-message-api-v1.mixins.json
  fabric-message-api-v1/src/main/resources/fabric.mod.json
  fabric-message-api-v1/src/testmod/java/net/fabricmc/fabric/test/message/ChatTest.java
  fabric-message-api-v1/src/testmod/resources/fabric.mod.json
  gradle.properties
  settings.gradle
Labels: enhancement, last call, reviews needed, merge me please, new module

#2273 Add all missing tags for SAVANNA, TAIGA, OVERWORLD and END
  fabric-convention-tags-v1/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BiomeTagGenerator.java
  fabric-convention-tags-v1/src/generated/resources/data/c/tags/worldgen/biome/climate_cold.json
  fabric-convention-tags-v1/src/generated/resources/data/c/tags/worldgen/biome/in_overworld.json
  fabric-convention-tags-v1/src/generated/resources/data/c/tags/worldgen/biome/in_the_end.json
  fabric-convention-tags-v1/src/generated/resources/data/c/tags/worldgen/biome/savanna.json
Labels: bug, merge me please, small change

#2266 Fix errors not showing up in disconnect messages
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/ClientConnectionMixin.java
Labels: bug, fabric-networking, merge me please, small change, priority:high

#2250 A few datagen fixes
  build.gradle
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricBlockLootTableProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/mixin/datagen/ModelProviderMixin.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestContent.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
Labels: bug, merge me please

#2129 Make getKnockbackResistance() work for all materials
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ArmorItemMixin.java
  fabric-item-api-v1/src/main/resources/fabric-item-api-v1.mixins.json
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/ArmorKnockbackResistanceTest.java
  fabric-item-api-v1/src/testmod/resources/assets/fabric-item-api-v1-testmod/models/item/wooden_boots.json
  fabric-item-api-v1/src/testmod/resources/assets/minecraft/textures/models/armor/wood_layer_1.png
  fabric-item-api-v1/src/testmod/resources/assets/minecraft/textures/models/armor/wood_layer_2.png
  fabric-item-api-v1/src/testmod/resources/fabric.mod.json
Labels: merge me please, small change

#2290 Make sure only render thread can call onGameJoin
  fabric-command-api-v2/src/client/java/net/fabricmc/fabric/mixin/command/client/ClientPlayNetworkHandlerMixin.java
Labels: bug, priority:high

#2252 Fix #2237: Allow registering argument types without interacting with the class map
  fabric-command-api-v2/src/main/java/net/fabricmc/fabric/api/command/v2/ArgumentTypeRegistry.java
  fabric-command-api-v2/src/main/java/net/fabricmc/fabric/mixin/command/ArgumentTypesAccessor.java
  fabric-command-api-v2/src/main/resources/fabric-command-api-v2.mixins.json
  fabric-command-api-v2/src/testmod/java/net/fabricmc/fabric/test/command/CustomArgumentTest.java
  fabric-command-api-v2/src/testmod/java/net/fabricmc/fabric/test/command/argument/SmileyArgument.java
  fabric-command-api-v2/src/testmod/java/net/fabricmc/fabric/test/command/argument/SmileyArgumentType.java
  fabric-command-api-v2/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call

#2265 Add SyncDataPackContents and TagsLoaded lifecycle events
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/impl/content/registry/FuelRegistryImpl.java
  fabric-content-registries-v0/src/main/resources/fabric-content-registries-v0.mixins.json
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/api/event/lifecycle/v1/CommonLifecycleEvents.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/api/event/lifecycle/v1/ServerLifecycleEvents.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/DataPackContentsMixin.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/PlayerManagerMixin.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/client/ClientPlayNetworkHandlerMixin.java
  fabric-lifecycle-events-v1/src/main/resources/fabric-lifecycle-events-v1.mixins.json
  fabric-lifecycle-events-v1/src/testmod/java/net/fabricmc/fabric/test/event/lifecycle/CommonLifecycleTests.java
  fabric-lifecycle-events-v1/src/testmod/java/net/fabricmc/fabric/test/event/lifecycle/ServerLifecycleTests.java
  fabric-lifecycle-events-v1/src/testmod/resources/fabric.mod.json
  fabric-mining-level-api-v1/build.gradle
  fabric-mining-level-api-v1/src/main/java/net/fabricmc/fabric/impl/mininglevel/MiningLevelCacheInvalidator.java
  fabric-mining-level-api-v1/src/main/java/net/fabricmc/fabric/impl/mininglevel/MiningLevelManagerImpl.java
  fabric-mining-level-api-v1/src/main/java/net/fabricmc/fabric/mixin/mininglevel/client/ClientPlayNetworkHandlerMixin.java
  fabric-mining-level-api-v1/src/main/resources/fabric-mining-level-api-v1.mixins.json
  fabric-mining-level-api-v1/src/main/resources/fabric.mod.json
Labels: enhancement, last call, priority:medium

#2193 Add registries for villager interactions to fabric-content-registries module
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/StrippableBlockRegistry.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/VillagerInteractionRegistries.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/VillagerPlantableRegistry.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/impl/content/registry/util/ImmutableCollectionUtils.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/mixin/content/registry/FarmerVillagerTaskMixin.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/mixin/content/registry/FarmerWorkTaskAccessor.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/mixin/content/registry/GiveGiftsToHeroTaskAccessor.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/mixin/content/registry/VillagerEntityAccessor.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/mixin/content/registry/VillagerEntityMixin.java
  fabric-content-registries-v0/src/main/resources/fabric-content-registries-v0.mixins.json
  fabric-content-registries-v0/src/testmod/java/net/fabricmc/fabric/test/content/registry/ContentRegistryTest.java
Labels: enhancement, last call

#2282 Fix Biome API bugs
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/BiomeSourceAccess.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/MultiNoiseSamplerHooks.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/NetherBiomeData.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/TheEndBiomeData.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/WeightedPicker.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MixinBiomeSource.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MixinChunkNoiseSampler.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MixinMinecraftServer.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MixinMultiNoiseBiomeSource.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MixinMultiNoiseSampler.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MixinNoiseConfig.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MixinTheEndBiomeSource.java
  fabric-biome-api-v1/src/main/resources/fabric-biome-api-v1.accesswidener
  fabric-biome-api-v1/src/main/resources/fabric-biome-api-v1.mixins.json
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/FabricBiomeTest.java
  fabric-biome-api-v1/src/testmod/resources/data/fabric-biome-api-v1-testmod/worldgen/biome/example_biome.json
Labels: bug, priority:high

#2322 Add some more TAWs to the Datagen Module
  fabric-data-generation-api-v1/build.gradle
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
  fabric-data-generation-api-v1/template.accesswidener
Labels: enhancement, merge me please, small change

#2326 Fix #2108: FlammableBlockRegistry ignores tags unless /reload
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/impl/content/registry/FlammableBlockRegistryImpl.java
  fabric-content-registries-v0/src/testmod/java/net/fabricmc/fabric/test/content/registry/ContentRegistryTest.java
  fabric-content-registries-v0/src/testmod/java/net/fabricmc/fabric/test/content/registry/FlammableTest.java
  fabric-content-registries-v0/src/testmod/resources/fabric.mod.json
Labels: bug, merge me please, priority:medium

#2327 Fix icon path
  fabric-command-api-v2/src/main/resources/assets/fabric-command-api-v2/icon.png
Labels: bug, merge me please, small change, priority:low

#2336 Fix Indigo not rendering replaced models
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/ItemRenderContext.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/mixin/client/indigo/renderer/MixinItemRenderer.java
Labels: bug, indigo, merge me please, priority:medium

#2339 Optimise file exists check for directory based ModNioResourcePacks
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModNioResourcePack.java
Labels: bug, merge me please, priority:high

#2356 Fix registry sync namespace check
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/MixinSimpleRegistry.java
Labels: bug, merge me please, small change, priority:high

#2314 Add FabricLootTableBuilder.modifyPools
  fabric-loot-api-v2/src/main/java/net/fabricmc/fabric/api/loot/v2/FabricLootTableBuilder.java
  fabric-loot-api-v2/src/main/java/net/fabricmc/fabric/api/loot/v2/LootTableEvents.java
  fabric-loot-api-v2/src/main/java/net/fabricmc/fabric/mixin/loot/LootTableBuilderMixin.java
  fabric-loot-api-v2/src/testmod/java/net/fabricmc/fabric/test/loot/LootTest.java
Labels: enhancement, last call, merge me please, small change, priority:low

#2279 Sculk Sensor Frequency Registry
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/SculkSensorFrequencyRegistry.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/mixin/content/registry/SculkSensorBlockMixin.java
  fabric-content-registries-v0/src/main/resources/fabric-content-registries-v0.mixins.json
  fabric-content-registries-v0/src/testmod/java/net/fabricmc/fabric/test/content/registry/ContentRegistryTest.java
  fabric-content-registries-v0/src/testmod/resources/data/minecraft/tags/game_events/vibrations.json
Labels: enhancement, last call, merge me please

#2365 Fix biome modification for modded end biomes
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationImpl.java
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/FabricBiomeTest.java
Labels: bug, merge me please, small change, priority:high

#2338 Make screen API crash easier to debug
  fabric-screen-api-v1/src/client/java/net/fabricmc/fabric/mixin/screen/MinecraftClientMixin.java
  fabric-screen-api-v1/src/client/java/net/fabricmc/fabric/mixin/screen/ScreenMixin.java
Labels: bug, merge me please, small change
