Repository FabricMC/fabric, pull requests merged in 2022-12, with the labels that each got.

#2717 Add producation server test, publish testmod jar to maven.
  .github/workflows/build.yml
  build.gradle
  gradle.properties
Labels: enhancement, merge me please, small change

#2726 Screen API: Fix MinecraftClientMixin overwriting the vanilla logger
  fabric-screen-api-v1/src/client/java/net/fabricmc/fabric/mixin/screen/MinecraftClientMixin.java
Labels: bug, merge me please, small change

#2727 add c:shields common tag
  fabric-convention-tags-v1/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v1/src/generated/resources/data/c/tags/items/shields.json
  fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/api/tag/convention/v1/ConventionalItemTags.java
Labels: enhancement, merge me please, small change, priority:low, next?

#2734 GameTest: add javadoc
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/api/gametest/v1/package-info.java
Labels: merge me please, next?

#2736 Generate AW for DataProvider.getName implementations
  fabric-data-generation-api-v1/build.gradle
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricLanguageProvider.java
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
Labels: enhancement, merge me please, small change

#2741 Refactor FabricBlockSettings to copy and override new stuff
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/FabricBlockSettings.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/AbstractBlockSettingsAccessor.java
Labels: bug, enhancement, merge me please, next?

#2742 Adapt the existing creative inventory page button texture to new position
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/impl/client/itemgroup/FabricCreativeGuiComponents.java
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/mixin/itemgroup/client/CreativeInventoryScreenMixin.java
  fabric-item-group-api-v1/src/main/resources/assets/fabric/textures/gui/creative_buttons.png
Labels: enhancement, merge me please

#2745 Item API: override Item.Settings#requires
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/FabricItemSettings.java
Labels: merge me please, next?

#2751 Fix previous creative tab not being restored
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/mixin/itemgroup/client/CreativeInventoryScreenMixin.java
Labels: bug, priority:high

#2781 Ensure consistent ordering of datagen TAW
  fabric-data-generation-api-v1/build.gradle
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
Labels: merge me please, small change

#2770 Fix disconnect screen scissoring on high-resolution displays
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/mixin/networking/client/DisconnectedScreenMixin.java
Labels: bug, fabric-networking, merge me please, priority:medium, next?

#2769 Disable the gametest command on the server by default.
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/impl/gametest/FabricGameTestHelper.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/ArgumentTypesMixin.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/CommandManagerMixin.java
Labels: bug, merge me please, small change, next?

#2768 Fix #1145: Long enum gamerule name hidden by button
  fabric-game-rule-api-v1/src/client/java/net/fabricmc/fabric/impl/gamerule/widget/EnumRuleWidget.java
  fabric-game-rule-api-v1/src/main/resources/fabric-game-rule-api-v1.accesswidener
  fabric-game-rule-api-v1/src/testmod/resources/assets/fabric-gamerule-test/lang/en_us.json
Labels: bug, merge me please

#2767 Small Cleanups
  fabric-api-base/src/main/java/net/fabricmc/fabric/api/util/NbtType.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerLoginNetworking.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/model/FabricBakedModel.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/simple/FrameBlockEntity.java
  fabric-rendering-data-attachment-v1/src/main/java/net/fabricmc/fabric/api/rendering/data/v1/RenderAttachedBlockView.java
  fabric-rendering-data-attachment-v1/src/main/java/net/fabricmc/fabric/api/rendering/data/v1/RenderAttachmentBlockEntity.java
Labels: merge me please, small change

#2749 Fix block api resources path
  fabric-block-api-v1/src/main/resources/assets/fabric-block-api-v1/icon.png
Labels: bug, merge me please, small change

#2782 Javadoc and typo fixes
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeModificationContext.java
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/event/client/player/ClientPickBlockGatherCallback.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/api/gametest/v1/package-info.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/FabricBlockSettings.java
  fabric-particles-v1/src/client/java/net/fabricmc/fabric/api/client/particle/v1/ParticleFactoryRegistry.java
  fabric-rendering-fluids-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/fluid/FluidRendererMixin.java
  fabric-screen-api-v1/src/client/java/net/fabricmc/fabric/mixin/screen/ScreenMixin.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/unittests/FluidItemTests.java
Labels: next?

#2779 Fix #602: Allow querying registered `DynamicItemRenderer`s
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/BuiltinItemRendererRegistry.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/BuiltinItemRendererRegistryImpl.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/BuiltinModelItemRendererMixin.java
Labels: merge me please, small change

#2780 Add more transitive Access Wideners
  fabric-data-generation-api-v1/build.gradle
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
  fabric-data-generation-api-v1/template.accesswidener
  fabric-transitive-access-wideners-v1/build.gradle
  fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener
  fabric-transitive-access-wideners-v1/template.accesswidener
Labels: enhancement, merge me please

#2582 Deprecated BlockEntityRendererRegistry in favor of vanilla's BlockEntityRendererFactories
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/BlockEntityRendererRegistry.java
  fabric-transitive-access-wideners-v1/build.gradle
  fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener
  fabric-transitive-access-wideners-v1/src/testmod/java/net/fabricmc/fabric/test/access/BlockEntityRendererTest.java
  fabric-transitive-access-wideners-v1/src/testmod/java/net/fabricmc/fabric/test/access/SignBlockEntityTest.java
  fabric-transitive-access-wideners-v1/src/testmod/resources/assets/fabric-transitive-access-wideners-v1-testmod/blockstates/test_sign.json
  fabric-transitive-access-wideners-v1/src/testmod/resources/assets/fabric-transitive-access-wideners-v1-testmod/blockstates/test_wall_sign.json
  fabric-transitive-access-wideners-v1/src/testmod/resources/assets/fabric-transitive-access-wideners-v1-testmod/models/block/test_sign.json
  fabric-transitive-access-wideners-v1/src/testmod/resources/assets/fabric-transitive-access-wideners-v1-testmod/models/item/test_sign.json
  fabric-transitive-access-wideners-v1/src/testmod/resources/fabric.mod.json
  fabric-transitive-access-wideners-v1/template.accesswidener
Labels: last call, merge me please, next?

#2670 API for brewing recipes which use Ingredients instead of Items
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/FabricBrewingRecipeRegistry.java
  fabric-content-registries-v0/src/main/resources/fabric-content-registries-v0.accesswidener
  fabric-content-registries-v0/src/testmod/java/net/fabricmc/fabric/test/content/registry/ContentRegistryTest.java
  fabric-content-registries-v0/src/testmod/java/net/fabricmc/fabric/test/mixin/content/registry/BrewingRecipeRegistryAccessor.java
  fabric-content-registries-v0/src/testmod/resources/fabric-content-registries-v0-testmod.mixins.json
  fabric-content-registries-v0/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call, merge me please, next?

#2776 Add Traditional Chinese
  fabric-resource-loader-v0/src/main/resources/assets/fabric-resource-loader-v0/lang/zh_tw.json
Labels: merge me please

#2784 Don't break the ordering of ResourcePackProviders
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/ResourcePackManagerMixin.java
Labels: bug, merge me please

#2783 Block Entity Lifecycle fixes
  fabric-lifecycle-events-v1/src/client/java/net/fabricmc/fabric/api/client/event/lifecycle/v1/ClientBlockEntityEvents.java
  fabric-lifecycle-events-v1/src/client/java/net/fabricmc/fabric/mixin/event/lifecycle/client/ClientChunkManagerMixin.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/api/event/lifecycle/v1/ServerBlockEntityEvents.java
  fabric-lifecycle-events-v1/src/main/resources/fabric-lifecycle-events-v1.accesswidener
Labels: bug

#2785 Fix ItemGroup language generation.
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricLanguageProvider.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestContent.java
Labels: bug, merge me please
