Repository FabricMC/fabric, pull requests merged in 2022-08, with the labels that each got.

#2154 Move a few object builders to transitive AWs
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/entity/FabricBlockEntityTypeBuilder.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/villager/VillagerProfessionBuilder.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/villager/VillagerTypeHelper.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/VillagerTypeAccessor.java
  fabric-object-builder-api-v1/src/main/resources/fabric-object-builder-api-v1.accesswidener
  fabric-object-builder-api-v1/src/main/resources/fabric-object-builder-v1.mixins.json
  fabric-transitive-access-wideners-v1/build.gradle
  fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener
  fabric-transitive-access-wideners-v1/template.accesswidener
Labels: last call, merge me please

#2307 Add TagUtil
  fabric-convention-tags-v1/build.gradle
  fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/api/tag/convention/v1/TagUtil.java
  fabric-convention-tags-v1/src/testmod/java/net/fabricmc/fabric/test/tag/convention/v1/TagUtilTest.java
  fabric-convention-tags-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call, merge me please

#2308 Add client tags module
  fabric-client-tags-api-v1/build.gradle
  fabric-client-tags-api-v1/src/client/java/net/fabricmc/fabric/api/tag/client/v1/ClientTags.java
  fabric-client-tags-api-v1/src/client/java/net/fabricmc/fabric/impl/tag/client/ClientTagsLoader.java
  fabric-client-tags-api-v1/src/client/resources/assets/fabric-client-tags-api-v1/icon.png
  fabric-client-tags-api-v1/src/client/resources/fabric.mod.json
  fabric-client-tags-api-v1/src/testmod/java/net/fabricmc/fabric/test/tag/client/v1/ClientTagTest.java
  fabric-client-tags-api-v1/src/testmod/resources/fabric.mod.json
  gradle.properties
  settings.gradle
Labels: enhancement, last call, merge me please, new module

#2407 ModResourcePackUtil: Properly handle special chars in mod name
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackUtil.java
  fabric-resource-loader-v0/src/testmod/java/net/fabricmc/fabric/test/resource/loader/BuiltinResourcePackTestMod.java
Labels: bug, merge me please, priority:low

#2421 Make static-only classes final and unconstructible
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeModifications.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/VillagerInteractionRegistries.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/VillagerPlantableRegistry.java
  fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/api/tag/convention/v1/ConventionalBiomeTags.java
  fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/api/tag/convention/v1/ConventionalBlockTags.java
  fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/api/tag/convention/v1/ConventionalEnchantmentTags.java
  fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/api/tag/convention/v1/ConventionalEntityTypeTags.java
  fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/api/tag/convention/v1/ConventionalFluidTags.java
  fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/api/tag/convention/v1/ConventionalItemTags.java
  fabric-lifecycle-events-v1/src/client/java/net/fabricmc/fabric/api/client/event/lifecycle/v1/ClientEntityEvents.java
  fabric-lifecycle-events-v1/src/client/java/net/fabricmc/fabric/api/client/event/lifecycle/v1/ClientTickEvents.java
  fabric-loot-api-v2/src/main/java/net/fabricmc/fabric/api/loot/v2/LootTableEvents.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/entity/FabricDefaultAttributeRegistry.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/entity/MinecartComparatorLogicRegistry.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/model/ModelHelper.java
  fabric-transfer-api-v1/src/client/java/net/fabricmc/fabric/api/transfer/v1/client/fluid/FluidVariantRendering.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidVariantAttributes.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/StoragePreconditions.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/StorageUtil.java
Labels: merge me please, priority:low

#2422 ModelHelper: remove useless contract
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/model/ModelHelper.java
Labels: merge me please, small change, priority:low

#2446 Rename modid to "fabric-api" and provide "fabric". Update loom
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/main/resources/fabric.mod.json
Labels: enhancement, merge me please

#2341 Even More TAWs
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/entity/FabricEntityTypeBuilder.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/SpawnRestrictionAccessor.java
  fabric-object-builder-api-v1/src/main/resources/fabric-object-builder-api-v1.accesswidener
  fabric-object-builder-api-v1/src/main/resources/fabric-object-builder-v1.mixins.json
  fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener
  fabric-transitive-access-wideners-v1/template.accesswidener
Labels: enhancement, last call, merge me please, priority:low
