Repository FabricMC/fabric, pull requests merged in 2022-07, with the labels that each got.

#2344 Fix Indigo AO calculation
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/Indigo.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/aocalc/AoCalculator.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/aocalc/AoLuminanceFix.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/AbstractMeshConsumer.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/AbstractQuadRenderer.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/BlockRenderContext.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/ChunkRenderInfo.java
Labels: bug, indigo, merge me please, priority:medium

#2349 Make disconnected screen reason text scrollable
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/mixin/networking/client/DisconnectedScreenMixin.java
  fabric-networking-api-v1/src/client/resources/fabric-networking-api-v1.client.mixins.json
  fabric-networking-api-v1/src/testmod/java/net/fabricmc/fabric/test/networking/disconnectscreen/DisconnectScreenTest.java
  fabric-networking-api-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, merge me please, small change

#2363 Fix incorrect check in GlobalReceiverRegistry
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/GlobalReceiverRegistry.java
Labels: bug, fabric-networking, merge me please, small change

#2380 Fix inconsistent ordering of item attribute modifiers by using a linked hashmap
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ItemStackMixin.java
Labels: bug, merge me please, small change

#2387 Fix custom dimension not loaded on world preset other than default
  fabric-resource-loader-v0/src/client/java/net/fabricmc/fabric/mixin/resource/loader/client/CreateWorldScreenMixin.java
  fabric-resource-loader-v0/src/client/java/net/fabricmc/fabric/mixin/resource/loader/client/MoreOptionsDialogAccessor.java
  fabric-resource-loader-v0/src/client/resources/fabric-resource-loader-v0.client.mixins.json
Labels: bug, merge me please, priority:high

#2411 Message API: 1.19.1 changes
  fabric-message-api-v1/src/main/java/net/fabricmc/fabric/api/message/v1/ServerMessageDecoratorEvent.java
  fabric-message-api-v1/src/main/java/net/fabricmc/fabric/api/message/v1/ServerMessageEvents.java
  fabric-message-api-v1/src/main/java/net/fabricmc/fabric/mixin/message/PlayerManagerMixin.java
  fabric-message-api-v1/src/testmod/java/net/fabricmc/fabric/test/message/ChatTest.java
Labels: enhancement, merge me please, priority:high

#2425 Fix 1.19.1 command API bugs
  fabric-command-api-v2/src/client/java/net/fabricmc/fabric/impl/command/client/ClientCommandInternals.java
  fabric-command-api-v2/src/client/java/net/fabricmc/fabric/mixin/command/client/ClientCommandSourceMixin.java
  fabric-command-api-v2/src/client/java/net/fabricmc/fabric/mixin/command/client/ClientPlayerEntityMixin.java
Labels: bug, merge me please, priority:high

#2426 Fix: broadcast message headers when chat event is cancelled
  fabric-message-api-v1/src/main/java/net/fabricmc/fabric/mixin/message/PlayerManagerMixin.java
Labels: bug, priority:high

#2377 Add development guidelines (CONTRIBUTING.md)
  CONTRIBUTING.md
  README.md
Labels: merge me please
