Repository FabricMC/fabric, pull requests merged in 2022-02, with the labels that each got.

#1982 Fix Indigo rendering item models without transforms multiple times
  fabric-renderer-indigo/src/main/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/ItemRenderContext.java
Labels: bug, merge me please, small change, priority:medium

#2001 Fix a ClassCastException being thrown when a data pack reload event is invoked
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/MinecraftServerMixin.java
Labels: merge me please

#2009 Fix type passed to data pack reload events.
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/api/event/lifecycle/v1/ServerLifecycleEvents.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/MinecraftServerMixin.java
Labels: bug, port, priority:high

#2010 1.18.2-pre1 Biome API
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeModificationContext.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeModifications.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeSelectionContext.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeSelectors.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/NetherBiomeData.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationContextImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeSelectionContextImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeStructureStartsImpl.java
  fabric-biome-api-v1/src/main/resources/fabric-biome-api-v1.accesswidener
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/FabricBiomeTest.java
  settings.gradle
Labels: port, priority:high

#2019 Misc FabricTagProvider fixes and improvements.
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricTagProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/ForcedTagEntry.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/mixin/datagen/AbstractTagProviderMixin.java
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.mixins.json
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
  fabric-data-generation-api-v1/template.accesswidener
Labels: enhancement, priority:high

#2028 Fix Block2ObjectMap not using TagKey
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/FlammableBlockRegistry.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/util/Block2ObjectMap.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/impl/content/registry/FlammableBlockRegistryImpl.java
Labels: bug, port, priority:high
