Repository FabricMC/fabric, pull requests merged in 2022-01, with the labels that each got.

#1853 Registry sync packet compression II
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/FabricRegistryClientInit.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/FabricRegistryInit.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/RegistryMapSerializer.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/RegistrySyncManager.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/packet/DirectRegistryPacketHandler.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/packet/NbtRegistryPacketHandler.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/packet/RegistryPacketHandler.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/MixinLevelStorageSession.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/MixinPlayerManager.java
  fabric-registry-sync-v0/src/main/resources/fabric-registry-sync-v0.mixins.json
  fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/RegistrySyncTest.java
  fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/RegistrySyncTestClient.java
  fabric-registry-sync-v0/src/testmod/resources/fabric.mod.json
Labels: enhancement, registry-sync, merge me please

#1927 Use the correct information when throwing Exceptions for failed tests.
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/impl/gametest/FabricGameTestHelper.java
Labels: enhancement, merge me please, small change

#1928 Fix attribute modifiers inject limiting other mixins.
  fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/mixin/tool/attribute/MixinItemStack.java
Labels: merge me please, small change

#1938 Preventing END special events with dimensional api
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/dimension/EntityMixin.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/dimension/ServerPlayerEntityMixin.java
  fabric-dimensions-v1/src/main/resources/fabric-dimensions-v1.mixins.json
Labels: bug, priority:medium

#1946 Fix end return spawn location issue.
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/dimension/ServerPlayerEntityMixin.java
Labels: bug, priority:high

#1540 Structure Pool Callback
  fabric-structure-api-v1/src/main/java/net/fabricmc/fabric/api/structure/v1/FabricStructurePool.java
  fabric-structure-api-v1/src/main/java/net/fabricmc/fabric/api/structure/v1/StructurePoolAddCallback.java
  fabric-structure-api-v1/src/main/java/net/fabricmc/fabric/impl/structure/FabricStructurePoolImpl.java
  fabric-structure-api-v1/src/main/java/net/fabricmc/fabric/mixin/structure/DynamicRegistryManagerMixin.java
  fabric-structure-api-v1/src/main/java/net/fabricmc/fabric/mixin/structure/StructurePoolAccessor.java
  fabric-structure-api-v1/src/main/resources/fabric-structure-api-v1.mixins.json
  fabric-structure-api-v1/src/testmod/java/net/fabricmc/fabric/test/structure/StructureTest.java
  fabric-structure-api-v1/src/testmod/resources/data/fabric/structures/cactus_farm.nbt
Labels: enhancement, last call, reviews needed, priority:low

#1945 Fix Indigo UV rotation
  fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/api/renderer/v1/mesh/MutableQuadView.java
  fabric-renderer-indigo/src/main/java/net/fabricmc/fabric/impl/client/indigo/renderer/helper/TextureHelper.java
Labels: merge me please

#1957 Fix tags_populated conditions not working
  fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/api/resource/conditions/v1/DefaultResourceConditions.java
  fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/impl/resource/conditions/ResourceConditionsImpl.java
  fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/mixin/resource/conditions/JsonDataLoaderMixin.java
  fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/mixin/resource/conditions/SinglePreparationResourceReloaderMixin.java
  fabric-resource-conditions-api-v1/src/main/resources/fabric-resource-conditions-api-v1.mixins.json
  fabric-resource-conditions-api-v1/src/testmod/java/net/fabricmc/fabric/test/resource/conditions/ConditionalResourcesTest.java
  fabric-resource-conditions-api-v1/src/testmod/resources/data/fabric-resource-conditions-api-v1-testmod/recipes/item_tags_populated.json
  fabric-resource-conditions-api-v1/src/testmod/resources/data/fabric-resource-conditions-api-v1-testmod/tags/items/test_condition.json
  fabric-resource-conditions-api-v1/src/testmod/resources/fabric.mod.json
Labels: bug, merge me please, priority:high

#1966 Move biome modification into the MinecraftServer constructor
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeSelectionContext.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeSelectors.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/OverworldBiomeData.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationMarker.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeSelectionContextImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/DynamicRegistryManagerImplMixin.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/MinecraftServerMixin.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/RegistryOpsMixin.java
  fabric-biome-api-v1/src/main/resources/fabric-biome-api-v1.accesswidener
  fabric-biome-api-v1/src/main/resources/fabric-biome-api-v1.mixins.json
Labels: bug, enhancement, merge me please, priority:medium

#1962 workaround https://github.com/FabricMC/Mixin/issues/76
  fabric-entity-events-v1/src/main/resources/fabric-entity-events-v1.mixins.json
Labels: bug, merge me please, small change, priority:medium
