Repository FabricMC/fabric, pull requests merged in 2022-03, with the labels that each got.

#1918 Support Loader 0.13's multiple mod root paths, optimize ModNioResourcePack
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModNioResourcePack.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackUtil.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ResourceManagerHelperImpl.java
  fabric-resource-loader-v0/src/main/resources/fabric.mod.json
  gradle.properties
  src/main/resources/fabric.mod.json
Labels: enhancement, merge me please

#1979 Fix #1912 and #1972: inventory updates in transactions
  checkstyle.xml
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/TransferApiImpl.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/item/InventorySlotWrapper.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/item/SpecialLogicInventory.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/mixin/transfer/AbstractFurnaceBlockEntityMixin.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/mixin/transfer/LootableContainerBlockEntityMixin.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/mixin/transfer/SimpleInventoryMixin.java
  fabric-transfer-api-v1/src/main/resources/fabric-transfer-api-v1.mixins.json
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/gametests/VanillaStorageTests.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/mixin/AbstractFurnaceBlockEntityAccessor.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/unittests/ItemTests.java
  fabric-transfer-api-v1/src/testmod/resources/fabric-transfer-api-v1-testmod.mixins.json
  fabric-transfer-api-v1/src/testmod/resources/fabric.mod.json
Labels: bug, merge me please

#2024 Order of operations
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/entity/FabricEntityTypeBuilder.java
Labels: bug, merge me please, small change

#2037 Fix MC-197259 - Modded blocks not present in debug world type. Closes #2031
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/trackers/vanilla/BlockInitTracker.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/AccessorDebugChunkGenerator.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/MixinMinecraftServer.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/client/MixinMinecraftClient.java
  fabric-registry-sync-v0/src/main/resources/fabric-registry-sync-v0.mixins.json
Labels: bug, registry-sync, merge me please, small change, priority:medium

#2045 Fix missing structures causing chunks to reset on upgrade.
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/MixinChunkSerializer.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/MixinStructuresToConfiguredStructuresFix.java
  fabric-registry-sync-v0/src/main/resources/fabric-registry-sync-v0.mixins.json
Labels: bug, reviews needed, merge me please, priority:high

#2070 Fix optional tag from TagKey datagen
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricTagProvider.java
Labels: bug, merge me please, small change

#2069 Allow dots in namespaces to match vanilla behavior (fabric-resource-loader-v0)
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModNioResourcePack.java
Labels: bug, merge me please, small change, priority:medium

#2054 Add `fabric-registry-sync-v0` to all testmods runtime classpath
  build.gradle
Labels: enhancement, merge me please, small change

#2044 Create transitive AW module
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/advancement/CriterionRegistry.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/client/model/FabricModelPredicateProviderRegistry.java
  fabric-screen-handler-api-v1/src/main/java/net/fabricmc/fabric/api/client/screenhandler/v1/ScreenRegistry.java
  fabric-screen-handler-api-v1/src/main/java/net/fabricmc/fabric/api/screenhandler/v1/ScreenHandlerRegistry.java
  fabric-transitive-access-wideners-v1/README.md
  fabric-transitive-access-wideners-v1/build.gradle
  fabric-transitive-access-wideners-v1/src/main/resources/assets/fabric-transitive-access-wideners-v1/icon.png
  fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener
  fabric-transitive-access-wideners-v1/src/main/resources/fabric.mod.json
  fabric-transitive-access-wideners-v1/template.accesswidener
  gradle.properties
  settings.gradle
Labels: enhancement, last call, reviews needed, merge me please, new module, priority:low

#2062 Jar and PGP sign artifacts.
  .github/workflows/release.yml
  build.gradle
Labels: enhancement, merge me please, priority:medium

#2081 Fix 22w11a crash due to invalid signature
  fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/mixin/screen/MinecraftClientMixin.java
Labels: bug, small change, priority:high

#2092 Fix #2091: multiple mods adding to the same tag not working
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/GroupResourcePack.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/NamespaceResourceManagerMixin.java
  fabric-resource-loader-v0/src/main/resources/fabric-resource-loader-v0.accesswidener
Labels: bug, small change, priority:high
