Repository FabricMC/fabric, pull requests merged in 2022-11, with the labels that each got.

#2632 22w44a
  build.gradle
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeModificationContext.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeSelectionContext.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeSelectors.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/MultiNoiseSamplerHooks.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/NetherBiomeData.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/TheEndBiomeData.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationContextImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BuiltInRegistryKeys.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/ChunkNoiseSamplerMixin.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MinecraftServerMixin.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MultiNoiseUtilMultiNoiseSamplerMixin.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/NoiseConfigMixin.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/TheEndBiomeSourceMixin.java
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/DataGeneratorEntrypoint.java
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/FabricBiomeTest.java
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/WorldgenProvider.java
  fabric-command-api-v2/src/client/java/net/fabricmc/fabric/mixin/command/client/ClientPlayNetworkHandlerMixin.java
  fabric-convention-tags-v1/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BiomeTagGenerator.java
  fabric-convention-tags-v1/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BlockTagGenerator.java
  fabric-convention-tags-v1/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnchantmentTagGenerator.java
  fabric-convention-tags-v1/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EntityTypeTagGenerator.java
  fabric-convention-tags-v1/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/FluidTagGenerator.java
  fabric-convention-tags-v1/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/FabricDataGenerator.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricBuiltinRegistriesProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricTagProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricWorldgenProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/FabricDataGenHelper.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/mixin/datagen/AbstractTagProviderMixin.java
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestContent.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
  fabric-data-generation-api-v1/template.accesswidener
  fabric-dimensions-v1/src/testmod/java/net/fabricmc/fabric/test/dimension/VoidChunkGenerator.java
  fabric-game-rule-api-v1/src/client/java/net/fabricmc/fabric/impl/gamerule/widget/EnumRuleWidget.java
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/impl/itemgroup/FabricCreativeGuiComponents.java
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/mixin/itemgroup/ItemGroupMixin.java
  fabric-item-group-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/group/ItemGroupTest.java
  fabric-networking-api-v1/src/testmod/java/net/fabricmc/fabric/test/networking/channeltest/ChannelScreen.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/DynamicRegistrySync.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/BuiltinRegistriesMixin.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/MinecraftServerMixin.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/RegistryLoaderMixin.java
  fabric-registry-sync-v0/src/main/resources/fabric-registry-sync-v0.mixins.json
  fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/RegistrySyncTest.java
  fabric-rendering-fluids-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/fluid/FluidRenderHandlerRegistryImpl.java
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/CustomFluid.java
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/NoOverlayFluid.java
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/OverlayFluid.java
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/UnregisteredFluid.java
  fabric-screen-api-v1/src/testmod/java/net/fabricmc/fabric/test/screen/StopSoundButton.java
  fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener
  gradle.properties
Labels: port, priority:high

#2573 Add `AFTER_DEATH` and `ALLOW_DAMAGE` events; generalise `ALLOW_DEATH` to living entities
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/ServerLivingEntityEvents.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/ServerPlayerEvents.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/LivingEntityMixin.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/ServerPlayerEntityMixin.java
  fabric-entity-events-v1/src/testmod/java/net/fabricmc/fabric/test/entity/event/EntityEventTests.java
Labels: enhancement, last call, merge me please, priority:low

#2589 Implement a version of `FabricDefaultAttributeRegistry#register` that takes a `DefaultAttributeContainer`
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/entity/FabricDefaultAttributeRegistry.java
Labels: last call, merge me please, small change, priority:low

#2593 Edit `ko-kr` translations for `resource-loader`
  fabric-resource-loader-v0/src/main/resources/assets/fabric-resource-loader-v0/lang/ko_kr.json
Labels: merge me please, small change, priority:low

#2653 Item Group API: fix bugs in 22w45a port
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/impl/itemgroup/CreativeGuiExtensions.java
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/impl/itemgroup/FabricCreativeGuiComponents.java
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/mixin/itemgroup/client/CreativeInventoryScreenMixin.java
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/impl/itemgroup/ItemGroupHelper.java
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/mixin/itemgroup/ItemGroupMixin.java
Labels: bug, merge me please, priority:high, next?

#2650 Biome API: modify Nether biomes a bit earlier
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MinecraftServerMixin.java
Labels: bug, merge me please, small change, priority:high, next?

#2638 Rename FabricWorldgenProvider
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/WorldgenProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricDynamicRegistryProvider.java
Labels: merge me please, next?

#2637 Item Group API: Expose showOpRestrictedItems
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/api/itemgroup/v1/FabricItemGroupEntries.java
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/mixin/itemgroup/ItemGroupMixin.java
Labels: enhancement, merge me please, small change, next?

#2664 Update Gson javadoc link
  build.gradle
Labels: merge me please, small change, priority:low, next?

#2669 Fix shulker boxes accepting other shulkers when using a directionless `InventoryStorage`
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/item/InventorySlotWrapper.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/gametests/VanillaStorageTests.java
Labels: bug, merge me please, small change

#2668 Load modded translations on the server
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/LanguageMixin.java
  fabric-resource-loader-v0/src/main/resources/fabric-resource-loader-v0.mixins.json
  fabric-resource-loader-v0/src/testmod/java/net/fabricmc/fabric/test/resource/loader/LanguageTestMod.java
  fabric-resource-loader-v0/src/testmod/resources/fabric.mod.json
Labels: enhancement, merge me please, small change, next?

#2666 [1.19.2] Adjust nether biomes injection point
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/MinecraftServerMixin.java
Labels: bug, merge me please

#2635 Access-widen `ItemModelGenerator#writer`
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
  fabric-data-generation-api-v1/template.accesswidener
Labels: merge me please, small change

#2618 Fixed ScreenEvents Javadoc
  fabric-screen-api-v1/src/client/java/net/fabricmc/fabric/api/client/screen/v1/ScreenEvents.java
Labels: merge me please, small change

#2617 Split all duplicated packages
  checkstyle.xml
  deprecated/fabric-events-lifecycle-v0/src/client/java/net/fabricmc/fabric/impl/event/lifecycle/v0/client/LegacyClientEventInvokers.java
  deprecated/fabric-events-lifecycle-v0/src/main/java/net/fabricmc/fabric/impl/event/lifecycle/v0/LegacyEventInvokers.java
  deprecated/fabric-events-lifecycle-v0/src/main/resources/fabric.mod.json
  deprecated/fabric-networking-v0/src/client/java/net/fabricmc/fabric/api/network/ClientSidePacketRegistry.java
  deprecated/fabric-networking-v0/src/client/java/net/fabricmc/fabric/impl/client/networking/v0/ClientSidePacketRegistryImpl.java
  deprecated/fabric-networking-v0/src/client/java/net/fabricmc/fabric/impl/client/networking/v0/OldClientNetworkingHooks.java
  deprecated/fabric-networking-v0/src/main/java/net/fabricmc/fabric/api/network/ServerSidePacketRegistry.java
  deprecated/fabric-networking-v0/src/main/java/net/fabricmc/fabric/impl/networking/v0/OldNetworkingHooks.java
  deprecated/fabric-networking-v0/src/main/java/net/fabricmc/fabric/impl/networking/v0/ServerSidePacketRegistryImpl.java
  deprecated/fabric-networking-v0/src/main/resources/fabric.mod.json
  deprecated/fabric-rendering-v0/src/client/java/net/fabricmc/fabric/impl/client/rendering/v0/RenderingCallbackInvoker.java
  deprecated/fabric-rendering-v0/src/client/resources/fabric.mod.json
  fabric-entity-events-v1/src/client/java/net/fabricmc/fabric/mixin/client/entity/event/elytra/ClientPlayerEntityMixin.java
  fabric-entity-events-v1/src/client/resources/fabric-entity-events-v1.client.mixins.json
  fabric-item-groups-v0/src/client/java/net/fabricmc/fabric/impl/client/item/group/CreativeGuiExtensions.java
  fabric-item-groups-v0/src/client/java/net/fabricmc/fabric/impl/client/item/group/FabricCreativeGuiComponents.java
  fabric-item-groups-v0/src/client/java/net/fabricmc/fabric/mixin/item/group/client/CreativeInventoryScreenMixin.java
  fabric-item-groups-v0/src/client/java/net/fabricmc/fabric/mixin/item/group/client/ItemGroupMixin.java
  fabric-lifecycle-events-v1/src/client/java/net/fabricmc/fabric/impl/client/event/lifecycle/ClientLifecycleEventsImpl.java
  fabric-lifecycle-events-v1/src/main/resources/fabric.mod.json
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientNetworkingImpl.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/mixin/networking/client/accessor/ConnectScreenAccessor.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/mixin/networking/client/accessor/MinecraftClientAccessor.java
  fabric-networking-api-v1/src/client/resources/fabric-networking-api-v1.client.mixins.json
  fabric-registry-sync-v0/src/client/java/net/fabricmc/fabric/impl/client/registry/sync/FabricRegistryClientInit.java
  fabric-registry-sync-v0/src/main/resources/fabric.mod.json
Labels: merge me please, small change

#2556 Support stack aware recipe remainders 1.19.2
  fabric-item-api-v1/build.gradle
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/FabricItem.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/FabricItemStack.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/impl/item/RecipeRemainderHandler.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/AbstractFurnaceBlockEntityMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/BrewingStandBlockEntityMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ItemStackMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/RecipeMixin.java
  fabric-item-api-v1/src/main/resources/fabric-item-api-v1.mixins.json
  fabric-item-api-v1/src/main/resources/fabric.mod.json
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/CustomDamageTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/BrewingStandGameTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/FurnaceGameTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/RecipeGameTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/mixin/BrewingRecipeRegistryAccessor.java
  fabric-item-api-v1/src/testmod/resources/data/fabric-item-api-v1-testmod/recipes/weird_pickaxe.json
  fabric-item-api-v1/src/testmod/resources/fabric-item-api-tests-v1.mixins.json
  fabric-item-api-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call, merge me please, next?

#2659 Fix #2657: Transfer API edge case with bad isValid overrides
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/item/InventorySlotWrapper.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/gametests/VanillaStorageTests.java
Labels: bug, merge me please

#2674 Fix crash in 1.19.3 stack remainder test port
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/CustomDamageTest.java
Labels: bug, test, priority:high

#2615 Generate package-info files for all impl and mixin packages
  .gitignore
  CONTRIBUTING.md
  build.gradle
  fabric-api-base/src/main/java/net/fabricmc/fabric/impl/base/event/PhaseSorting.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/NetherBiomeData.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/TheEndBiomeData.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationContextImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationMarker.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeSelectionContextImpl.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BuiltInRegistryKeys.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/impl/dimension/FabricDimensionInternals.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/impl/dimension/Teleportable.java
  fabric-rendering-data-attachment-v1/src/main/java/net/fabricmc/fabric/impl/rendering/data/attachment/RenderDataObjectConsumer.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModNioResourcePack.java
  fabric-screen-api-v1/src/client/java/net/fabricmc/fabric/impl/client/screen/ButtonList.java
  fabric-screen-api-v1/src/client/java/net/fabricmc/fabric/impl/client/screen/ScreenEventFactory.java
  fabric-screen-api-v1/src/client/java/net/fabricmc/fabric/impl/client/screen/ScreenExtensions.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/item/SpecialLogicInventory.java
  gradle/package-info.gradle
Labels: enhancement, merge me please, priority:low

#2678 Add automated client smoke tests.
  .github/workflows/build.yml
  build.gradle
  fabric-api-base/build.gradle
  fabric-api-base/src/testmod/java/net/fabricmc/fabric/test/base/FabricApiAutoTestClient.java
  fabric-api-base/src/testmod/java/net/fabricmc/fabric/test/base/FabricApiAutoTestServer.java
  fabric-api-base/src/testmod/java/net/fabricmc/fabric/test/base/FabricApiBaseTestInit.java
  fabric-api-base/src/testmod/java/net/fabricmc/fabric/test/base/FabricClientTestHelper.java
  fabric-api-base/src/testmod/java/net/fabricmc/fabric/test/base/mixin/CyclingButtonWidgetAccessor.java
  fabric-api-base/src/testmod/java/net/fabricmc/fabric/test/base/mixin/ScreenAccessor.java
  fabric-api-base/src/testmod/resources/fabric-api-base-testmod.mixins.json
  fabric-api-base/src/testmod/resources/fabric.mod.json
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/ingame/client/FluidVariantRenderTest.java
Labels: enhancement, merge me please, test, priority:low

#2683 Add license to client only etries for client modules.
  build.gradle
Labels: bug, merge me please, small change

#2689 Add coverage task
  build.gradle
Labels: enhancement, merge me please, test, priority:low

#2688 Cleanup Renderer API testmod
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/WorldRenderExtensions.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/mixin/ClientWorldMixin.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/mixin/WorldMixin.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/simple/FrameBlock.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/simple/FrameBlockEntity.java
  fabric-renderer-api-v1/src/testmod/resources/fabric-renderer-api-v1-testmod.mixins.json
  fabric-renderer-api-v1/src/testmod/resources/fabric.mod.json
Labels: merge me please, test

#2681 Add DataGeneratorEntrypoint.buildRegistry
  fabric-biome-api-v1/src/testmod/generated/data/fabric-biome-api-v1-testmod/tags/worldgen/biome/biome_tag_test.json
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/DataGeneratorEntrypoint.java
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/FabricBiomeTest.java
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/TestBiomeTagProvider.java
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/TestBiomes.java
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/WorldgenProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/DataGeneratorEntrypoint.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/FabricDataGenHelper.java
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
  fabric-data-generation-api-v1/template.accesswidener
Labels: enhancement, merge me please, priority:medium, next?

#2700 Do not recommend an api that doesn't exist anymore
  fabric-rendering-fluids-v1/src/main/resources/fabric.mod.json
Labels: bug, merge me please, small change, priority:low

#2698 1.19.3-pre2 javadoc fixes
  deprecated/fabric-loot-tables-v1/src/main/java/net/fabricmc/fabric/api/loot/v1/LootEntryTypeRegistry.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/DataGeneratorEntrypoint.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/FabricDataGenerator.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/package-info.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricAdvancementProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricBlockLootTableProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricLanguageProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricModelProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricRecipeProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricTagProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/SimpleFabricLootTableProvider.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/FabricItem.java
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/api/itemgroup/v1/FabricItemGroup.java
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/api/itemgroup/v1/FabricItemGroupEntries.java
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/api/itemgroup/v1/ItemGroupEvents.java
  fabric-screen-api-v1/src/client/java/net/fabricmc/fabric/api/client/screen/v1/ScreenEvents.java
Labels: merge me please, priority:medium

#2697 Add FabricDataGenerator.createBuiltinResourcePack to support data gen for builtin resource packs.
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/FabricDataGenerator.java
Labels: enhancement, merge me please, priority:high

#2695 Add access widener for SoundEvent.of
  fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener
  fabric-transitive-access-wideners-v1/template.accesswidener
Labels: enhancement, merge me please, small change, priority:medium

#2693 Improved error handling in FabricGameTestHelper
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/impl/gametest/FabricGameTestHelper.java
Labels: enhancement, merge me please, small change, priority:low

#2692 Add some useful helper methods to FabricDynamicRegistryProvider.Entries
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/WorldgenProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricDynamicRegistryProvider.java
Labels: enhancement, merge me please, small change, priority:medium

#2658 Resource Conditions: add feature_enabled
  fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/api/resource/conditions/v1/DefaultResourceConditions.java
  fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/impl/resource/conditions/ResourceConditionsImpl.java
  fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/mixin/resource/conditions/DataPackContentsMixin.java
  fabric-resource-conditions-api-v1/src/testmod/java/net/fabricmc/fabric/test/resource/conditions/ConditionalResourcesTest.java
  fabric-resource-conditions-api-v1/src/testmod/resources/data/fabric-resource-conditions-api-v1-testmod/recipes/features_enabled.json
Labels: enhancement, priority:medium

#2686 Add `BakedModel` unwrapping API
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/model/ForwardingBakedModel.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/model/WrapperBakedModel.java
Labels: enhancement, last call, small change

#2712 Networking: fix type of created packet
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/api/client/networking/v1/ClientPlayNetworking.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientNetworkingImpl.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerPlayNetworking.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerNetworkingImpl.java
Labels: bug, fabric-networking, small change, priority:medium
