Repository FabricMC/fabric, pull requests merged in 2023-11, with the labels that each got.

#3397 Fix Doubles not being editable in the game-rule menu
  fabric-game-rule-api-v1/src/main/java/net/fabricmc/fabric/api/gamerule/v1/rule/DoubleRule.java
  fabric-game-rule-api-v1/src/main/java/net/fabricmc/fabric/api/gamerule/v1/rule/ValidateableRule.java
Labels: bug, merge me please

#3394 Network addon session refactor
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientLoginNetworkAddon.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientPlayNetworkAddon.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/mixin/networking/client/ClientCommonNetworkHandlerMixin.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/mixin/networking/client/ClientLoginNetworkHandlerMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/AbstractChanneledNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/AbstractNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/GlobalReceiverRegistry.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/payload/PayloadHelper.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerConfigurationNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerLoginNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerPlayNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/ClientConnectionMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/CustomPayloadC2SPacketMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/CustomPayloadS2CPacketMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/LoginQueryRequestS2CPacketMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/LoginQueryResponseC2SPacketMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/ServerConfigurationNetworkHandlerMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/ServerLoginNetworkHandlerMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/ServerPlayNetworkHandlerMixin.java
Labels: bug, merge me please, priority:high

#3389 Fix custom ingredient serialization with allowEmpty
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/CustomIngredientImpl.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/mixin/recipe/ingredient/IngredientMixin.java
  fabric-recipe-api-v1/src/testmod/java/net/fabricmc/fabric/test/recipe/ingredient/SerializationTests.java
Labels: bug, merge me please

#3421 23w45a porting fixes
  fabric-dimensions-v1/src/testmod/java/net/fabricmc/fabric/test/dimension/FabricDimensionTest.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/FabricBlockSettings.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/type/BlockSetTypeBuilder.java
  fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener
  fabric-transitive-access-wideners-v1/template.accesswidener
Labels: bug, merge me please, small change

#3416 Backport #2901 to 1.18.2
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/api/client/rendering/v1/CoreShaderRegistrationCallback.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/impl/client/rendering/FabricShader.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/shader/GameRendererMixin.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/shader/ShaderImportProcessorMixin.java
  fabric-rendering-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/shader/ShaderMixin.java
  fabric-rendering-v1/src/main/resources/fabric-rendering-v1.mixins.json
  fabric-rendering-v1/src/testmod/java/net/fabricmc/fabric/test/rendering/client/HudAndShaderTest.java
  fabric-rendering-v1/src/testmod/resources/assets/fabric-rendering-v1-testmod/shaders/core/test.fsh
  fabric-rendering-v1/src/testmod/resources/assets/fabric-rendering-v1-testmod/shaders/core/test.json
  fabric-rendering-v1/src/testmod/resources/assets/fabric-rendering-v1-testmod/shaders/core/test.vsh
  fabric-rendering-v1/src/testmod/resources/assets/fabric-rendering-v1-testmod/shaders/core/test_local_import.glsl
  fabric-rendering-v1/src/testmod/resources/assets/fabric-rendering-v1-testmod/shaders/include/test_include.glsl
  fabric-rendering-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, merge me please, port

#3413 Backport #2901 to 1.19.2
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/CoreShaderRegistrationCallback.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/FabricShader.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/shader/GameRendererMixin.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/shader/ShaderImportProcessorMixin.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/shader/ShaderMixin.java
  fabric-rendering-v1/src/client/resources/fabric-rendering-v1.mixins.json
  fabric-rendering-v1/src/testmod/java/net/fabricmc/fabric/test/rendering/client/HudAndShaderTest.java
  fabric-rendering-v1/src/testmod/resources/assets/fabric-rendering-v1-testmod/shaders/core/test.fsh
  fabric-rendering-v1/src/testmod/resources/assets/fabric-rendering-v1-testmod/shaders/core/test.json
  fabric-rendering-v1/src/testmod/resources/assets/fabric-rendering-v1-testmod/shaders/core/test.vsh
  fabric-rendering-v1/src/testmod/resources/assets/fabric-rendering-v1-testmod/shaders/core/test_local_import.glsl
  fabric-rendering-v1/src/testmod/resources/assets/fabric-rendering-v1-testmod/shaders/include/test_include.glsl
  fabric-rendering-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, merge me please, port

#3433 1.19.2 backport of #3146
  fabric-particles-v1/build.gradle
  fabric-particles-v1/src/client/java/net/fabricmc/fabric/api/client/particle/v1/ParticleRenderEvents.java
  fabric-particles-v1/src/client/java/net/fabricmc/fabric/mixin/client/particle/BlockDustParticleMixin.java
  fabric-particles-v1/src/client/resources/fabric-particles-v1.client.mixins.json
  fabric-particles-v1/src/main/resources/fabric.mod.json
  fabric-particles-v1/src/testmod/java/net/fabricmc/fabric/test/particle/ParticleTestSetup.java
  fabric-particles-v1/src/testmod/java/net/fabricmc/fabric/test/particle/ParticleTintTestBlock.java
  fabric-particles-v1/src/testmod/java/net/fabricmc/fabric/test/particle/client/ParticleRenderEventTests.java
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/blockstates/always_tinted.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/blockstates/never_tinted.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/blockstates/tinted_over_water.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/lang/en_us.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/models/block/tint_test.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/models/item/always_tinted.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/models/item/never_tinted.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/models/item/tinted_over_water.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/textures/block/tint_test.png
  fabric-particles-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, merge me please, port

#3432 Fix registry resource conditions on loot tables.
  fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/mixin/resource/conditions/LootManagerMixin.java
  fabric-resource-conditions-api-v1/src/main/resources/fabric-resource-conditions-api-v1.mixins.json
  fabric-resource-conditions-api-v1/src/testmod/java/net/fabricmc/fabric/test/resource/conditions/ConditionalResourcesTest.java
  fabric-resource-conditions-api-v1/src/testmod/resources/data/fabric-resource-conditions-api-v1-testmod/loot_tables/blocks/loaded.json
  fabric-resource-conditions-api-v1/src/testmod/resources/data/fabric-resource-conditions-api-v1-testmod/loot_tables/blocks/not_loaded.json
Labels: bug, merge me please

#3407 Avoid serializing object-based payload into `PacketByteBuf` on the main thread
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/api/client/networking/v1/ClientConfigurationNetworking.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/api/client/networking/v1/ClientPlayNetworking.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientNetworkingImpl.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientPlayNetworkAddon.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/mixin/networking/client/ClientCommonNetworkHandlerMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerConfigurationNetworking.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerPlayNetworking.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/AbstractChanneledNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/GlobalReceiverRegistry.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/NetworkingImpl.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/payload/ResolvablePayload.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/payload/ResolvedPayload.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/payload/RetainedPayload.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/payload/TypedPayload.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/payload/UntypedPayload.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerConfigurationNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerNetworkingImpl.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerPlayNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/CustomPayloadC2SPacketMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/CustomPayloadS2CPacketMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/ServerCommonNetworkHandlerMixin.java
  fabric-networking-api-v1/src/test/java/net/fabricmc/fabric/test/networking/unit/CommonPacketTests.java
Labels: fabric-networking, merge me please

#3446 Only retain buffer on receiving side
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/NetworkingImpl.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/payload/PayloadHelper.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/CustomPayloadC2SPacketMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/CustomPayloadS2CPacketMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/NetworkStateInternalPacketHandlerMixin.java
  fabric-networking-api-v1/src/main/resources/fabric-networking-api-v1.mixins.json
  fabric-networking-api-v1/src/testmod/java/net/fabricmc/fabric/test/networking/play/NetworkingPlayPacketTest.java
Labels: bug, fabric-networking, merge me please, priority:high
