Repository FabricMC/fabric, pull requests merged in 2023-03, with the labels that each got.

#2940 Fixed end biome source injection
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/TheEndBiomeSourceMixin.java
Labels: bug, merge me please, small change, priority:medium

#2935 EquipmentSlotProvider: Add javadoc link to getPreferredEquipmentSlot
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/EquipmentSlotProvider.java
Labels: merge me please, small change, priority:low

#2901 Add registry for core shaders in custom namespaces
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/CoreShaderRegistrationCallback.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/FabricShaderProgram.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/shader/GameRendererMixin.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/shader/ShaderProgramImportProcessorMixin.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/shader/ShaderProgramMixin.java
  fabric-rendering-v1/src/client/resources/fabric-rendering-v1.mixins.json
  fabric-rendering-v1/src/testmod/java/net/fabricmc/fabric/test/rendering/client/HudAndShaderTest.java
  fabric-rendering-v1/src/testmod/resources/assets/fabric-rendering-v1-testmod/shaders/core/test.fsh
  fabric-rendering-v1/src/testmod/resources/assets/fabric-rendering-v1-testmod/shaders/core/test.json
  fabric-rendering-v1/src/testmod/resources/assets/fabric-rendering-v1-testmod/shaders/core/test.vsh
  fabric-rendering-v1/src/testmod/resources/assets/fabric-rendering-v1-testmod/shaders/core/test_local_import.glsl
  fabric-rendering-v1/src/testmod/resources/assets/fabric-rendering-v1-testmod/shaders/include/test_include.glsl
  fabric-rendering-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call, priority:low, next?

#2947 Fix custom packet inside of bundled packet not being processed
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientPlayNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerPlayNetworkAddon.java
  fabric-networking-api-v1/src/testmod/java/net/fabricmc/fabric/test/networking/play/NetworkingPlayPacketTest.java
Labels: priority:high

#2878 Add 'Windswept Hills' biome convention tag
  fabric-convention-tags-v1/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BiomeTagGenerator.java
  fabric-convention-tags-v1/src/generated/resources/data/c/tags/worldgen/biome/windswept.json
  fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/api/tag/convention/v1/ConventionalBiomeTags.java
Labels: enhancement, priority:low

#2956 Fix Programmer Art injection support (1.19.2)
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackUtil.java
Labels: bug, small change, priority:medium, next?
