Repository FabricMC/fabric, pull requests merged in 2023-12, with the labels that each got.

#3431 Fix `FluidStorageUtil#moveWithSound` Play Sound
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidStorageUtil.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/ingame/FluidChuteBlock.java
Labels: bug, merge me please, small change

#3452 Update loom and Gradle
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: merge me please, small change

#3367 Add Client After Block Break Event
  fabric-events-interaction-v0/src/client/java/net/fabricmc/fabric/api/event/client/player/ClientPlayerBlockBreakEvents.java
  fabric-events-interaction-v0/src/client/java/net/fabricmc/fabric/mixin/event/interaction/client/ClientPlayerInteractionManagerMixin.java
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/event/player/PlayerBlockBreakEvents.java
  fabric-events-interaction-v0/src/testmod/java/net/fabricmc/fabric/test/event/interaction/PlayerBreakBlockTests.java
  fabric-events-interaction-v0/src/testmod/resources/fabric.mod.json
  fabric-events-interaction-v0/src/testmodClient/java/net/fabricmc/fabric/test/client/event/interaction/ClientPlayerBlockBreakTests.java
Labels: enhancement, last call, merge me please, priority:low
