Repository FabricMC/fabric, pull requests merged in 2023-07, with the labels that each got.

#3167 Add vi_vn.json
  fabric-item-group-api-v1/src/main/resources/assets/fabric/lang/vi_vn.json
  fabric-resource-loader-v0/src/main/resources/assets/fabric-resource-loader-v0/lang/vi_vn.json
Labels: merge me please, small change

#3166 Update Finnish translation
  fabric-resource-loader-v0/src/main/resources/assets/fabric-resource-loader-v0/lang/fi_fi.json
Labels: enhancement, merge me please, small change

#3115 Add builders for BlockSetType and WoodType to replace registries
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/type/BlockSetTypeBuilder.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/type/BlockSetTypeRegistry.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/type/WoodTypeBuilder.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/type/WoodTypeRegistry.java
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/TealSignTest.java
Labels: last call, merge me please

#3118 Add support for partially synced client tags
  fabric-client-tags-api-v1/build.gradle
  fabric-client-tags-api-v1/src/client/java/net/fabricmc/fabric/api/tag/client/v1/ClientTags.java
  fabric-client-tags-api-v1/src/client/java/net/fabricmc/fabric/impl/tag/client/ClientTagsImpl.java
  fabric-client-tags-api-v1/src/client/java/net/fabricmc/fabric/impl/tag/client/ClientTagsLoader.java
  fabric-client-tags-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/tag/client/v1/ClientTagTest.java
  fabric-client-tags-api-v1/src/testmodClient/resources/data/fabric/tags/blocks/sword_efficient.json
  fabric-client-tags-api-v1/src/testmodClient/resources/resourcepacks/test2/data/minecraft/tags/blocks/sword_efficient.json
  fabric-client-tags-api-v1/src/testmodClient/resources/resourcepacks/test2/pack.mcmeta
Labels: enhancement, last call, merge me please

#3141 Fix default fluid names for non-placeable fluids, clarify Storage iterator lifecycle with modification
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidVariantAttributeHandler.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/Storage.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/ingame/ExtractStickItem.java
Labels: bug, merge me please

#3146 Add event for preventing particle tinting for colored blocks
  fabric-particles-v1/build.gradle
  fabric-particles-v1/src/client/java/net/fabricmc/fabric/api/client/particle/v1/ParticleRenderEvents.java
  fabric-particles-v1/src/client/java/net/fabricmc/fabric/mixin/client/particle/BlockDustParticleMixin.java
  fabric-particles-v1/src/client/resources/fabric-particles-v1.client.mixins.json
  fabric-particles-v1/src/main/resources/fabric.mod.json
  fabric-particles-v1/src/testmod/java/net/fabricmc/fabric/test/particle/ParticleTestSetup.java
  fabric-particles-v1/src/testmod/java/net/fabricmc/fabric/test/particle/ParticleTintTestBlock.java
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/blockstates/always_tinted.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/blockstates/never_tinted.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/blockstates/tinted_over_water.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/lang/en_us.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/models/block/tint_test.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/models/item/always_tinted.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/models/item/never_tinted.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/models/item/tinted_over_water.json
  fabric-particles-v1/src/testmod/resources/assets/fabric-particles-v1-testmod/textures/block/tint_test.png
  fabric-particles-v1/src/testmod/resources/fabric.mod.json
  fabric-particles-v1/src/testmodClient/java/net/fabricmc/fabric/test/particle/client/ParticleRenderEventTests.java
Labels: enhancement, last call, merge me please, priority:low

#3164 Fix injected resources not overriding certain vanilla resources (1.20)
  fabric-resource-loader-v0/src/client/java/net/fabricmc/fabric/impl/client/resource/loader/FabricWrappedVanillaResourcePack.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/GroupResourcePack.java
  fabric-resource-loader-v0/src/testmod/resources/assets/minecraft/textures/block/diamond_block.png
  fabric-resource-loader-v0/src/testmod/resources/high_contrast/assets/minecraft/textures/block/diamond_block.png
  fabric-resource-loader-v0/src/testmod/resources/programmer_art/assets/minecraft/textures/block/diamond_block.png
Labels: bug, small change

#3163 Add dynamic registry API
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricDynamicRegistryProvider.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/api/event/registry/DynamicRegistries.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/DynamicRegistriesImpl.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/RegistryLoaderMixin.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SaveLoadingMixin.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SerializableRegistriesMixin.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/TagManagerLoaderMixin.java
  fabric-registry-sync-v0/src/main/resources/fabric-registry-sync-v0.accesswidener
  fabric-registry-sync-v0/src/main/resources/fabric-registry-sync-v0.mixins.json
  fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/CustomDynamicRegistryTest.java
  fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/TestDynamicObject.java
  fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/TestNestedDynamicObject.java
  fabric-registry-sync-v0/src/testmod/resources/data/fabric-registry-sync-v0-testmod/fabric/test_dynamic/first.json
  fabric-registry-sync-v0/src/testmod/resources/data/fabric-registry-sync-v0-testmod/fabric/test_dynamic/second.json
  fabric-registry-sync-v0/src/testmod/resources/data/fabric-registry-sync-v0-testmod/fabric/test_dynamic_nested/synced.json
  fabric-registry-sync-v0/src/testmod/resources/data/fabric-registry-sync-v0-testmod/fabric/test_dynamic_synced_1/synced.json
  fabric-registry-sync-v0/src/testmod/resources/data/fabric-registry-sync-v0-testmod/fabric/test_dynamic_synced_2/synced.json
  fabric-registry-sync-v0/src/testmod/resources/data/fabric-registry-sync-v0-testmod/tags/fabric/test_dynamic_synced_1/test.json
  fabric-registry-sync-v0/src/testmod/resources/fabric.mod.json
  fabric-registry-sync-v0/src/testmodClient/java/net/fabricmc/fabric/test/registry/sync/client/DynamicRegistryClientTest.java
Labels: enhancement, last call, registry-sync, merge me please, priority:low

#3182 Fix #3170
  fabric-message-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/message/ClientPlayNetworkHandlerMixin.java
  fabric-message-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/message/client/ChatTestClient.java
Labels: bug, merge me please, priority:medium, next?

#3183 Make event phase ordering logic usable in other contexts (internally only)
  fabric-api-base/src/main/java/net/fabricmc/fabric/impl/base/event/ArrayBackedEvent.java
  fabric-api-base/src/main/java/net/fabricmc/fabric/impl/base/event/EventPhaseData.java
  fabric-api-base/src/main/java/net/fabricmc/fabric/impl/base/event/PhaseSorting.java
  fabric-api-base/src/main/java/net/fabricmc/fabric/impl/base/toposort/NodeSorting.java
  fabric-api-base/src/main/java/net/fabricmc/fabric/impl/base/toposort/SortableNode.java
  fabric-api-base/src/testmod/java/net/fabricmc/fabric/test/base/EventTests.java
Labels: merge me please, next?

#3190 Fix crash when beehive is broken by fake player
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/mixin/event/interaction/BeehiveBlockMixin.java
  fabric-events-interaction-v0/src/main/resources/fabric-events-interaction-v0.mixins.json
  fabric-events-interaction-v0/src/testmod/java/net/fabricmc/fabric/test/event/interaction/FakePlayerTests.java
Labels: bug, merge me please, priority:high

#3200 Fix Indigo handling of sculk sensor AO
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/Indigo.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/aocalc/AoCalculator.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/BlockRenderContext.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/ChunkRenderInfo.java
Labels: indigo, merge me please, priority:high

#3201 Some more TAWs for block creation and block loot tables
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
  fabric-data-generation-api-v1/template.accesswidener
  fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener
  fabric-transitive-access-wideners-v1/template.accesswidener
Labels: merge me please, small change

#3202 Add the cherry grove biome to the floral biome tag
  fabric-convention-tags-v1/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BiomeTagGenerator.java
  fabric-convention-tags-v1/src/generated/resources/data/c/tags/worldgen/biome/floral.json
  fabric-convention-tags-v1/src/generated/resources/data/c/tags/worldgen/biome/in_overworld.json
Labels: merge me please, small change

#3169 Ukrainian translate
  fabric-item-group-api-v1/src/main/resources/assets/fabric/lang/uk_ua.json
  fabric-resource-loader-v0/src/main/resources/assets/fabric-resource-loader-v0/lang/uk_ua.json
Labels: enhancement, merge me please, small change, priority:low

#3222 Sort item groups to ensure they are in a deterministic order between runs.
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/mixin/itemgroup/ItemGroupsMixin.java
Labels: enhancement, merge me please, small change

#3219 Fix #3215 - Only add namespace to registries added using the Fabric API.
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/DynamicRegistriesImpl.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/RegistryLoaderMixin.java
Labels: bug, registry-sync, merge me please, priority:high

#3212 Clarify nullability of `ModelModifier.AfterBake`
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/ModelModifier.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/impl/client/model/loading/ModelLoadingEventDispatcher.java
  fabric-model-loading-api-v1/src/client/resources/fabric.mod.json
Labels: enhancement, merge me please, small change

#3216 Fix data generation for custom dynamic registry
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricDynamicRegistryProvider.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestContent.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
Labels: bug, merge me please, test, priority:high
