Repository FabricMC/fabric, pull requests merged in 2023-01, with the labels that each got.

#2816 Fixed blocks with vanilla loot tables making strict validation of datagen fail
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricBlockLootTableProvider.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestContent.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
Labels: bug, merge me please, small change

#2813 Catch exception inside client-side JOIN event
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientPlayNetworkAddon.java
Labels: bug, fabric-networking, merge me please, small change, priority:high

#2803 Fix selected common item groups deselecting when reopening or changing pages on creative inv screen
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/mixin/itemgroup/client/CreativeInventoryScreenMixin.java
Labels: bug, merge me please, small change, priority:medium, next?

#2800 Replace useless nullability comments with jetbrains annotation
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/event/player/PlayerBlockBreakEvents.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/impl/item/FabricItemInternals.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/impl/item/ItemExtensions.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ItemMixin.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/entity/FabricEntityTypeBuilder.java
Labels: merge me please, small change, priority:low, next?

#2799 Keybindings API: New Years cleanup
  fabric-key-binding-api-v1/src/client/java/net/fabricmc/fabric/api/client/keybinding/v1/KeyBindingHelper.java
  fabric-key-binding-api-v1/src/client/java/net/fabricmc/fabric/impl/client/keybinding/KeyBindingRegistryImpl.java
Labels: merge me please, small change, next?

#2798 Object builder API updates
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/FabricBlockSettings.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/entity/FabricEntityTypeBuilder.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/entity/MinecartComparatorLogicRegistry.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/trade/TradeOfferHelper.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/DefaultAttributeRegistryMixin.java
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/BlockEntityTypeBuilderTest.java
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/ObjectBuilderGameTest.java
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/VillagerTypeTest1.java
  fabric-object-builder-api-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, merge me please, test, next?

#2795 Autogenerate Item constructor TAWs
  fabric-transitive-access-wideners-v1/build.gradle
  fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener
  fabric-transitive-access-wideners-v1/template.accesswidener
Labels: enhancement, merge me please, small change

#2789 Biome modification API small enhancements
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeModificationContext.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/BiomeModifications.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationContextImpl.java
Labels: bug, enhancement, merge me please, small change, next?

#2774 Fix interaction events
  fabric-events-interaction-v0/src/client/java/net/fabricmc/fabric/mixin/event/interaction/client/ClientPlayerInteractionManagerMixin.java
  fabric-events-interaction-v0/src/client/java/net/fabricmc/fabric/mixin/event/interaction/client/MinecraftClientMixin.java
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/block/BlockAttackInteractionAware.java
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/block/BlockPickInteractionAware.java
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/entity/EntityPickInteractionAware.java
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/event/client/player/ClientPickBlockGatherCallback.java
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/event/player/UseEntityCallback.java
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/impl/event/interaction/InteractionEventsRouterClient.java
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/mixin/event/interaction/ServerPlayNetworkHandlerMixin.java
  fabric-events-interaction-v0/src/testmod/java/net/fabricmc/fabric/test/event/interaction/UseEntityTests.java
  fabric-events-interaction-v0/src/testmod/resources/fabric.mod.json
Labels: bug, last call, merge me please, next?

#2586 Fabric custom ingredient API
  fabric-data-generation-api-v1/build.gradle
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
  fabric-recipe-api-v1/build.gradle
  fabric-recipe-api-v1/src/client/java/net/fabricmc/fabric/impl/recipe/ingredient/client/CustomIngredientSyncClient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/api/recipe/v1/ingredient/CustomIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/api/recipe/v1/ingredient/CustomIngredientSerializer.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/api/recipe/v1/ingredient/DefaultCustomIngredients.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/api/recipe/v1/ingredient/FabricIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/CustomIngredientImpl.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/CustomIngredientInit.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/CustomIngredientSync.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/ShapelessMatch.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/SupportedIngredientsPacketEncoder.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/builtin/AllIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/builtin/AnyIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/builtin/CombinedIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/builtin/DifferenceIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/builtin/NbtIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/mixin/recipe/ingredient/IngredientMixin.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/mixin/recipe/ingredient/PacketEncoderMixin.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/mixin/recipe/ingredient/ShapelessRecipeMixin.java
  fabric-recipe-api-v1/src/main/resources/assets/fabric-recipe-api-v1/icon.png
  fabric-recipe-api-v1/src/main/resources/fabric-recipe-api-v1.accesswidener
  fabric-recipe-api-v1/src/main/resources/fabric-recipe-api-v1.mixins.json
  fabric-recipe-api-v1/src/main/resources/fabric.mod.json
  fabric-recipe-api-v1/src/testmod/java/net/fabricmc/fabric/test/recipe/ingredient/IngredientMatchTests.java
  fabric-recipe-api-v1/src/testmod/java/net/fabricmc/fabric/test/recipe/ingredient/SerializationTests.java
  fabric-recipe-api-v1/src/testmod/java/net/fabricmc/fabric/test/recipe/ingredient/ShapelessRecipeMatchTests.java
  fabric-recipe-api-v1/src/testmod/resources/data/fabric-recipe-api-v1-testmod/recipes/test_shapeless_match.json
  fabric-recipe-api-v1/src/testmod/resources/fabric.mod.json
  gradle.properties
  settings.gradle
Labels: enhancement, last call, merge me please, next?

#2667 Entity Selector Option API
  fabric-command-api-v2/src/main/java/net/fabricmc/fabric/api/command/v2/EntitySelectorOptionRegistry.java
  fabric-command-api-v2/src/main/java/net/fabricmc/fabric/api/command/v2/FabricEntitySelectorReader.java
  fabric-command-api-v2/src/main/java/net/fabricmc/fabric/mixin/command/EntitySelectorOptionsAccessor.java
  fabric-command-api-v2/src/main/java/net/fabricmc/fabric/mixin/command/EntitySelectorReaderMixin.java
  fabric-command-api-v2/src/main/resources/fabric-command-api-v2.mixins.json
  fabric-command-api-v2/src/main/resources/fabric.mod.json
  fabric-command-api-v2/src/testmod/java/net/fabricmc/fabric/test/command/CommandTest.java
  fabric-command-api-v2/src/testmod/java/net/fabricmc/fabric/test/command/EntitySelectorGameTest.java
  fabric-command-api-v2/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call, merge me please, next?

#2824 Generate a test datapack from the datagen testmod output.
  fabric-data-generation-api-v1/build.gradle
  fabric-data-generation-api-v1/pack.mcmeta
Labels: merge me please, small change

#2825 Remove leftover `@ApiStatus.Internal` annotations and add annotation validation
  build.gradle
  fabric-client-tags-api-v1/src/client/java/net/fabricmc/fabric/impl/tag/client/ClientTagsLoader.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/FabricDataGenHelper.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/FabricTagBuilder.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/impl/gametest/FabricGameTestModInitializer.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/impl/item/RecipeRemainderHandler.java
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/impl/client/itemgroup/CreativeGuiExtensions.java
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/impl/client/itemgroup/FabricCreativeGuiComponents.java
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/impl/itemgroup/FabricItemGroupBuilderImpl.java
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/impl/itemgroup/ItemGroupEventsImpl.java
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/impl/itemgroup/ItemGroupHelper.java
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/impl/itemgroup/MinecraftItemGroups.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/package-info.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/packet/package-info.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/trackers/package-info.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/trackers/vanilla/BlockInitTracker.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/trackers/vanilla/BlockItemTracker.java
  fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/impl/resource/conditions/ResourceConditionsImpl.java
  gradle/validate-annotations.gradle
Labels: enhancement, merge me please

#2823 Fix #2552: Add way to use resource conditions for block loot table datagen
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/loot/FabricBlockLootTableGenerator.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricLootTableProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/loot/ConditionBlockLootTableGenerator.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/mixin/datagen/loot/BlockLootTableGeneratorMixin.java
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.mixins.json
  fabric-data-generation-api-v1/src/main/resources/fabric.mod.json
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
Labels: enhancement, last call, merge me please

#2585 [1.19.2] Implement custom SignTypes
  fabric-object-builder-api-v1/src/client/java/net/fabricmc/fabric/mixin/object/builder/client/EntityModelLayersMixin.java
  fabric-object-builder-api-v1/src/client/java/net/fabricmc/fabric/mixin/object/builder/client/TexturedRenderLayersMixin.java
  fabric-object-builder-api-v1/src/client/resources/fabric-object-builder-v1.client.mixins.json
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/sign/SignTypeRegistry.java
  fabric-object-builder-api-v1/src/main/resources/fabric-object-builder-api-v1.accesswidener
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/TealSignTest.java
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/client/TealSignClientTest.java
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/mixin/BlockEntityRendererFactoriesAccessor.java
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/blockstates/teal_sign.json
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/blockstates/teal_wall_sign.json
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/lang/en_us.json
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/models/block/teal_sign.json
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/models/item/teal_sign.json
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/textures/entity/signs/teal.png
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/textures/item/teal_sign.png
  fabric-object-builder-api-v1/src/testmod/resources/fabric-object-builder-api-v1-testmod.mixins.json
  fabric-object-builder-api-v1/src/testmod/resources/fabric.mod.json
  fabric-rendering-v1/build.gradle
Labels: enhancement, last call, merge me please, next?

#2832 [1.19.3] Implement custom SignTypes
  fabric-object-builder-api-v1/src/client/java/net/fabricmc/fabric/mixin/object/builder/client/EntityModelLayersMixin.java
  fabric-object-builder-api-v1/src/client/java/net/fabricmc/fabric/mixin/object/builder/client/HangingSignEditScreenMixin.java
  fabric-object-builder-api-v1/src/client/java/net/fabricmc/fabric/mixin/object/builder/client/TexturedRenderLayersMixin.java
  fabric-object-builder-api-v1/src/client/resources/fabric-object-builder-v1.client.mixins.json
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/sign/SignTypeRegistry.java
  fabric-object-builder-api-v1/src/main/resources/fabric-object-builder-api-v1.accesswidener
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/TealSignTest.java
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/client/TealSignClientTest.java
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/mixin/BlockEntityRendererFactoriesAccessor.java
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/blockstates/teal_hanging_sign.json
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/blockstates/teal_sign.json
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/blockstates/teal_wall_hanging_sign.json
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/blockstates/teal_wall_sign.json
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/lang/en_us.json
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/models/block/teal_sign.json
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/models/item/teal_hanging_sign.json
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/models/item/teal_sign.json
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/textures/entity/signs/hanging/teal.png
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/textures/entity/signs/teal.png
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/textures/gui/hanging_signs/teal.png
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/textures/item/teal_hanging_sign.png
  fabric-object-builder-api-v1/src/testmod/resources/assets/fabric-object-builder-api-v1-testmod/textures/item/teal_sign.png
  fabric-object-builder-api-v1/src/testmod/resources/fabric-object-builder-api-v1-testmod.mixins.json
  fabric-object-builder-api-v1/src/testmod/resources/fabric.mod.json
  fabric-rendering-v1/build.gradle
Labels: enhancement, last call, merge me please

#2826 Fix ItemStack.EMPTY.getItem() rarely returning null due to threading
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ItemStackMixin.java
Labels: bug

#2848 Fix memory leak by using weak set for ArrayBackedEvent list
  fabric-api-base/src/main/java/net/fabricmc/fabric/impl/base/event/EventFactoryImpl.java
Labels: bug, merge me please, small change, priority:high

#2874 Fix Dragon Breath leaves empty Glass Bottle in Brewing Stand when used
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/BrewingStandBlockEntityMixin.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/BrewingStandGameTest.java
Labels: bug, priority:high
