Repository FabricMC/fabric, pull requests merged in 2024-01, with the labels that each got.

#3508 Fix race condition when handling unknown packets.
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/mixin/networking/client/ClientCommonNetworkHandlerMixin.java
  fabric-networking-api-v1/src/testmod/java/net/fabricmc/fabric/test/networking/play/NetworkingPlayPacketTest.java
Labels: bug, fabric-networking, merge me please, priority:high

#3517 Fix jukebox state getting changed mid-transaction
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/mixin/transfer/JukeboxBlockEntityMixin.java
  fabric-transfer-api-v1/src/main/resources/fabric-transfer-api-v1.mixins.json
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/gametests/VanillaStorageTests.java
Labels: bug, merge me please

#3510 Check for the correct BE type in the lookup API
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/impl/lookup/block/BlockApiLookupImpl.java
Labels: bug, merge me please, priority:high

#3509 Add a system property for a custom output directory for gametest structures
  fabric-gametest-api-v1/build.gradle
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/TestCommandMixin.java
  fabric-gametest-api-v1/src/main/resources/fabric-gametest-api-v1.mixins.json
Labels: enhancement, merge me please, small change

#3495 Fix local login query response handler not working
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerLoginNetworkAddon.java
  fabric-networking-api-v1/src/testmod/java/net/fabricmc/fabric/test/networking/login/NetworkingLoginQueryTest.java
  fabric-networking-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/networking/client/login/NetworkingLoginQueryClientTest.java
Labels: bug, fabric-networking, merge me please, priority:high

#3487 feat: add fabric-api-bom and fabric-api-catalog
  build.gradle
  fabric-api-bom/build.gradle
  fabric-api-catalog/build.gradle
  gradle/module-validation.gradle
  settings.gradle
Labels: enhancement, last call, merge me please, small change

#3511 Add mob conversion event
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/ServerLivingEntityEvents.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/MobEntityMixin.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/PigEntityMixin.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/TadpoleEntityMixin.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/VillagerEntityMixin.java
  fabric-entity-events-v1/src/main/resources/fabric-entity-events-v1.mixins.json
  fabric-entity-events-v1/src/testmod/java/net/fabricmc/fabric/test/entity/event/EntityEventTests.java
Labels: enhancement, last call, merge me please

#3520 [1.20.4] Stack aware `getFoodComponent`
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/FabricItem.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/FabricItemStack.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/BlockItemMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/CatEntityMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/CookingRecipeJsonBuilderMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/FoxEntityMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/HungerManagerMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ItemMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ItemStackMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/LivingEntityMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/WolfEntityMixin.java
  fabric-item-api-v1/src/main/resources/fabric-item-api-v1.mixins.json
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/FoodGameInitializer.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/FoodGameTest.java
  fabric-item-api-v1/src/testmod/resources/assets/fabric-item-api-v1-testmod/models/item/damage_food.json
  fabric-item-api-v1/src/testmod/resources/assets/fabric-item-api-v1-testmod/models/item/name_food.json
  fabric-item-api-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call, merge me please

#3528 Don't tick gametests if the server isn't ticking
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/MinecraftServerMixin.java
Labels: bug, merge me please, small change

#3531 Fix login network addons not properly initialized
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientLoginNetworkAddon.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/mixin/networking/client/ClientLoginNetworkHandlerMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerLoginNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/ServerLoginNetworkHandlerMixin.java
Labels: bug, fabric-networking, priority:high

#3476 Data Attachment API
  fabric-data-attachment-api-v1/build.gradle
  fabric-data-attachment-api-v1/src/client/java/net/fabricmc/fabric/mixin/attachment/client/ClientPlayNetworkHandlerMixin.java
  fabric-data-attachment-api-v1/src/client/resources/fabric-data-attachment-api-v1.client.mixins.json
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/api/attachment/v1/AttachmentRegistry.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/api/attachment/v1/AttachmentTarget.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/api/attachment/v1/AttachmentType.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/AttachmentEntrypoint.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/AttachmentPersistentState.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/AttachmentRegistryImpl.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/AttachmentSerializingImpl.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/AttachmentTargetImpl.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/AttachmentTypeImpl.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/AttachmentTargetsMixin.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/BlockEntityMixin.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/BlockEntityUpdateS2CPacketMixin.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/ChunkSerializerMixin.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/EntityMixin.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/ServerWorldMixin.java
  fabric-data-attachment-api-v1/src/main/resources/assets/fabric-data-attachment-api-v1/icon.png
  fabric-data-attachment-api-v1/src/main/resources/fabric-data-attachment-api-v1.mixins.json
  fabric-data-attachment-api-v1/src/main/resources/fabric.mod.json
  fabric-data-attachment-api-v1/src/test/java/net/fabricmc/fabric/test/attachment/CommonAttachmentTests.java
  fabric-data-attachment-api-v1/src/testmod/java/net/fabricmc/fabric/test/attachment/AttachmentTestMod.java
  fabric-data-attachment-api-v1/src/testmod/java/net/fabricmc/fabric/test/attachment/gametest/AttachmentCopyTests.java
  fabric-data-attachment-api-v1/src/testmod/java/net/fabricmc/fabric/test/attachment/gametest/BlockEntityTests.java
  fabric-data-attachment-api-v1/src/testmod/java/net/fabricmc/fabric/test/attachment/mixin/BlockEntityTypeAccessor.java
  fabric-data-attachment-api-v1/src/testmod/resources/fabric-data-attachment-api-v1-testmod.mixins.json
  fabric-data-attachment-api-v1/src/testmod/resources/fabric.mod.json
  gradle.properties
  settings.gradle
Labels: enhancement, last call, merge me please, new module

#3544 Send `c:register` packet for play phase instead of config
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/CommonPacketsImpl.java
  fabric-networking-api-v1/src/testmod/java/net/fabricmc/fabric/test/networking/play/NetworkingPlayPacketTest.java
  fabric-networking-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/networking/client/play/NetworkingPlayPacketClientTest.java
Labels: bug, fabric-networking, merge me please, priority:high

#3550 Fix some registries being unsynced
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/FabricRegistryInit.java
Labels: bug, registry-sync, merge me please, small change, priority:high

#3522 Allow `FabricCodecDataProvider` to access dynamic registries
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricCodecDataProvider.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
Labels: enhancement, last call, merge me please, small change

#3555 Fix porting issues in Dynamic Registries API
  fabric-lifecycle-events-v1/src/client/java/net/fabricmc/fabric/mixin/event/lifecycle/client/ClientPlayNetworkHandlerMixin.java
  fabric-registry-sync-v0/src/client/java/net/fabricmc/fabric/mixin/registry/sync/client/ClientRegistriesDynamicRegistriesMixin.java
  fabric-registry-sync-v0/src/client/resources/fabric-registry-sync-v0.client.mixins.json
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/api/event/registry/DynamicRegistries.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/DynamicRegistriesImpl.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/RegistryLoaderMixin.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SerializableRegistriesMixin.java
  fabric-registry-sync-v0/src/main/resources/fabric-registry-sync-v0.accesswidener
  fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/CustomDynamicRegistryTest.java
  fabric-registry-sync-v0/src/testmod/resources/data/fabric-registry-sync-v0-testmod/tags/fabric/test_dynamic_synced_empty/empty.json
  fabric-registry-sync-v0/src/testmodClient/java/net/fabricmc/fabric/test/registry/sync/client/DynamicRegistryClientTest.java
Labels: bug, registry-sync, merge me please, priority:high

#3535 Make chunk sections only convert vanilla air blocks to AIR
  fabric-block-api-v1/src/main/java/net/fabricmc/fabric/mixin/block/ChunkSectionBlockStateCounterMixin.java
  fabric-block-api-v1/src/main/java/net/fabricmc/fabric/mixin/block/ChunkSectionMixin.java
  fabric-block-api-v1/src/main/resources/fabric-block-api-v1.mixins.json
Labels: enhancement, last call

#3557 Fix duplicate resource pack names
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModNioResourcePack.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackCreator.java
Labels: bug, merge me please, small change, priority:high
