Repository FabricMC/fabric, pull requests merged in 2024-06, with the labels that each got.

#3807 Tag cleanup and additions for 1.21
  deprecated/fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/impl/tag/convention/ConventionLogWarnings.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BiomeTagGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BlockTagGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/concrete.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/glazed_terracotta.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/shulker_boxes.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/concrete.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/concrete_powder.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/glazed_terracotta.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/leathers.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/music_discs.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/bow.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/bows.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/brush.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/crossbow.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/fishing_rod.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/melee_weapon.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/mining_tool.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/ranged_weapon.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/shear.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/shears.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/shield.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/shields.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/spear.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/spears.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/is_sparse_vegetation/overworld.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalBlockTags.java
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
Labels: last call, merge me please

#3820 Use identifier path composition methods
  fabric-object-builder-api-v1/src/client/java/net/fabricmc/fabric/mixin/object/builder/client/EntityModelLayersMixin.java
  fabric-object-builder-api-v1/src/client/java/net/fabricmc/fabric/mixin/object/builder/client/HangingSignEditScreenMixin.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/FabricShaderProgram.java
Labels: merge me please, small change

#3841 Rename FabricBlockLootTableProvider.registryLookup to stop hiding the protected vanilla field.
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricBlockLootTableProvider.java
Labels: bug, merge me please, small change

#3839 Add Mangrove Swamp and Bamboo Jungle to Dense Overworld Vegetation tag
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BiomeTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/is_dense_vegetation/overworld.json
Labels: merge me please, small change

#3814 Add API to control creative inventory screen
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/api/client/itemgroup/v1/FabricCreativeInventoryScreen.java
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/impl/client/itemgroup/CreativeGuiExtensions.java
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/impl/client/itemgroup/FabricCreativeGuiComponents.java
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/mixin/itemgroup/client/CreativeInventoryScreenMixin.java
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/impl/itemgroup/FabricItemGroupImpl.java
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/mixin/itemgroup/ItemGroupMixin.java
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/mixin/itemgroup/ItemGroupsMixin.java
  fabric-item-group-api-v1/src/main/resources/fabric.mod.json
Labels: enhancement, last call, merge me please

#3832 Configuration networking fixes
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/api/client/networking/v1/ClientConfigurationConnectionEvents.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientNetworkingImpl.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/mixin/networking/client/ClientCommonNetworkHandlerMixin.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/mixin/networking/client/ClientConfigurationNetworkHandlerMixin.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/mixin/networking/client/ClientLoginNetworkHandlerMixin.java
  fabric-networking-api-v1/src/testmod/java/net/fabricmc/fabric/test/networking/configuration/NetworkingConfigurationTest.java
  fabric-networking-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/networking/client/configuration/NetworkingConfigurationClientTest.java
Labels: bug, fabric-networking, merge me please

#3844 Fix incorrect tag warnings, and add fail option.
  build.gradle
  deprecated/fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/impl/tag/convention/ConventionLogWarnings.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/impl/tag/convention/v2/TranslationConventionLogWarnings.java
  fabric-resource-conditions-api-v1/src/testmod/resources/assets/fabric-resource-conditions-api-v1-testmod/lang/en_us.json
Labels: bug, small change, priority:high

#3858 Remove unnecessary local capture
  fabric-lifecycle-events-v1/src/client/java/net/fabricmc/fabric/mixin/event/lifecycle/client/WorldChunkMixin.java
Labels: merge me please, small change

#3854 Fix #3853
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/ItemRenderContext.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/mixin/client/indigo/renderer/ItemRendererAccessor.java
  fabric-renderer-indigo/src/client/resources/fabric-renderer-indigo.mixins.json
Labels: bug, indigo, merge me please, priority:high

#3850 Add MinecraftClient/Server instances to networking contexts
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/api/client/networking/v1/ClientConfigurationNetworking.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/api/client/networking/v1/ClientPlayNetworking.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerConfigurationNetworking.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerPlayNetworking.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerConfigurationNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerPlayNetworkAddon.java
  fabric-networking-api-v1/src/test/java/net/fabricmc/fabric/test/networking/unit/CommonPacketTests.java
  fabric-registry-sync-v0/src/client/java/net/fabricmc/fabric/impl/client/registry/sync/FabricRegistryClientInit.java
Labels: enhancement, last call, fabric-networking, merge me please, small change

#3848 Fix new tags not being plural
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BlockTagGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/concretes.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/glazed_terracottas.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/concrete_powders.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/concretes.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/glazed_terracottas.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalBlockTags.java
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
Labels: bug, merge me please, priority:high

#3865 Fix BlockEntity Load/Unload events
  fabric-lifecycle-events-v1/src/client/java/net/fabricmc/fabric/mixin/event/lifecycle/client/WorldChunkMixin.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/server/WorldChunkMixin.java
Labels: bug, merge me please, priority:high

#3886 Fix CoreShaderRegistrationCallback mixin
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/shader/GameRendererMixin.java
Labels: bug, merge me please, priority:high

#3884 Fix ComponentsIngredient's getMatchingStacks() not applying the component changes.
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/builtin/ComponentsIngredient.java
Labels: bug, merge me please, priority:high

#3881 Fix legacy tag warning text to be accurate
  deprecated/fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/impl/tag/convention/ConventionLogWarnings.java
Labels: merge me please, small change

#3880 doc: typo: Storage<Storage> -> Storage<Variant>
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/base/SidedStorageBlockEntity.java
Labels: merge me please, small change

#3875 Renderer API quads overloads for joml interfaces
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/mesh/MutableQuadView.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/mesh/QuadEmitter.java
Labels: enhancement, merge me please, small change
