Repository FabricMC/fabric, pull requests merged in 2024-02, with the labels that each got.

#3565 Improve 24w05a port
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/AttachmentSerializingImpl.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricAdvancementProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricBlockLootTableProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricCodecDataProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/SimpleFabricLootTableProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/loot/FabricLootTableProviderImpl.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
Labels: bug, merge me please, port

#3563 Fix WorldRenderEvents.AFTER_TRANSLUCENT
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/WorldRenderContext.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/WorldRenderContextImpl.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/WorldRendererMixin.java
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/WorldRenderEventsTests.java
Labels: bug, merge me please, priority:high

#3571 [1.20.1] Backport Gradle and Loader updates
  .github/workflows/build.yml
  .github/workflows/release.yml
  build.gradle
  deprecated/fabric-command-api-v1/build.gradle
  deprecated/fabric-commands-v0/build.gradle
  deprecated/fabric-containers-v0/build.gradle
  deprecated/fabric-events-lifecycle-v0/build.gradle
  deprecated/fabric-keybindings-v0/build.gradle
  deprecated/fabric-loot-tables-v1/build.gradle
  deprecated/fabric-models-v0/build.gradle
  deprecated/fabric-networking-v0/build.gradle
  deprecated/fabric-renderer-registries-v1/build.gradle
  deprecated/fabric-rendering-data-attachment-v1/build.gradle
  deprecated/fabric-rendering-v0/build.gradle
  fabric-api-base/build.gradle
  fabric-api-lookup-api-v1/build.gradle
  fabric-biome-api-v1/build.gradle
  fabric-block-api-v1/build.gradle
  fabric-block-view-api-v2/build.gradle
  fabric-blockrenderlayer-v1/build.gradle
  fabric-client-tags-api-v1/build.gradle
  fabric-command-api-v2/build.gradle
  fabric-content-registries-v0/build.gradle
  fabric-convention-tags-v1/build.gradle
  fabric-crash-report-info-v1/build.gradle
  fabric-data-generation-api-v1/build.gradle
  fabric-dimensions-v1/build.gradle
  fabric-entity-events-v1/build.gradle
  fabric-events-interaction-v0/build.gradle
  fabric-game-rule-api-v1/build.gradle
  fabric-gametest-api-v1/build.gradle
  fabric-item-api-v1/build.gradle
  fabric-item-group-api-v1/build.gradle
  fabric-key-binding-api-v1/build.gradle
  fabric-lifecycle-events-v1/build.gradle
  fabric-loot-api-v2/build.gradle
  fabric-message-api-v1/build.gradle
  fabric-mining-level-api-v1/build.gradle
  fabric-model-loading-api-v1/build.gradle
  fabric-networking-api-v1/build.gradle
  fabric-object-builder-api-v1/build.gradle
  fabric-particles-v1/build.gradle
  fabric-recipe-api-v1/build.gradle
  fabric-registry-sync-v0/build.gradle
  fabric-renderer-api-v1/build.gradle
  fabric-renderer-indigo/build.gradle
  fabric-rendering-fluids-v1/build.gradle
  fabric-rendering-v1/build.gradle
  fabric-resource-conditions-api-v1/build.gradle
  fabric-resource-loader-v0/build.gradle
  fabric-screen-api-v1/build.gradle
  fabric-screen-handler-api-v1/build.gradle
  fabric-sound-api-v1/build.gradle
  fabric-transfer-api-v1/build.gradle
  fabric-transitive-access-wideners-v1/build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  src/main/resources/fabric.mod.json
Labels: merge me please, backport

#3558 Expose a function for querying the non-default fluid renderer
  fabric-rendering-fluids-v1/src/client/java/net/fabricmc/fabric/api/client/render/fluid/v1/FluidRenderHandlerRegistry.java
  fabric-rendering-fluids-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/fluid/FluidRenderHandlerRegistryImpl.java
  fabric-rendering-fluids-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/fluid/FluidRendererMixin.java
Labels: enhancement, last call, merge me please, small change

#3548 Extend Data Attachment API to ProtoChunk
  fabric-data-attachment-api-v1/build.gradle
  fabric-data-attachment-api-v1/src/client/java/net/fabricmc/fabric/mixin/attachment/client/ClientPlayNetworkHandlerMixin.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/api/attachment/v1/AttachmentTarget.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/api/attachment/v1/AttachmentType.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/AttachmentEntrypoint.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/AttachmentTargetImpl.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/AttachmentTargetsMixin.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/ChunkSerializerMixin.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/WorldChunkMixin.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/WrapperProtoChunkMixin.java
  fabric-data-attachment-api-v1/src/main/resources/fabric-data-attachment-api-v1.mixins.json
  fabric-data-attachment-api-v1/src/main/resources/fabric.mod.json
  fabric-data-attachment-api-v1/src/test/java/net/fabricmc/fabric/test/attachment/CommonAttachmentTests.java
  fabric-data-attachment-api-v1/src/testmod/java/net/fabricmc/fabric/test/attachment/AttachmentTestMod.java
  fabric-data-attachment-api-v1/src/testmod/java/net/fabricmc/fabric/test/attachment/SetAttachmentFeature.java
  fabric-data-attachment-api-v1/src/testmod/resources/data/fabric-data-attachment-api-v1-testmod/worldgen/placed_feature/set_attachment.json
  fabric-data-attachment-api-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call, merge me please

#3533 1.20.4 - Server Lifecycle Events - Save Events
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/api/event/lifecycle/v1/ServerLifecycleEvents.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/MinecraftServerMixin.java
  fabric-lifecycle-events-v1/src/testmod/java/net/fabricmc/fabric/test/event/lifecycle/ServerLifecycleTests.java
Labels: enhancement, last call, merge me please

#3503 Add Support for Custom ColorResolvers
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/ColorResolverRegistry.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/ColorResolverRegistryImpl.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/ClientWorldMixin.java
  fabric-rendering-v1/src/client/resources/fabric-rendering-v1.mixins.json
  fabric-rendering-v1/src/testmod/java/net/fabricmc/fabric/test/rendering/CustomColorResolverTestInit.java
  fabric-rendering-v1/src/testmod/resources/fabric.mod.json
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/CustomColorResolverTest.java
  fabric-rendering-v1/src/testmodClient/resources/assets/fabric-rendering-v1-testmod/blockstates/custom_color_block.json
  fabric-rendering-v1/src/testmodClient/resources/assets/fabric-rendering-v1-testmod/models/block/custom_color_block.json
  fabric-rendering-v1/src/testmodClient/resources/assets/fabric-rendering-v1-testmod/textures/block/blank.png
Labels: enhancement, last call, merge me please

#3578 24w06a porting fixes
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/elytra/PlayerEntityMixin.java
  fabric-events-interaction-v0/src/client/java/net/fabricmc/fabric/mixin/event/interaction/client/MinecraftClientMixin.java
  fabric-lifecycle-events-v1/src/client/java/net/fabricmc/fabric/mixin/event/lifecycle/client/ClientPlayNetworkHandlerMixin.java
  fabric-lifecycle-events-v1/src/client/java/net/fabricmc/fabric/mixin/event/lifecycle/client/ClientTagLoaderMixin.java
  fabric-lifecycle-events-v1/src/client/resources/fabric-lifecycle-events-v1.client.mixins.json
  fabric-lifecycle-events-v1/src/testmodClient/java/net/fabricmc/fabric/test/event/lifecycle/client/ClientTickTests.java
  fabric-message-api-v1/src/testmod/java/net/fabricmc/fabric/test/message/ChatTest.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/api/event/registry/FabricRegistryBuilder.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SimpleRegistryMixin.java
  fabric-resource-loader-v0/src/client/java/net/fabricmc/fabric/mixin/resource/loader/client/GameOptionsMixin.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModNioResourcePack.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackCreator.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackFactory.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackUtil.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/PlaceholderResourcePack.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ResourceManagerHelperImpl.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/DatapackCommandMixin.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/MinecraftServerMixin.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/ResourcePackManagerMixin.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/ResourcePackProfileMixin.java
  fabric-resource-loader-v0/src/test/java/net/fabricmc/fabric/test/resource/loader/unit/ModResourcePackUtilTests.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/context/ContainerItemContext.java
  gradle.properties
Labels: bug, port

#3583 Fix coverage task
  build.gradle
Labels: bug, merge me please, small change

#3588 Fix empty data attachments being saved.
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/AttachmentSerializingImpl.java
  fabric-data-attachment-api-v1/src/test/java/net/fabricmc/fabric/test/attachment/CommonAttachmentTests.java
Labels: bug, priority:high

#3593 Fluid rendering fixes
  fabric-rendering-fluids-v1/src/client/java/net/fabricmc/fabric/api/client/render/fluid/v1/FluidRenderHandler.java
  fabric-rendering-fluids-v1/src/client/java/net/fabricmc/fabric/api/client/render/fluid/v1/FluidRendering.java
  fabric-rendering-fluids-v1/src/client/java/net/fabricmc/fabric/api/client/render/fluid/v1/SimpleFluidRenderHandler.java
  fabric-rendering-fluids-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/fluid/FluidRenderHandlerInfo.java
  fabric-rendering-fluids-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/fluid/FluidRenderHandlerRegistryImpl.java
  fabric-rendering-fluids-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/fluid/FluidRenderingImpl.java
  fabric-rendering-fluids-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/fluid/FluidRendererMixin.java
  fabric-rendering-fluids-v1/src/testmodClient/java/net/fabricmc/fabric/test/client/rendering/fluid/CustomizedFluidRenderer.java
Labels: bug, merge me please, priority:medium

#3600 Improve handling of empty item groups in the creative menu
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/mixin/itemgroup/client/CreativeInventoryScreenMixin.java
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/mixin/itemgroup/ItemGroupsMixin.java
  fabric-item-group-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/group/ItemGroupTest.java
Labels: bug, merge me please, small change

#3594 [1.20.5] Misc networking cleanup
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientCommonNetworkAddon.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientPlayNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/AbstractChanneledNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/GlobalReceiverRegistry.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerConfigurationNetworkAddon.java
Labels: fabric-networking, merge me please, cleanup

#3599 Fix teal sign crash by registering the wood type.
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/TealSignTest.java
Labels: bug, merge me please, test, small change

#3598 [1.20.5] Fix registry sync
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/packet/DirectRegistryPacketHandler.java
  fabric-registry-sync-v0/src/test/java/net/fabricmc/fabric/test/registry/sync/DirectRegistryPacketHandlerTest.java
Labels: bug, registry-sync, merge me please, priority:high

#3603 Fix ClientPlayNetworking.Contexnt.player() being null
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientPlayNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerConfigurationNetworkAddon.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerPlayNetworkAddon.java
  fabric-networking-api-v1/src/testmod/java/net/fabricmc/fabric/test/networking/play/NetworkingPlayPacketTest.java
  fabric-networking-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/networking/client/play/NetworkingPlayPacketClientTest.java
Labels: bug, fabric-networking, merge me please, priority:high

#3612 Fire the `MOB_CONVERSION` event after shearing the mushroom cow
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/MooshroomEntityMixin.java
  fabric-entity-events-v1/src/main/resources/fabric-entity-events-v1.mixins.json
Labels: bug, merge me please, small change

#3613 Remove now unneeded OverlayVertexConsumerMixin
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/OverlayVertexConsumerMixin.java
  fabric-renderer-api-v1/src/client/resources/fabric-renderer-api-v1.mixins.json
Labels: merge me please, port, cleanup
