Repository FabricMC/fabric, pull requests merged in 2024-08, with the labels that each got.

#3872 [1.21] Resource Conditions in Pack Overlays
  fabric-resource-conditions-api-v1/build.gradle
  fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/api/resource/conditions/v1/ResourceConditions.java
  fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/impl/resource/conditions/OverlayConditionsMetadata.java
  fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/mixin/resource/conditions/ResourcePackProfileMixin.java
  fabric-resource-conditions-api-v1/src/main/resources/fabric-resource-conditions-api-v1.mixins.json
  fabric-resource-conditions-api-v1/src/testmod/java/net/fabricmc/fabric/test/resource/conditions/ConditionalResourcesTest.java
  fabric-resource-conditions-api-v1/src/testmod/resources/do_overlay/data/fabric-resource-conditions-api-v1-testmod/predicate/do_overlay.json
  fabric-resource-conditions-api-v1/src/testmod/resources/dont_overlay/data/fabric-resource-conditions-api-v1-testmod/predicate/dont_overlay.json
  fabric-resource-conditions-api-v1/src/testmod/resources/pack.mcmeta
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ResourceManagerHelperImpl.java
Labels: enhancement, last call, merge me please

#3887 Replace redirect in lifecycle events with wrap operation
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/MinecraftServerMixin.java
Labels: merge me please, small change

#3937 Add `ShadeMode` to FRAPI
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/material/BlendMode.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/material/MaterialFinder.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/material/MaterialView.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/material/ShadeMode.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/model/FabricBakedModel.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/model/ModelHelper.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/impl/renderer/VanillaModelEncoder.java
  fabric-renderer-api-v1/src/client/resources/fabric-renderer-api-v1.mixins.json
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/OctagonalColumnBlock.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/Registration.java
  fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/ModelResolverImpl.java
  fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/OctagonalColumnUnbakedModel.java
  fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/RiverstoneUnbakedModel.java
  fabric-renderer-api-v1/src/testmodClient/resources/assets/fabric-renderer-api-v1-testmod/blockstates/octagonal_column.json
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/IndigoRenderer.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/aocalc/AoCalculator.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/material/MaterialFinderImpl.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/material/MaterialViewImpl.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/mesh/EncodingFormat.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/AbstractBlockRenderContext.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/ChunkRenderInfo.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/TerrainRenderContext.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/mixin/client/indigo/renderer/BakedModelMixin.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/mixin/client/indigo/renderer/SectionBuilderMixin.java
  fabric-renderer-indigo/src/client/resources/fabric-renderer-indigo.accesswidener
  fabric-renderer-indigo/src/client/resources/fabric-renderer-indigo.mixins.json
Labels: enhancement, last call, indigo, merge me please

#3957 Add `c:slime_balls` tag, add more melee weapons to melee tag, add `c:fertilizers` tag, fix entries for some biome and food tags
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BiomeTagGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/fertilizers.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/fruit.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/fruits.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/golden.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/vegetable.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/vegetables.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/slime_balls.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/melee_weapon.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/is_cold/overworld.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/is_sparse_vegetation/overworld.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
Labels: enhancement, last call, merge me please

#3981 Add more TAWs for custom RenderLayers
  fabric-transitive-access-wideners-v1/build.gradle
  fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener
  fabric-transitive-access-wideners-v1/template.accesswidener
Labels: enhancement, last call, merge me please, small change

#3991 Actually throw the exception when a duplicate registry entry is found.
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SimpleRegistryMixin.java
Labels: bug, registry-sync, merge me please, small change, priority:high

#3992 Prevent vanilla clients from joining servers that require modded registry entries.
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerConfigurationNetworkAddon.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/RegistrySyncManager.java
Labels: enhancement, registry-sync, fabric-networking, merge me please

#3994 Allow duplicate entries after being frozen on the client in prod.
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SimpleRegistryAccessor.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SimpleRegistryMixin.java
  fabric-registry-sync-v0/src/main/resources/fabric-registry-sync-v0.mixins.json
Labels: registry-sync, priority:high

#3999 Revert registry sync changes. Allowing duplicate entries and vanilla clients on servers with modded registries.
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerConfigurationNetworkAddon.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/RegistrySyncManager.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SimpleRegistryMixin.java
Labels: bug, registry-sync, fabric-networking, priority:high

#4009 Add an API to add additional supported blocks to block entity types.
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/entity/FabricBlockEntityType.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/BlockEntityTypeMixin.java
  fabric-object-builder-api-v1/src/main/resources/fabric-object-builder-v1.mixins.json
  fabric-object-builder-api-v1/src/main/resources/fabric.mod.json
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/TealSignTest.java
  fabric-object-builder-api-v1/src/testmod/resources/fabric.mod.json
  fabric-object-builder-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/object/builder/client/TealSignClientTest.java
  fabric-object-builder-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/object/builder/client/mixin/BlockEntityRendererFactoriesAccessor.java
  fabric-object-builder-api-v1/src/testmodClient/resources/fabric-object-builder-api-v1-testmod.client.mixins.json
Labels: enhancement, last call, priority:high

#4021 Add chorus fruit to `c:foods/fruit` tag
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/fruit.json
Labels: merge me please, small change

#4019 Update grgit
  build.gradle
  settings.gradle
Labels: merge me please

#4013 Crafter support for the transfer api.
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/mixin/transfer/CrafterBlockMixin.java
  fabric-transfer-api-v1/src/main/resources/fabric-transfer-api-v1.mixins.json
Labels: bug, merge me please, priority:low

#4010 Fix handled screen not calling super.mouseReleased or super.mouseDragged
  fabric-screen-api-v1/src/client/java/net/fabricmc/fabric/mixin/screen/HandledScreenMixin.java
  fabric-screen-api-v1/src/client/resources/fabric-screen-api-v1.mixins.json
  fabric-screen-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/screen/ScreenTests.java
Labels: bug, merge me please, priority:low

#4008 Add crop and nugget tags
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/crops.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/crops/beetroot.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/crops/cactus.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/crops/carrot.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/crops/cocoa_bean.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/crops/melon.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/crops/nether_wart.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/crops/potato.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/crops/pumpkin.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/crops/sugar_cane.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/crops/wheat.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/nuggets.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/nuggets/gold.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/nuggets/iron.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
Labels: enhancement, last call, merge me please, priority:low

#4043 Finish porting Model Loading, FRAPI, and Indigo to 24w33a
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/BlockStateResolver.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/DelegatingUnbakedModel.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/ModelLoadingPlugin.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/ModelModifier.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/ModelResolver.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/PreparableModelLoadingPlugin.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/impl/client/model/loading/ModelLoaderHooks.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/impl/client/model/loading/ModelLoadingEventDispatcher.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/impl/client/model/loading/ModelLoadingPluginContextImpl.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/impl/client/model/loading/ModelLoadingPluginManager.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/model/loading/BakedModelManagerMixin.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/model/loading/BlockStatesLoaderMixin.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/model/loading/ModelLoaderMixin.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/model/loading/class_10097Mixin.java
  fabric-model-loading-api-v1/src/client/resources/fabric-model-loading-api-v1.mixins.json
  fabric-model-loading-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/model/loading/BakedModelFeatureRenderer.java
  fabric-model-loading-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/model/loading/ModelTestModClient.java
  fabric-model-loading-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/model/loading/NestedModelLoadingTest.java
  fabric-model-loading-api-v1/src/testmodClient/resources/fabric.mod.json
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/mesh/MutableQuadView.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/mesh/QuadEmitter.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/mesh/QuadView.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/impl/renderer/VanillaModelEncoder.java
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/FrameBlock.java
  fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/FrameUnbakedModel.java
  fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/OctagonalColumnUnbakedModel.java
  fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/PillarUnbakedModel.java
  fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/RiverstoneUnbakedModel.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/IndigoRenderer.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/aocalc/AoCalculator.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/aocalc/VanillaAoHelper.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/mesh/MutableQuadViewImpl.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/BlockRenderInfo.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/ItemRenderContext.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/mixin/client/indigo/renderer/BlockModelRendererMixin.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/mixin/client/indigo/renderer/ItemRendererMixin.java
  settings.gradle
Labels: port, priority:high

#4026 [1.20.4] Remove incorrect assertion in setClientConfigurationAddon
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientNetworkingImpl.java
Labels: bug, fabric-networking, merge me please, priority:medium, backport

#4045 Fix operator item group event
  fabric-item-group-api-v1/src/main/java/net/fabricmc/fabric/mixin/itemgroup/ItemGroupMixin.java
Labels: bug, merge me please, small change

#4051 After Damage Event
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/ServerLivingEntityEvents.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/LivingEntityMixin.java
  fabric-entity-events-v1/src/testmod/java/net/fabricmc/fabric/test/entity/event/EntityEventTests.java
Labels: enhancement, merge me please, small change

#4054 24w34a porting fixes
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/VillagerInteractionRegistries.java
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/elytra/ElytraFlightControllerMixin.java
  fabric-entity-events-v1/src/main/resources/fabric-entity-events-v1.mixins.json
  fabric-entity-events-v1/src/testmod/java/net/fabricmc/fabric/test/entity/event/DiamondElytraItem.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/CustomDamageHandler.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/api/event/lifecycle/v1/ServerTickEvents.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/ModelModifier.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/EntityTrackingEvents.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/api/recipe/v1/ingredient/CustomIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/api/recipe/v1/ingredient/CustomIngredientSerializer.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/api/recipe/v1/ingredient/FabricIngredient.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidConstants.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidVariantAttributeHandler.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidVariantAttributes.java
Labels: bug, merge me please, port

#4056 Update Fabric Loader and re-enable server test
  build.gradle
  deprecated/fabric-command-api-v1/src/main/resources/fabric.mod.json
  deprecated/fabric-commands-v0/src/main/resources/fabric.mod.json
  deprecated/fabric-convention-tags-v1/src/main/resources/fabric.mod.json
  deprecated/fabric-keybindings-v0/src/client/resources/fabric.mod.json
  deprecated/fabric-loot-api-v2/src/main/resources/fabric.mod.json
  deprecated/fabric-rendering-data-attachment-v1/src/main/resources/fabric.mod.json
  deprecated/fabric-rendering-v0/src/client/resources/fabric.mod.json
  fabric-api-base/src/main/resources/fabric.mod.json
  fabric-api-lookup-api-v1/src/main/resources/fabric.mod.json
  fabric-biome-api-v1/src/main/resources/fabric.mod.json
  fabric-block-api-v1/src/main/resources/fabric.mod.json
  fabric-block-view-api-v2/src/main/resources/fabric.mod.json
  fabric-blockrenderlayer-v1/src/client/resources/fabric.mod.json
  fabric-client-tags-api-v1/src/client/resources/fabric.mod.json
  fabric-command-api-v2/src/main/resources/fabric.mod.json
  fabric-content-registries-v0/src/main/resources/fabric.mod.json
  fabric-convention-tags-v2/src/datagen/resources/fabric.mod.json
  fabric-convention-tags-v2/src/main/resources/fabric.mod.json
  fabric-crash-report-info-v1/src/main/resources/fabric.mod.json
  fabric-data-attachment-api-v1/src/main/resources/fabric.mod.json
  fabric-data-generation-api-v1/src/main/resources/fabric.mod.json
  fabric-dimensions-v1/src/main/resources/fabric.mod.json
  fabric-entity-events-v1/src/main/resources/fabric.mod.json
  fabric-events-interaction-v0/src/main/resources/fabric.mod.json
  fabric-game-rule-api-v1/src/main/resources/fabric.mod.json
  fabric-gametest-api-v1/src/main/resources/fabric.mod.json
  fabric-item-api-v1/src/main/resources/fabric.mod.json
  fabric-item-group-api-v1/src/main/resources/fabric.mod.json
  fabric-key-binding-api-v1/src/client/resources/fabric.mod.json
  fabric-lifecycle-events-v1/src/main/resources/fabric.mod.json
  fabric-loot-api-v3/src/main/resources/fabric.mod.json
  fabric-message-api-v1/src/main/resources/fabric.mod.json
  fabric-model-loading-api-v1/src/client/resources/fabric.mod.json
  fabric-networking-api-v1/src/main/resources/fabric.mod.json
  fabric-object-builder-api-v1/src/main/resources/fabric.mod.json
  fabric-particles-v1/src/main/resources/fabric.mod.json
  fabric-recipe-api-v1/src/main/resources/fabric.mod.json
  fabric-registry-sync-v0/src/main/resources/fabric.mod.json
  fabric-renderer-api-v1/src/client/resources/fabric.mod.json
  fabric-renderer-indigo/src/client/resources/fabric.mod.json
  fabric-rendering-fluids-v1/src/main/resources/fabric.mod.json
  fabric-rendering-v1/src/client/resources/fabric.mod.json
  fabric-resource-conditions-api-v1/src/main/resources/fabric.mod.json
  fabric-resource-loader-v0/src/main/resources/fabric.mod.json
  fabric-screen-api-v1/src/client/resources/fabric.mod.json
  fabric-screen-handler-api-v1/src/main/resources/fabric.mod.json
  fabric-sound-api-v1/src/client/resources/fabric.mod.json
  fabric-transfer-api-v1/src/main/resources/fabric.mod.json
  fabric-transitive-access-wideners-v1/src/main/resources/fabric.mod.json
  gradle.properties
  src/main/resources/fabric.mod.json
Labels: merge me please

#4057 Join a dedicated server in the automated client test.
  fabric-api-base/src/testmodClient/java/net/fabricmc/fabric/test/base/client/FabricApiAutoTestClient.java
  fabric-api-base/src/testmodClient/java/net/fabricmc/fabric/test/base/client/FabricClientTestHelper.java
  fabric-api-base/src/testmodClient/java/net/fabricmc/fabric/test/base/client/TestDedicatedServer.java
  fabric-api-base/src/testmodClient/java/net/fabricmc/fabric/test/base/client/mixin/MinecraftDedicatedServerMixin.java
  fabric-api-base/src/testmodClient/resources/fabric-api-base-testmod.client.mixins.json
Labels: merge me please, test
