Repository FabricMC/fabric, pull requests merged in 2024-07, with the labels that each got.

#3902 Added Badlands and Wooded badlands to hot tag
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BiomeTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/is_hot/overworld.json
Labels: merge me please, small change

#3909 Add common Mace tag
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/mace.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/melee_weapon.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
Labels: merge me please, small change

#3916 Cleanup usages of `Text`
  fabric-command-api-v2/src/client/java/net/fabricmc/fabric/mixin/command/client/ClientCommandSourceMixin.java
  fabric-game-rule-api-v1/src/client/java/net/fabricmc/fabric/impl/gamerule/widget/DoubleRuleWidget.java
  fabric-game-rule-api-v1/src/client/java/net/fabricmc/fabric/impl/gamerule/widget/EnumRuleWidget.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/RegistrySyncManager.java
Labels: enhancement, merge me please, small change

#3912 Several tag fixes and additions
  deprecated/fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/impl/tag/convention/ConventionLogWarnings.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BlockTagGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/glass_blocks.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/glass_blocks/cheap.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/glass_blocks/colorless.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/glass_blocks/tinted.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/glass_panes.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/glass_panes/colorless.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/ender_pearls.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/berry.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/bread.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/candy.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/cooked_fish.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/cooked_meat.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/cookie.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/fruit.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/golden.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/raw_fishe.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/raw_meat.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/soup.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/vegetable.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/glass_blocks.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/glass_blocks/cheap.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/glass_blocks/colorless.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/glass_blocks/tinted.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/glass_panes.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/glass_panes/colorless.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/igniter.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalBlockTags.java
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
Labels: enhancement, last call, merge me please, priority:medium

#3925 Add tests for convention tag keys matching field names
  fabric-convention-tags-v2/src/testmod/java/net/fabricmc/fabric/test/tag/convention/v2/TagUtilTest.java
Labels: merge me please, test

#3927 Add API to create reload listeners with a registry lookup.
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/api/resource/ResourceManagerHelper.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ResourceManagerHelperImpl.java
  fabric-resource-loader-v0/src/main/resources/fabric-resource-loader-v0.accesswidener
  fabric-resource-loader-v0/src/testmod/java/net/fabricmc/fabric/test/resource/loader/ResourceReloadListenerTestMod.java
Labels: enhancement, last call, merge me please

#3932 Fix some registry-related bugs
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationImpl.java
  fabric-biome-api-v1/src/main/resources/fabric-biome-api-v1.accesswidener
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/RegistryKeysMixin.java
  fabric-registry-sync-v0/src/main/resources/fabric-registry-sync-v0.mixins.json
Labels: bug, registry-sync, merge me please, priority:medium

#3940 Fix crash when using custom render layers in BLOCK_OUTLINE event
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/WorldRendererMixin.java
Labels: bug, merge me please, priority:high

#3970 Use `ConcurrentHashMap` inside `RegistryAttributeImpl`
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/RegistryAttributeImpl.java
Labels: registry-sync, merge me please, small change
