Repository FabricMC/fabric, pull requests merged in 2024-10, with the labels that each got.

#4136 Update mod to Minecraft snapshot 24w40a
  fabric-client-tags-api-v1/src/client/java/net/fabricmc/fabric/impl/tag/client/ClientTagsLoader.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BiomeTagGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EntityTypeTagGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/entity_type/boats.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/black.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/blue.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/brown.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/cyan.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/gray.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/green.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/light_blue.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/light_gray.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/lime.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/magenta.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/orange.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/pink.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/purple.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/red.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/white.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/dyed/yellow.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/is_dark_forest.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/is_dense_vegetation/overworld.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/is_temperate/overworld.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/is_tree/deciduous.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalBiomeTags.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricRecipeProvider.java
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
  fabric-dimensions-v1/src/testmod/java/net/fabricmc/fabric/test/dimension/VoidChunkGenerator.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/FabricItem.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/AbstractFurnaceBlockEntityMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/AnvilScreenHandlerMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/BrewingStandBlockEntityMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/CraftingRecipeMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/RecipeMixin.java
  fabric-item-api-v1/src/main/resources/fabric-item-api-v1.mixins.json
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/RecipeGameTest.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/PlayerManagerMixin.java
  fabric-loot-api-v3/src/testmod/java/net/fabricmc/fabric/test/loot/LootTest.java
  fabric-recipe-api-v1/src/testmod/java/net/fabricmc/fabric/test/recipe/ingredient/ShapelessRecipeMatchTests.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/FabricRegistryInit.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/WorldRendererMixin.java
  fabric-resource-conditions-api-v1/src/testmod/java/net/fabricmc/fabric/test/resource/conditions/ConditionalResourcesTest.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/mixin/transfer/AbstractFurnaceBlockEntityMixin.java
  gradle.properties
Labels: port, priority:high

#4157 Update mod to Minecraft 1.21.2 pre-release 3
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/AttachmentTargetsMixin.java
  fabric-data-attachment-api-v1/src/test/java/net/fabricmc/fabric/test/attachment/CommonAttachmentTests.java
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/api/recipe/v1/ingredient/CustomIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/api/recipe/v1/ingredient/FabricIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/CustomIngredientImpl.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/builtin/AllIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/builtin/AnyIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/builtin/ComponentsIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/builtin/CustomDataIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/builtin/DifferenceIngredient.java
  fabric-recipe-api-v1/src/main/resources/fabric-recipe-api-v1.accesswidener
  fabric-recipe-api-v1/src/testmod/java/net/fabricmc/fabric/test/recipe/ingredient/IngredientMatchTests.java
  fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener
  gradle.properties
Labels: merge me please

#4153 Add mixin audit unit test
  fabric-api-base/src/test/java/net/fabricmc/fabric/test/base/MixinAuditTest.java
Labels: merge me please, test, small change

#4152 Rename CustomIngredient.getMatchingStacks & add CustomIngredient.toDisplay
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/api/recipe/v1/ingredient/CustomIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/CustomIngredientImpl.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/builtin/CombinedIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/builtin/ComponentsIngredient.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/impl/recipe/ingredient/builtin/CustomDataIngredient.java
  fabric-recipe-api-v1/src/main/resources/fabric-recipe-api-v1.accesswidener
Labels: enhancement, priority:high

#4114 Add Pie Item Tag c:foods/pie
  deprecated/fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/impl/tag/convention/ConventionLogWarnings.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/foods/pie.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
Labels: enhancement, merge me please, small change

#4134 Add more `c` fluid tags
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/FluidTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/fluid/beetroot_soup.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/fluid/experience.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/fluid/gaseous.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/fluid/mushroom_stew.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/fluid/potion.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/fluid/rabbit_stew.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/fluid/suspicious_stew.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalFluidTags.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidConstants.java
Labels: last call, merge me please

#4155 Fix After Translucent World Render Event
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/WorldRendererMixin.java
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/WorldRenderEventsTests.java
Labels: bug, merge me please, port

#4165 Fix: Dont show warning for modded entity types without a datafixer
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/EntityTypeBuilderMixin.java
Labels: bug, merge me please, port, small change

#4146 Add Stripped Logs and Stripped Woods Tags
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BlockTagGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/stripped_logs.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/stripped_woods.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/stripped_logs.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/stripped_woods.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalBlockTags.java
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
Labels: last call, merge me please

#4083 Add support for Item-containing Items
  fabric-transfer-api-v1/build.gradle
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/item/ItemStorage.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/item/BundleContentsStorage.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/item/ContainerComponentStorage.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/mixin/transfer/BundleContentsComponentAccessor.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/mixin/transfer/ContainerComponentAccessor.java
  fabric-transfer-api-v1/src/main/resources/fabric-transfer-api-v1.mixins.json
  fabric-transfer-api-v1/src/test/java/net/fabricmc/fabric/test/transfer/unittests/ContainerItemTests.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/ingame/TransferTestInitializer.java
Labels: enhancement, last call, merge me please

#4172 Fix: Common groups missing operator
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/impl/client/itemgroup/FabricCreativeGuiComponents.java
Labels: bug, priority:medium

#4177 Fix title screen screenshot in automated client test
  fabric-api-base/src/testmodClient/java/net/fabricmc/fabric/test/base/client/FabricApiAutoTestClient.java
  fabric-api-base/src/testmodClient/java/net/fabricmc/fabric/test/base/client/FabricClientTestHelper.java
  fabric-api-base/src/testmodClient/java/net/fabricmc/fabric/test/base/client/mixin/TitleScreenAccessor.java
  fabric-api-base/src/testmodClient/resources/fabric-api-base-testmod.client.mixins.json
Labels: test, small change

#4171 Remove LevelProperties check
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/modification/MinecraftServerMixin.java
Labels: merge me please, small change

#4178 Optimize screenshot delays in automated client test
  fabric-api-base/src/testmodClient/java/net/fabricmc/fabric/test/base/client/FabricApiAutoTestClient.java
  fabric-api-base/src/testmodClient/java/net/fabricmc/fabric/test/base/client/FabricClientTestHelper.java
Labels: merge me please, test, small change

#4183 Add ServerChunkEvents.Generate
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/api/event/lifecycle/v1/ServerChunkEvents.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/ChunkGeneratingMixin.java
  fabric-lifecycle-events-v1/src/testmod/java/net/fabricmc/fabric/test/event/lifecycle/ServerChunkLifecycleTests.java
  fabric-lifecycle-events-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call, merge me please

#4184 Revert "Prevent vanilla clients from joining servers that require modded registry entries. (#4169)"
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerConfigurationNetworkAddon.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/RegistrySyncManager.java
Labels: bug, merge me please, priority:high

#4187 Fix overriding vanilla translations
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/server/LanguageMixin.java
  fabric-resource-loader-v0/src/testmod/java/net/fabricmc/fabric/test/resource/loader/LanguageTestMod.java
  fabric-resource-loader-v0/src/testmod/resources/assets/minecraft/lang/en_us.json
Labels: bug, merge me please, small change, priority:high

#4188 Update Loom and Loader
  build.gradle
  deprecated/fabric-command-api-v1/src/main/resources/fabric.mod.json
  deprecated/fabric-commands-v0/src/main/resources/fabric.mod.json
  deprecated/fabric-convention-tags-v1/src/main/resources/fabric.mod.json
  deprecated/fabric-keybindings-v0/src/client/resources/fabric.mod.json
  deprecated/fabric-loot-api-v2/src/main/resources/fabric.mod.json
  deprecated/fabric-rendering-data-attachment-v1/src/main/resources/fabric.mod.json
  deprecated/fabric-rendering-v0/src/client/resources/fabric.mod.json
  fabric-api-base/src/main/resources/fabric.mod.json
  fabric-api-lookup-api-v1/src/main/resources/fabric.mod.json
  fabric-biome-api-v1/src/main/resources/fabric.mod.json
  fabric-block-api-v1/src/main/resources/fabric.mod.json
  fabric-block-view-api-v2/src/main/resources/fabric.mod.json
  fabric-blockrenderlayer-v1/src/client/resources/fabric.mod.json
  fabric-client-tags-api-v1/src/client/resources/fabric.mod.json
  fabric-command-api-v2/src/main/resources/fabric.mod.json
  fabric-content-registries-v0/src/main/resources/fabric.mod.json
  fabric-convention-tags-v2/src/datagen/resources/fabric.mod.json
  fabric-convention-tags-v2/src/main/resources/fabric.mod.json
  fabric-crash-report-info-v1/src/main/resources/fabric.mod.json
  fabric-data-attachment-api-v1/src/main/resources/fabric.mod.json
  fabric-data-generation-api-v1/src/main/resources/fabric.mod.json
  fabric-dimensions-v1/src/main/resources/fabric.mod.json
  fabric-entity-events-v1/src/main/resources/fabric.mod.json
  fabric-events-interaction-v0/src/main/resources/fabric.mod.json
  fabric-game-rule-api-v1/src/main/resources/fabric.mod.json
  fabric-gametest-api-v1/src/main/resources/fabric.mod.json
  fabric-item-api-v1/src/main/resources/fabric.mod.json
  fabric-item-group-api-v1/src/main/resources/fabric.mod.json
  fabric-key-binding-api-v1/src/client/resources/fabric.mod.json
  fabric-lifecycle-events-v1/src/main/resources/fabric.mod.json
  fabric-loot-api-v3/src/main/resources/fabric.mod.json
  fabric-message-api-v1/src/main/resources/fabric.mod.json
  fabric-model-loading-api-v1/src/client/resources/fabric.mod.json
  fabric-networking-api-v1/src/main/resources/fabric.mod.json
  fabric-object-builder-api-v1/src/main/resources/fabric.mod.json
  fabric-particles-v1/src/main/resources/fabric.mod.json
  fabric-recipe-api-v1/src/main/resources/fabric.mod.json
  fabric-registry-sync-v0/src/main/resources/fabric.mod.json
  fabric-renderer-api-v1/src/client/resources/fabric.mod.json
  fabric-renderer-indigo/src/client/resources/fabric.mod.json
  fabric-rendering-fluids-v1/src/main/resources/fabric.mod.json
  fabric-rendering-v1/src/client/resources/fabric.mod.json
  fabric-resource-conditions-api-v1/src/main/resources/fabric.mod.json
  fabric-resource-loader-v0/src/main/resources/fabric.mod.json
  fabric-screen-api-v1/src/client/resources/fabric.mod.json
  fabric-screen-handler-api-v1/src/main/resources/fabric.mod.json
  fabric-sound-api-v1/src/client/resources/fabric.mod.json
  fabric-transfer-api-v1/src/main/resources/fabric.mod.json
  fabric-transitive-access-wideners-v1/src/main/resources/fabric.mod.json
  gradle.properties
  src/main/resources/fabric.mod.json
Labels: merge me please, priority:high
