Repository FabricMC/fabric, pull requests merged in 2024-09, with the labels that each got.

#4063 Remove CoreShaderRegistrationCallback as its no longer required.
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/CoreShaderRegistrationCallback.java
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/HudAndShaderTest.java
  fabric-rendering-v1/src/testmodClient/resources/assets/fabric-rendering-v1-testmod/shaders/core/test.json
Labels: merge me please, port

#4080 Add `c:animal_foods` tag
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/animal_foods.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
Labels: merge me please

#4058 Add missing `minecraft:enchantable/vanishing` to `c:enchantables`
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/enchantables.json
Labels: merge me please, small change

#4052 Print the full stack trace from the dedicated server watchdog
  fabric-crash-report-info-v1/build.gradle
  fabric-crash-report-info-v1/src/main/java/net/fabricmc/fabric/impl/crash/report/info/ThreadPrinting.java
  fabric-crash-report-info-v1/src/main/java/net/fabricmc/fabric/mixin/crash/report/info/DedicatedServerWatchdogMixin.java
  fabric-crash-report-info-v1/src/main/resources/fabric-crash-report-info-v1.mixins.json
  fabric-crash-report-info-v1/src/testmod/java/net/fabricmc/fabric/test/crash/report/info/ThreadDumpTests.java
  fabric-crash-report-info-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call, merge me please

#4074 Add TransferVariant.getComponentMap()
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/TransferVariant.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/fluid/FluidVariantImpl.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/item/ItemVariantImpl.java
Labels: enhancement, last call, merge me please, small change

#4079 Use unix line endings on all files
  .gitattributes
  build.gradle
Labels: merge me please, small change

#4091 Remove deprecated FRAPI fallback consumers
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/material/MaterialFinder.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/material/MaterialView.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/mesh/Mesh.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/render/RenderContext.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/impl/renderer/VanillaModelEncoder.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/AbstractBlockRenderContext.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/AbstractRenderContext.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/ItemRenderContext.java
Labels: merge me please

#4093 Update Gradle and Mockito
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: merge me please, small change

#4085 Modify Enchantment and Fabric Component Map Builder Extensions
  fabric-item-api-v1/build.gradle
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/EnchantmentEvents.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/EnchantmentSource.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/FabricComponentMapBuilder.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/FabricItemStack.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/impl/item/EnchantmentUtil.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ComponentMapBuilderMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/EnchantmentBuilderAccessor.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/RegistryLoaderMixin.java
  fabric-item-api-v1/src/main/resources/fabric-item-api-v1.mixins.json
  fabric-item-api-v1/src/main/resources/fabric.mod.json
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/CustomEnchantmentEffectsTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/DefaultItemComponentTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/CustomEnchantmentEffectsGameTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/DefaultItemComponentGameTest.java
  fabric-item-api-v1/src/testmod/resources/data/fabric-item-api-v1-testmod/enchantment/weird_impaling.json
  fabric-item-api-v1/src/testmod/resources/data/fabric-item-api-v1-testmod/gametest/structure/bedrock_platform.snbt
  fabric-item-api-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call, merge me please

#4088 Create `c:obsidians` block and item tag
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BlockTagGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/obsidians.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/obsidians/crying.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/obsidians/normal.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/obsidians.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/obsidians/crying.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/obsidians/normal.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalBlockTags.java
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
Labels: enhancement, merge me please

#4097 Add access to ClientConfigurationNetworkHandler in context
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/api/client/networking/v1/ClientConfigurationNetworking.java
  fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientConfigurationNetworkAddon.java
  fabric-networking-api-v1/src/test/java/net/fabricmc/fabric/test/networking/unit/CommonPacketTests.java
Labels: enhancement, last call, fabric-networking, merge me please, small change

#4082 Add ItemVariant#withComponentChanges and FluidVariant#withComponentChanges
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidVariant.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/item/ItemVariant.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/storage/TransferVariant.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/TransferApiImpl.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/fluid/FluidVariantImpl.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/item/ItemVariantImpl.java
  fabric-transfer-api-v1/src/test/java/net/fabricmc/fabric/test/transfer/unittests/FluidVariantTests.java
Labels: enhancement, last call, merge me please, priority:low

#4108 Fix vanilla storage game tests being sensitive to rotation
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/gametests/VanillaStorageTests.java
Labels: merge me please, test, small change

#4038 Add fuel registry events
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/FuelRegistryEvents.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/impl/content/registry/FuelRegistryEventsContextImpl.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/mixin/content/registry/FuelRegistryMixin.java
  fabric-content-registries-v0/src/main/resources/fabric-content-registries-v0.mixins.json
  fabric-content-registries-v0/src/testmod/java/net/fabricmc/fabric/test/content/registry/ContentRegistryGameTest.java
  fabric-content-registries-v0/src/testmod/java/net/fabricmc/fabric/test/content/registry/ContentRegistryTest.java
  fabric-content-registries-v0/src/testmod/resources/assets/fabric-content-registries-v0-testmod/lang/en_us.json
  fabric-content-registries-v0/src/testmod/resources/data/fabric-content-registries-v0-testmod/tags/item/smelting_fuels_excluded_by_tag.json
  fabric-content-registries-v0/src/testmod/resources/data/fabric-content-registries-v0-testmod/tags/item/smelting_fuels_included_by_tag.json
  fabric-content-registries-v0/src/testmod/resources/data/minecraft/tags/item/non_flammable_wood.json
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/CustomDamageTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/FurnaceGameTest.java
Labels: merge me please, port, priority:high

#4121 Update mod to Minecraft snapshot 24w39a
  fabric-content-registries-v0/src/testmod/java/net/fabricmc/fabric/test/content/registry/ContentRegistryTest.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EntityTypeTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/entity_type/boats.json
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/LivingEntityMixin.java
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/entity/FakePlayer.java
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/mixin/itemgroup/client/CreativeInventoryScreenMixin.java
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/CustomFluid.java
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/NoOverlayFluid.java
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/OverlayFluid.java
  fabric-rendering-fluids-v1/src/testmod/java/net/fabricmc/fabric/test/client/rendering/fluid/UnregisteredFluid.java
  fabric-resource-conditions-api-v1/src/testmod/java/net/fabricmc/fabric/test/resource/conditions/DefaultResourceConditionsTest.java
  fabric-resource-conditions-api-v1/src/testmod/resources/data/fabric-resource-conditions-api-v1-testmod/recipe/features_enabled.json
  fabric-resource-loader-v0/src/client/java/net/fabricmc/fabric/mixin/resource/loader/client/CreateWorldScreenMixin.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/item/ComposterWrapper.java
  gradle.properties
Labels: port
