Repository FabricMC/fabric, pull requests merged in 2024-05, with the labels that each got.

#3716 Default English Translations for `c` namespaced tags
  crowdin.yml
  deprecated/fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/impl/tag/convention/ConventionLogWarnings.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/DatagenEntrypoint.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/FabricTagKey.java
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/impl/tag/convention/v2/TranslationConventionLogWarnings.java
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/mixin/tag/TagKeyMixin.java
  fabric-convention-tags-v2/src/main/resources/fabric-convention-tags-api-v2.mixins.json
  fabric-convention-tags-v2/src/main/resources/fabric.mod.json
  fabric-data-generation-api-v1/build.gradle
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricLanguageProvider.java
Labels: enhancement, last call, merge me please

#3726 Use knownPackInfo on mod data packs to avoid registry syncing
  fabric-resource-loader-v0/src/client/java/net/fabricmc/fabric/mixin/resource/loader/client/ClientDataPackManagerMixin.java
  fabric-resource-loader-v0/src/client/resources/fabric-resource-loader-v0.client.mixins.json
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/FabricOriginalKnownPacksGetter.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModNioResourcePack.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackCreator.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackUtil.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ResourceManagerHelperImpl.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/MinecraftServerMixin.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/RegistryLoaderMixin.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/SelectKnownPacksC2SPacketMixin.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/ServerConfigurationNetworkHandlerMixin.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/SynchronizeRegistriesTaskMixin.java
  fabric-resource-loader-v0/src/main/resources/fabric-resource-loader-v0.mixins.json
  fabric-resource-loader-v0/src/testmod/java/net/fabricmc/fabric/test/mixin/resource/loader/SynchronizeRegistriesTaskMixin.java
  fabric-resource-loader-v0/src/testmod/java/net/fabricmc/fabric/test/resource/loader/BuiltinResourcePackTestMod.java
  fabric-resource-loader-v0/src/testmod/resources/assets/fabric-resource-loader-v0-testmod/textures/entity/wolf/green.png
  fabric-resource-loader-v0/src/testmod/resources/assets/fabric-resource-loader-v0-testmod/textures/entity/wolf/pink.png
  fabric-resource-loader-v0/src/testmod/resources/data/minecraft/wolf_variant/woods.json
  fabric-resource-loader-v0/src/testmod/resources/fabric-resource-loader-v0-testmod.mixins.json
  fabric-resource-loader-v0/src/testmod/resources/fabric.mod.json
  fabric-resource-loader-v0/src/testmod/resources/resourcepacks/test2/data/minecraft/wolf_variant/woods.json
Labels: enhancement, last call, merge me please, next?

#3728 Add API to modify default item components
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/DefaultItemComponentEvents.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/impl/item/DefaultItemComponentImpl.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ItemAccessor.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/RegistriesMixin.java
  fabric-item-api-v1/src/main/resources/fabric-item-api-v1.mixins.json
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/DefaultItemComponentTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/DefaultItemComponentGameTest.java
  fabric-item-api-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, last call, merge me please

#3743 Don't enforce a RegistryByteBuf packet code for the extended screen handler type.
  fabric-screen-handler-api-v1/src/main/java/net/fabricmc/fabric/api/screenhandler/v1/ExtendedScreenHandlerType.java
  fabric-screen-handler-api-v1/src/main/java/net/fabricmc/fabric/impl/screenhandler/Networking.java
Labels: bug, last call, merge me please, small change, priority:low

#3744 Support extending dynamic registries in datagen
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/FabricDataGenerator.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/FabricDataGenHelper.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestContent.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/ExperimentalRegistriesValidatorMixin.java
  fabric-registry-sync-v0/src/main/resources/fabric-registry-sync-v0.mixins.json
Labels: enhancement, last call, merge me please

#3749 Support loading a single resource condition instead of array
  fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/api/resource/conditions/v1/ResourceCondition.java
  fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/impl/resource/conditions/ResourceConditionsImpl.java
  fabric-resource-conditions-api-v1/src/testmod/resources/data/fabric-resource-conditions-api-v1-testmod/predicates/loaded.json
Labels: enhancement, last call, merge me please, small change

#3781 Fix non-player handling in CustomDamageHandler
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ItemStackMixin.java
Labels: bug, merge me please, priority:high

#3778 Fix ClientMessageEvents Injection Points
  fabric-message-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/message/ClientPlayNetworkHandlerMixin.java
  fabric-message-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/message/MessageHandlerMixin.java
Labels: bug, merge me please, priority:medium

#3752 Registry resource conditions
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricDynamicRegistryProvider.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
  fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/mixin/resource/conditions/RegistryLoaderMixin.java
  fabric-resource-conditions-api-v1/src/main/resources/fabric-resource-conditions-api-v1.mixins.json
  fabric-resource-conditions-api-v1/src/testmod/java/net/fabricmc/fabric/test/resource/conditions/ConditionalResourcesTest.java
  fabric-resource-conditions-api-v1/src/testmod/resources/data/fabric-resource-conditions-api-v1-testmod/banner_pattern/loaded.json
  fabric-resource-conditions-api-v1/src/testmod/resources/data/fabric-resource-conditions-api-v1-testmod/banner_pattern/not_loaded.json
Labels: enhancement, last call, merge me please

#3777 Finish port to 24w20a
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalBiomeTags.java
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/EnchantmentEvents.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/EquipmentSlotProvider.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/LivingEntityMixin.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/BrewingStandGameTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/FurnaceGameTest.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/ServerChunkLoadingManagerMixin.java
  fabric-networking-api-v1/src/testmod/java/net/fabricmc/fabric/test/networking/common/NetworkingCommonTest.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackCreator.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackUtil.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/SynchronizeRegistriesTaskMixin.java
  fabric-resource-loader-v0/src/testmod/java/net/fabricmc/fabric/test/mixin/resource/loader/SynchronizeRegistriesTaskMixin.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/gametests/VanillaStorageTests.java
Labels: port

#3801 Improve 24w21b port
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/block/BlockApiLookup.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/entity/EntityApiLookup.java
  fabric-api-lookup-api-v1/src/main/java/net/fabricmc/fabric/api/lookup/v1/item/ItemApiLookup.java
  fabric-biome-api-v1/src/testmod/generated/data/fabric-biome-api-v1-testmod/tags/worldgen/biome/tag_selector_test.json
  fabric-biome-api-v1/src/testmod/java/net/fabricmc/fabric/test/biome/TestBiomeTagProvider.java
  fabric-command-api-v2/src/testmod/resources/data/fabric_command_api_v2_testmod/function/load.mcfunction
  fabric-command-api-v2/src/testmod/resources/data/fabric_command_api_v2_testmod/function/tick.mcfunction
  fabric-command-api-v2/src/testmod/resources/data/minecraft/tags/function/load.json
  fabric-command-api-v2/src/testmod/resources/data/minecraft/tags/function/tick.json
  fabric-content-registries-v0/src/testmod/resources/data/minecraft/tags/game_event/vibrations.json
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricCodecDataProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/impl/datagen/loot/FabricLootTableProviderImpl.java
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
  fabric-dimensions-v1/build.gradle
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/api/dimension/v1/FabricDimensions.java
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/impl/dimension/FabricDimensionInternals.java
  fabric-dimensions-v1/src/testmod/java/net/fabricmc/fabric/test/dimension/FabricDimensionTest.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/EntityMixin.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/ServerPlayerEntityMixin.java
  fabric-gametest-api-v1/build.gradle
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/api/gametest/v1/package-info.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/impl/gametest/FabricGameTestHelper.java
  fabric-gametest-api-v1/src/main/resources/data/fabric-gametest-api-v1/gametest/structure/empty.snbt
  fabric-gametest-api-v1/src/testmod/resources/data/fabric-gametest-api-v1-testmod/gametest/structure/exampletestsuite.diamond.snbt
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ItemStackMixin.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/UpdatingItem.java
  fabric-item-api-v1/src/testmod/resources/data/fabric-item-api-v1-testmod/recipe/weird_pickaxe.json
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/DisconnectPacketSource.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/ClientConnectionMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/ServerConfigurationNetworkHandlerMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/ServerLoginNetworkHandlerMixin.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/ServerPlayNetworkHandlerMixin.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModNioResourcePack.java
  fabric-screen-handler-api-v1/src/main/java/net/fabricmc/fabric/api/screenhandler/v1/ExtendedScreenHandlerType.java
  fabric-screen-handler-api-v1/src/testmod/resources/data/fabric-screen-handler-api-v1-testmod/loot_table/blocks/box.json
  fabric-transfer-api-v1/src/testmod/resources/data/fabric-transfer-api-v1-testmod/gametest/structure/double_chest_comparators.snbt
Labels: merge me please, port

#3799 Fix model offset being ignored in non-terrain rendering
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/BlockRenderContext.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/TerrainRenderContext.java
Labels: bug, merge me please, priority:high

#3797 Add mixins for FabricItem.getAttributeModifiers
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ItemStackMixin.java
Labels: bug, merge me please

#3791 Suppress translated tag warnings in prod
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/impl/tag/convention/v2/TranslationConventionLogWarnings.java
Labels: bug, merge me please, small change, priority:high
