Repository FabricMC/fabric, pull requests merged in 2025-04, with the labels that each got.

#4523 Fix EnchantmentEvents.MODIFY not synchronising changes with the client
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/impl/item/EnchantmentUtil.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/EnchantmentBuilderMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/RegistryLoaderMixin.java
  fabric-item-api-v1/src/main/resources/fabric-item-api-v1.mixins.json
Labels: bug, merge me please

#4546 Improve Indigo lighting
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/Indigo.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/aocalc/AoCalculator.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/aocalc/AoConfig.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/aocalc/AoFace.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/helper/GeometryHelper.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/AbstractTerrainRenderContext.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/BlockRenderInfo.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/LightDataProvider.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/TerrainLikeRenderContext.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/TerrainRenderContext.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/mixin/client/indigo/renderer/SectionBuilderMixin.java
Labels: enhancement, indigo, merge me please

#4568 25w14craftmine: Fix vanilla client compatibility.
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SimpleRegistryMixin.java
Labels: bug, registry-sync, merge me please, small change

#4562 Add custom unbaked block state model types
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/CompositeBlockStateModel.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/CustomUnbakedBlockStateModel.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/UnbakedModelDeserializer.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/impl/client/model/loading/CompositeBlockStateModelImpl.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/impl/client/model/loading/CustomUnbakedBlockStateModelInit.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/impl/client/model/loading/CustomUnbakedBlockStateModelRegistry.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/model/loading/UnbakedBlockStateModelMixin.java
  fabric-model-loading-api-v1/src/client/resources/fabric-model-loading-api-v1.mixins.json
  fabric-model-loading-api-v1/src/client/resources/fabric.mod.json
  fabric-model-loading-api-v1/src/testmodClient/resources/assets/minecraft/blockstates/oak_slab.json
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/block/model/MultipartBlockStateModelMixin.java
Labels: enhancement, last call

#4571 [Craftmine] Fix item assets being created for every block
  fabric-data-generation-api-v1/src/client/java/net/fabricmc/fabric/impl/datagen/client/FabricItemAssetDefinitions.java
  fabric-data-generation-api-v1/src/client/java/net/fabricmc/fabric/mixin/datagen/client/ModelProviderItemAssetsMixin.java
  fabric-data-generation-api-v1/src/client/java/net/fabricmc/fabric/mixin/datagen/client/ModelProviderMixin.java
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
  fabric-data-generation-api-v1/template.accesswidener
Labels: bug, status: merge me please

#4538 AttSync: Disconnect when attachment target is null
  crowdin.yml
  fabric-data-attachment-api-v1/src/client/java/net/fabricmc/fabric/impl/attachment/client/AttachmentSyncClient.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/sync/AttachmentChange.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/sync/AttachmentSyncException.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/sync/AttachmentTargetInfo.java
  fabric-data-attachment-api-v1/src/main/resources/assets/fabric-data-attachment-api-v1/lang/en_us.json
  fabric-data-attachment-api-v1/src/test/java/net/fabricmc/fabric/test/attachment/CommonAttachmentTests.java
Labels: enhancement, status: last call, status: merge me please

#4565 Extra models support
  fabric-model-loading-api-v1/build.gradle
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/ExtraModelKey.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/FabricBakedModelManager.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/ModelLoadingPlugin.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/SimpleUnbakedExtraModel.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/UnbakedExtraModel.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/impl/client/model/loading/BakedModelsHooks.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/impl/client/model/loading/ModelLoadingEventDispatcher.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/impl/client/model/loading/ModelLoadingPluginContextImpl.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/model/loading/BakedModelManagerMixin.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/model/loading/ModelBakerBakedModelsMixin.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/model/loading/ModelBakerMixin.java
  fabric-model-loading-api-v1/src/client/resources/fabric-model-loading-api-v1.accesswidener
  fabric-model-loading-api-v1/src/client/resources/fabric-model-loading-api-v1.mixins.json
  fabric-model-loading-api-v1/src/client/resources/fabric.mod.json
  fabric-model-loading-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/model/loading/BakedModelFeatureRenderer.java
  fabric-model-loading-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/model/loading/ModelTestModClient.java
  fabric-model-loading-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/model/loading/SpecificModelReloadListener.java
Labels: enhancement, status: last call, status: merge me please, priority: high

#4569 Ensure `BlockDustParticle` always uses accurate `BlockPos`
  fabric-particles-v1/build.gradle
  fabric-particles-v1/src/client/java/net/fabricmc/fabric/impl/client/particle/ExtendedBlockStateParticleEffectSyncClient.java
  fabric-particles-v1/src/client/java/net/fabricmc/fabric/mixin/client/particle/BlockDustParticleMixin.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/api/particle/v1/FabricBlockStateParticleEffect.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/impl/particle/BlockStateParticleEffectExtension.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/impl/particle/BlockStateParticleEffectFactoryImpl.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/impl/particle/ExtendedBlockStateParticleEffectPacketCodec.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/impl/particle/ExtendedBlockStateParticleEffectSync.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/mixin/particle/BlockStateParticleEffectMixin.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/mixin/particle/BreezeEntityMixin.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/mixin/particle/BrushItemMixin.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/mixin/particle/EntityMixin.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/mixin/particle/LivingEntityMixin.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/mixin/particle/ParticleUtilMixin.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/mixin/particle/ServerPlayerEntityMixin.java
  fabric-particles-v1/src/main/java/net/fabricmc/fabric/mixin/particle/WardenEntityMixin.java
  fabric-particles-v1/src/main/resources/fabric-particles-v1.mixins.json
  fabric-particles-v1/src/main/resources/fabric.mod.json
  fabric-renderer-api-v1/build.gradle
  fabric-renderer-api-v1/src/client/resources/fabric.mod.json
Labels: enhancement, status: last call, status: merge me please

#4572 [1.21.5] Fix item assets being created for every block
  fabric-data-generation-api-v1/src/client/java/net/fabricmc/fabric/impl/datagen/client/FabricItemAssetDefinitions.java
  fabric-data-generation-api-v1/src/client/java/net/fabricmc/fabric/mixin/datagen/client/ModelProviderItemAssetsMixin.java
  fabric-data-generation-api-v1/src/client/java/net/fabricmc/fabric/mixin/datagen/client/ModelProviderMixin.java
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
  fabric-data-generation-api-v1/template.accesswidener
Labels: bug, status: merge me please

#4576 Fix mixin name validation not running.
  build.gradle
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/impl/client/gametest/context/TestClientWorldContextImpl.java
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/gametest/ClientChunkManagerClientChunkMapAccessor.java
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/gametest/threading/MainMixin.java
  fabric-client-gametest-api-v1/src/client/resources/fabric-client-gametest-api-v1.mixins.json
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/mixin/content/registry/AbstractBlockAbstractBlockStateMixin.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/mixin/content/registry/AbstractBlockAccessor.java
  fabric-content-registries-v0/src/main/resources/fabric-content-registries-v0.mixins.json
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/sync/AttachmentChange.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/CustomPayloadC2SPacketAccessor.java
  fabric-data-attachment-api-v1/src/main/resources/fabric-data-attachment-api-v1.mixins.json
  fabric-data-generation-api-v1/src/client/java/net/fabricmc/fabric/mixin/datagen/client/ModelProviderBlockStateSuppliersMixin.java
  fabric-data-generation-api-v1/src/client/resources/fabric-data-generation-api-v1.client.mixins.json
  fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/dimension/TaggedChoiceTaggedChoiceTypeMixin.java
  fabric-dimensions-v1/src/main/resources/fabric-dimensions-v1.mixins.json
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/block/model/MultipartBlockStateModelMixin.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/block/model/MultipartBlockStateModelMultipartBakedModelAccessor.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/item/BasicItemModelUnbakedMixin.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/item/ItemRenderStateLayerRenderStateMixin.java
  fabric-renderer-api-v1/src/client/resources/fabric-renderer-api-v1.mixins.json
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/mixin/client/indigo/renderer/ItemRenderStateLayerRenderStateMixin.java
  fabric-renderer-indigo/src/client/resources/fabric-renderer-indigo.mixins.json
Labels: status: merge me please, small change

#4584 Small buildscript tweaks
  build.gradle
  fabric-particles-v1/src/main/resources/fabric.mod.json
  gradle/module-versioning.gradle
  gradle/validate-annotations.gradle
Labels: status: merge me please, small change

#4560 Add FabricSoundProvider and related builders
  fabric-data-generation-api-v1/src/client/java/net/fabricmc/fabric/api/client/datagen/v1/builder/SoundTypeBuilder.java
  fabric-data-generation-api-v1/src/client/java/net/fabricmc/fabric/api/client/datagen/v1/provider/FabricSoundsProvider.java
  fabric-data-generation-api-v1/src/client/java/net/fabricmc/fabric/impl/datagen/client/SoundTypeBuilderImpl.java
  fabric-data-generation-api-v1/src/testmod/generated/resourcepacks/example_builtin/assets/fabric-data-gen-api-v1-testmod/sounds.json
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestContent.java
  fabric-data-generation-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/datagen/client/DataGeneratorClientTestEntrypoint.java
Labels: enhancement, status: last call

#4586 [1.21.1] AttSync: Disconnect when attachment target is null
  crowdin.yml
  fabric-data-attachment-api-v1/src/client/java/net/fabricmc/fabric/impl/attachment/client/AttachmentSyncClient.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/sync/AttachmentChange.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/sync/AttachmentSyncException.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/sync/AttachmentTargetInfo.java
  fabric-data-attachment-api-v1/src/main/resources/assets/fabric-data-attachment-api-v1/lang/en_us.json
  fabric-data-attachment-api-v1/src/test/java/net/fabricmc/fabric/test/attachment/CommonAttachmentTests.java
Labels: enhancement, status: merge me please, backport
