Repository FabricMC/fabric, pull requests merged in 2025-06, with the labels that each got.

#4639 Port Hud Api
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/HudRenderCallback.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/hud/HudElement.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/hud/HudElementRegistry.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/hud/VanillaHudElements.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/hud/HudElementRegistryImpl.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/hud/HudLayer.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/InGameHudMixin.java
  fabric-rendering-v1/src/test/java/net/fabricmc/fabric/impl/client/rendering/hud/HudElementRegistryTest.java
  fabric-rendering-v1/src/testmod/resources/fabric.mod.json
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/HudTests.java
  fabric-rendering-v1/src/testmodClient/resources/templates/hud_layer_test_after_hotbar_and_bars.png
  fabric-rendering-v1/src/testmodClient/resources/templates/hud_layer_test_after_misc_overlay.png
  fabric-rendering-v1/src/testmodClient/resources/templates/hud_layer_test_before_misc_overlay.png
Labels: status: last call, port

#4695 Make inline loot table test a game test
  fabric-loot-api-v3/src/testmod/java/net/fabricmc/fabric/test/loot/LootGameTest.java
  fabric-loot-api-v3/src/testmod/java/net/fabricmc/fabric/test/loot/LootTest.java
  fabric-loot-api-v3/src/testmod/resources/fabric.mod.json
Labels: tests

#4698 [1.21.1] Registry aliasing backport
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/api/event/registry/FabricRegistry.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/RegistryMixin.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SimpleRegistryMixin.java
  fabric-registry-sync-v0/src/main/resources/fabric-registry-sync-v0.mixins.json
  fabric-registry-sync-v0/src/main/resources/fabric.mod.json
  fabric-registry-sync-v0/src/test/java/net/fabricmc/fabric/test/registry/sync/RegistryAliasTest.java
  fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/RegistryAliasTest.java
  fabric-registry-sync-v0/src/testmod/resources/assets/fabric-registry-sync-v0-testmod/models/block/test_block.json
  fabric-registry-sync-v0/src/testmod/resources/assets/fabric-registry-sync-v0-testmod/models/block/test_block_old.json
  fabric-registry-sync-v0/src/testmod/resources/assets/fabric-registry-sync-v0-testmod/models/item/test_block.json
  fabric-registry-sync-v0/src/testmod/resources/assets/fabric-registry-sync-v0-testmod/models/item/test_block_old.json
  fabric-registry-sync-v0/src/testmod/resources/assets/fabric-registry-sync-v0-testmod/models/item/test_ingot.json
  fabric-registry-sync-v0/src/testmod/resources/assets/fabric-registry-sync-v0-testmod/models/item/test_ingot_old.json
  fabric-registry-sync-v0/src/testmod/resources/fabric.mod.json
Labels: enhancement, status: merge me please, backport

#4690 Add `GatherDebugTextEvents`
  fabric-renderer-api-v1/build.gradle
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/impl/renderer/DebugHudClient.java
  fabric-renderer-api-v1/src/client/resources/fabric-renderer-api-v1.debughud.mixins.json
  fabric-renderer-api-v1/src/client/resources/fabric.mod.json
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/GatherDebugTextEvents.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/DebugHudMixin.java
  fabric-rendering-v1/src/client/resources/fabric-rendering-v1.mixins.json
  fabric-rendering-v1/src/testmod/resources/fabric.mod.json
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/DebugTextTest.java
Labels: enhancement, status: last call, status: merge me please, small change

#4693 ArmorRenderer: Add option to disable default head item rendering
  fabric-rendering-v1/build.gradle
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/ArmorRenderer.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/BipedEntityRendererMixin.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/LivingEntityRendererMixin.java
  fabric-rendering-v1/src/client/resources/fabric-rendering-v1.mixins.json
  fabric-rendering-v1/src/testmod/java/net/fabricmc/fabric/test/rendering/ArmorRenderingTestsInit.java
  fabric-rendering-v1/src/testmod/resources/fabric.mod.json
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/ArmorRenderingTests.java
Labels: bug, enhancement, status: last call, status: merge me please, priority: low

#4705 Fix `FabricLayerRenderState` javadoc
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/render/FabricLayerRenderState.java
Labels: status: merge me please, small change, cleanup

#4706 Add `DrawItemStackOverlayCallback`
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/DrawItemStackOverlayCallback.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/DrawContextMixin.java
  fabric-rendering-v1/src/client/resources/fabric-rendering-v1.mixins.json
  fabric-rendering-v1/src/testmod/resources/fabric.mod.json
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/ItemStackOverlayTest.java
Labels: enhancement, status: last call, small change

#4724 [1.21.1] Fix FabricRecipeProvider.getRecipeIdentifier not applying to recipe advancements
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricRecipeProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/recipe/FabricRecipeExporter.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/mixin/datagen/recipe/AllCraftingRecipeJsonBuildersMixin.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/mixin/datagen/recipe/ComplexRecipeJsonBuilderMixin.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/mixin/datagen/recipe/SmithingTransformRecipeJsonBuilderMixin.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/mixin/datagen/recipe/SmithingTrimRecipeJsonBuilderMixin.java
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.mixins.json
  fabric-data-generation-api-v1/src/main/resources/fabric.mod.json
Labels: bug, status: merge me please, backport

#4726 [1.21.1] ArmorRenderer: Add option to disable default head item rendering
  fabric-rendering-v1/build.gradle
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/ArmorRenderer.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/HeadFeatureRendererMixin.java
  fabric-rendering-v1/src/client/resources/fabric-rendering-v1.mixins.json
  fabric-rendering-v1/src/testmod/java/net/fabricmc/fabric/test/rendering/ArmorRenderingTestsInit.java
  fabric-rendering-v1/src/testmod/resources/fabric.mod.json
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/ArmorRenderingTests.java
  fabric-rendering-v1/src/testmodClient/resources/assets/fabric-rendering-v1-testmod/models/item/custom_helmet.json
Labels: status: merge me please, backport

#4722 Add lava chicken music disk to music disks tag.
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/music_discs.json
  src/main/resources/fabric.mod.json
Labels: status: merge me please

#4725 Fix getRecipeIdentifier applying twice to advancement paths
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricRecipeProvider.java
Labels: bug, status: merge me please, small change
