Repository FabricMC/fabric, pull requests merged in 2025-05, with the labels that each got.

#4541 Add ServerChunkEvents.CHUNK_LEVEL_TYPE_CHANGE
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/api/event/lifecycle/v1/ServerChunkEvents.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/impl/event/lifecycle/ChunkLevelTypeEventTracker.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/ChunkGeneratingMixin.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/ChunkHolderMixin.java
  fabric-lifecycle-events-v1/src/main/resources/fabric-lifecycle-events-v1.mixins.json
  fabric-lifecycle-events-v1/src/testmod/java/net/fabricmc/fabric/test/event/lifecycle/ServerChunkLifecycleTests.java
Labels: enhancement, status: last call, status: merge me please

#4587 Add component tooltip appender registry
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/ComponentTooltipAppenderRegistry.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/impl/item/ComponentTooltipAppenderRegistryImpl.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/impl/item/VanillaTooltipAppenderOrder.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ItemStackMixin.java
  fabric-item-api-v1/src/test/java/net/fabricmc/fabric/test/item/unittest/ComponentTooltipAppenderRegistryTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/ComponentTooltipAppenderTest.java
  fabric-item-api-v1/src/testmod/resources/fabric.mod.json
Labels: enhancement, status: last call, status: merge me please

#4597 Add system property to filter mods for client tests.
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/impl/client/gametest/FabricClientGameTestRunner.java
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/impl/client/gametest/TestSystemProperties.java
Labels: enhancement, status: last call, status: merge me please, small change

#4610 [1.21.1] Add ServerChunkEvents.CHUNK_LEVEL_TYPE_CHANGE
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/api/event/lifecycle/v1/ServerChunkEvents.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/impl/event/lifecycle/ChunkLevelTypeEventTracker.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/ChunkGeneratingMixin.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/ChunkHolderMixin.java
  fabric-lifecycle-events-v1/src/main/resources/fabric-lifecycle-events-v1.mixins.json
  fabric-lifecycle-events-v1/src/testmod/java/net/fabricmc/fabric/test/event/lifecycle/ServerChunkLifecycleTests.java
Labels: enhancement, status: merge me please, backport

#4606 Attachment changed event
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/api/attachment/v1/AttachmentTarget.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/AttachmentTargetsMixin.java
  fabric-data-attachment-api-v1/src/testmod/java/net/fabricmc/fabric/test/attachment/AttachmentTestMod.java
  fabric-data-attachment-api-v1/src/testmod/resources/fabric.mod.json
  fabric-data-attachment-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/attachment/client/AttachmentClientTestMod.java
  fabric-data-attachment-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/attachment/client/gametest/SyncGametest.java
Labels: enhancement, status: last call, status: merge me please

#4615 Fix profiled resource sorting.
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/SimpleResourceReloadMixin.java
Labels: bug, status: merge me please, small change

#4614 Replace all uses of LocalCapture with @Local (Now for 1.21.6)
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/LivingEntityMixin.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/ServerPlayerEntityMixin.java
  fabric-events-interaction-v0/src/client/java/net/fabricmc/fabric/mixin/event/interaction/client/ClientPlayerInteractionManagerMixin.java
  fabric-events-interaction-v0/src/client/java/net/fabricmc/fabric/mixin/event/interaction/client/MinecraftClientMixin.java
  fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/mixin/event/interaction/ServerPlayerInteractionManagerMixin.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/StructureTemplateManagerMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/AbstractFurnaceBlockEntityMixin.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/BrewingStandBlockEntityMixin.java
  fabric-lifecycle-events-v1/src/client/java/net/fabricmc/fabric/mixin/event/lifecycle/client/ClientChunkManagerMixin.java
  fabric-lifecycle-events-v1/src/client/java/net/fabricmc/fabric/mixin/event/lifecycle/client/WorldChunkMixin.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/MinecraftServerMixin.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/server/WorldChunkMixin.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/EntityModelsMixin.java
  fabric-screen-handler-api-v1/src/main/java/net/fabricmc/fabric/mixin/screenhandler/ServerPlayerEntityMixin.java
Labels: status: merge me please, cleanup

#4617 remove At.SHIFT.BY
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/ServerPlayerEntityMixin.java
  fabric-lifecycle-events-v1/src/client/java/net/fabricmc/fabric/mixin/event/lifecycle/client/WorldChunkMixin.java
  fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/server/WorldChunkMixin.java
  fabric-rendering-fluids-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/fluid/FluidRendererMixin.java
Labels: status: merge me please, cleanup

#4618 Ensure all mixin methods and fields are marked Unique as required.
  checkstyle.xml
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/BiomeSourceMixin.java
  fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/mixin/biome/TheEndBiomeSourceMixin.java
  fabric-block-view-api-v2/src/client/java/net/fabricmc/fabric/mixin/blockview/client/ChunkRendererRegionBuilderMixin.java
  fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/mixin/content/registry/FireBlockMixin.java
  fabric-crash-report-info-v1/src/main/java/net/fabricmc/fabric/mixin/crash/report/info/SystemDetailsMixin.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/AttachmentTargetsMixin.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/ClientConnectionMixin.java
  fabric-events-interaction-v0/src/client/java/net/fabricmc/fabric/mixin/event/interaction/client/MinecraftClientMixin.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/StructureTemplateManagerMixin.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/SpriteAtlasTextureMixin.java
  fabric-rendering-fluids-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/fluid/FluidRendererMixin.java
  fabric-resource-loader-v0/src/client/java/net/fabricmc/fabric/mixin/resource/loader/client/KeyedResourceReloadListenerClientMixin.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/KeyedResourceReloadListenerMixin.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/server/LanguageMixin.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/mixin/transfer/FluidMixin.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/mixin/transfer/ItemMixin.java
Labels: cleanup

#4619 Add sound event subtitle to language generation
  fabric-data-generation-api-v1/src/client/java/net/fabricmc/fabric/api/client/datagen/v1/builder/SoundTypeBuilder.java
  fabric-data-generation-api-v1/src/client/java/net/fabricmc/fabric/api/client/datagen/v1/provider/FabricSoundsProvider.java
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricLanguageProvider.java
  fabric-data-generation-api-v1/src/testmod/generated/assets/fabric-data-gen-api-v1-testmod/lang/en_us.json
  fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
Labels: enhancement, status: last call

#4616 Fix Inject in IngredientMixin not being marked as cancellable.
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/mixin/recipe/ingredient/IngredientMixin.java
Labels: bug, status: merge me please, small change

#4630 Data Attachments: Don't mark changed & sync if old value is the same as new value
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/AttachmentTargetsMixin.java
Labels: enhancement, status: last call, status: merge me please, small change

#4647 Merge client tag API into tag API
  fabric-client-tags-api-v1/build.gradle
  fabric-client-tags-api-v1/src/client/resources/assets/fabric-client-tags-api-v1/icon.png
  fabric-client-tags-api-v1/src/client/resources/fabric.mod.json
  fabric-client-tags-api-v1/src/testmodClient/resources/fabric.mod.json
  fabric-tag-api-v1/build.gradle
  fabric-tag-api-v1/src/client/java/net/fabricmc/fabric/api/tag/client/v1/ClientTags.java
  fabric-tag-api-v1/src/client/java/net/fabricmc/fabric/impl/tag/client/ClientTagsImpl.java
  fabric-tag-api-v1/src/client/java/net/fabricmc/fabric/impl/tag/client/ClientTagsLoader.java
  fabric-tag-api-v1/src/main/resources/fabric.mod.json
  fabric-tag-api-v1/src/testmod/resources/fabric.mod.json
  fabric-tag-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/tag/client/v1/ClientTagTest.java
  fabric-tag-api-v1/src/testmodClient/resources/data/fabric/tags/block/sword_efficient.json
  fabric-tag-api-v1/src/testmodClient/resources/resourcepacks/test2/data/minecraft/tags/block/sword_efficient.json
  fabric-tag-api-v1/src/testmodClient/resources/resourcepacks/test2/pack.mcmeta
  gradle.properties
  settings.gradle
Labels: cleanup

#4640 Don't erase data attachments if missing in NBT
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/AttachmentTargetsMixin.java
Labels: status: last call, small change

#4644 Add tag to make open trapdoors above tagged blocks climbable
  fabric-block-api-v1/build.gradle
  fabric-block-api-v1/src/main/java/net/fabricmc/fabric/api/block/v1/BlockFunctionalityTags.java
  fabric-block-api-v1/src/main/java/net/fabricmc/fabric/mixin/block/LivingEntityMixin.java
  fabric-block-api-v1/src/main/resources/fabric-block-api-v1.mixins.json
  fabric-block-api-v1/src/testmod/java/net/fabricmc/fabric/test/block/ClimbableTrapdoorTest.java
  fabric-block-api-v1/src/testmod/resources/assets/fabric-block-api-v1-testmod/blockstates/custom_ladder.json
  fabric-block-api-v1/src/testmod/resources/assets/fabric-block-api-v1-testmod/blockstates/custom_non_ladder.json
  fabric-block-api-v1/src/testmod/resources/assets/fabric-block-api-v1-testmod/models/block/custom_ladder.json
  fabric-block-api-v1/src/testmod/resources/assets/fabric-block-api-v1-testmod/models/block/custom_non_ladder.json
  fabric-block-api-v1/src/testmod/resources/assets/fabric-block-api-v1-testmod/textures/block/custom_ladder.png
  fabric-block-api-v1/src/testmod/resources/assets/fabric-block-api-v1-testmod/textures/block/custom_non_ladder.png
  fabric-block-api-v1/src/testmod/resources/data/fabric/tags/block/can_climb_trapdoor_above.json
  fabric-block-api-v1/src/testmod/resources/data/minecraft/tags/block/climbable.json
  fabric-block-api-v1/src/testmod/resources/fabric.mod.json
  fabric-block-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/block/client/ClimbableTrapdoorClientTest.java
Labels: enhancement, status: last call, priority: low

#4646 Add ServerLoginNetworking.getSender
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerLoginNetworking.java
Labels: status: last call, module: networking api, small change

#4648 Added multiple `c:primary_wood_type` biome tags
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BiomeTagGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/primary_wood_type.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/primary_wood_type/acacia.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/primary_wood_type/bamboo.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/primary_wood_type/birch.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/primary_wood_type/cherry.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/primary_wood_type/crimson.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/primary_wood_type/dark_oak.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/primary_wood_type/jungle.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/primary_wood_type/mangrove.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/primary_wood_type/oak.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/primary_wood_type/pale_oak.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/primary_wood_type/spruce.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/primary_wood_type/warped.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalBiomeTags.java
Labels: status: last call, area: tags

#4654 Fix #4487 for 1.20.1
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerPlayNetworkAddon.java
Labels: status: merge me please, backport

#4665 [1.21.1] Backport world attachment sync fix from #4366
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/sync/AttachmentSync.java
Labels: status: merge me please, backport

#4658 [1.21.1] Call AFTER_PLAYER_CHANGE_WORLD on respawn in different world
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/ServerEntityWorldChangeEvents.java
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/PlayerManagerMixin.java
Labels: backport

#4656 Backport #4621 to 1.21.3
  fabric-message-api-v1/src/client/java/net/fabricmc/fabric/api/client/message/v1/ClientReceiveMessageEvents.java
Labels: backport

#4655 Backport #4621 to 1.21.4
  fabric-message-api-v1/src/client/java/net/fabricmc/fabric/api/client/message/v1/ClientReceiveMessageEvents.java
Labels: backport

#4668 Fix UseItemCallback not using .isAccepted() Closes #4666
  fabric-events-interaction-v0/src/client/java/net/fabricmc/fabric/mixin/event/interaction/client/ClientPlayerInteractionManagerMixin.java
Labels: bug, status: merge me please, small change

#4650 Finalize 1.21.5 FRAPI port and other improvements
  fabric-model-loading-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/model/loading/BakedModelFeatureRenderer.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/Renderer.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/mesh/MutableQuadView.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/mesh/QuadEmitter.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/model/FabricBlockModelPart.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/model/FabricBlockStateModel.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/model/MeshBakedGeometry.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/model/ModelBakeSettingsHelper.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/model/ModelHelper.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/model/SpriteFinder.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/render/FabricBlockModelRenderer.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/render/FabricBlockRenderManager.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/render/FabricLayerRenderState.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/render/RenderLayerHelper.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/sprite/FabricAtlasPreparation.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/sprite/FabricErrorCollectingSpriteGetter.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/sprite/FabricSpriteAtlasTexture.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/sprite/FabricStitchResult.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/impl/renderer/QuadSpriteBaker.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/impl/renderer/SpriteFinderImpl.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/impl/renderer/StitchResultExtension.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/block/model/GeometryBakedModelMixin.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/block/render/FallingBlockEntityRendererMixin.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/block/render/PistonBlockEntityRendererMixin.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/block/render/SnowGolemPumpkinFeatureRendererMixin.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/item/BasicItemModelMixin.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/sprite/BakedModelManager1Mixin.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/sprite/ErrorCollectingSpriteGetterMixin.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/sprite/SpriteAtlasManagerAtlasPreparationMixin.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/sprite/SpriteAtlasTextureMixin.java
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/sprite/SpriteLoaderStitchResultMixin.java
  fabric-renderer-api-v1/src/client/resources/fabric-renderer-api-v1.mixins.json
  fabric-renderer-api-v1/src/client/resources/fabric.mod.json
  fabric-renderer-api-v1/src/testmod/java/net/fabricmc/fabric/test/renderer/OctagonalColumnBlock.java
  fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/FrameGeometry.java
  fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/OctagonalColumnGeometry.java
  fabric-renderer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/renderer/client/PillarGeometry.java
  fabric-renderer-api-v1/src/testmodClient/resources/assets/fabric-renderer-api-v1-testmod/blockstates/octagonal_column.json
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/IndigoRenderer.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/aocalc/AoCalculator.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/aocalc/AoFace.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/aocalc/AoFaceData.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/helper/GeometryHelper.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/mesh/MutableQuadViewImpl.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/ItemRenderContext.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/mixin/client/indigo/renderer/BlockRenderManagerMixin.java
Labels: enhancement, module: renderer indigo, priority: high, cleanup
