Repository FabricMC/fabric, pull requests merged in 2025-02, with the labels that each got.

#4419 Port to 25w06a
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/ServerWorldMixin.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/UpdatingItem.java
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/PersistentStateManagerTest.java
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/DimensionalRenderingTest.java
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/HudAndShaderTest.java
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/WorldRenderEventsTests.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/item/PlayerInventoryStorageImpl.java
  fabric-transfer-api-v1/src/test/java/net/fabricmc/fabric/test/transfer/unittests/PlayerInventoryStorageTests.java
  fabric-transfer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/transfer/ingame/client/FluidVariantRenderTest.java
  fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener
  gradle.properties
Labels: port, priority:high

#4421 Fixes to the rendering test mods
  fabric-rendering-v1/build.gradle
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/DimensionalRenderingTest.java
  fabric-transfer-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/transfer/ingame/client/FluidVariantRenderTest.java
Labels: merge me please

#4221 Change Creative Buttons Texture
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/impl/client/itemgroup/FabricCreativeGuiComponents.java
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/mixin/itemgroup/client/CreativeInventoryScreenMixin.java
  fabric-item-group-api-v1/src/main/resources/assets/fabric/textures/gui/creative_buttons.png
  fabric-item-group-api-v1/src/main/resources/programmer_art/assets/fabric/textures/gui/creative_buttons.png
Labels: last call, merge me please

#4427 Add a method for overriding modelId in item settings.
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/FabricItem.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ItemSettingsMixin.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/CustomModelIdTest.java
  fabric-item-api-v1/src/testmod/resources/fabric.mod.json
Labels: merge me please, small change

#4424 Rename "data" and "network" codecs to "server" and "client" codecs
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/api/event/registry/DynamicRegistries.java
  fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/DynamicRegistriesImpl.java
Labels: merge me please, small change

#4321 Add `UnbakedModelDeserializer`
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/api/client/model/loading/v1/UnbakedModelDeserializer.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/impl/client/model/loading/UnbakedModelDeserializerRegistry.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/impl/client/model/loading/UnbakedModelJsonDeserializer.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/model/loading/BakedModelManagerMixin.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/model/loading/JsonUnbakedModelAccessor.java
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/model/loading/JsonUnbakedModelMixin.java
  fabric-model-loading-api-v1/src/client/resources/fabric-model-loading-api-v1.mixins.json
  fabric-model-loading-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/model/loading/UnbakedModelDeserializerTest.java
  fabric-model-loading-api-v1/src/testmodClient/resources/assets/fabric-model-loading-api-v1-testmod/models/block/emerald_block.json
  fabric-model-loading-api-v1/src/testmodClient/resources/assets/minecraft/blockstates/emerald_block.json
  fabric-model-loading-api-v1/src/testmodClient/resources/fabric.mod.json
Labels: enhancement, last call, merge me please

#4119 Add Hud Render Events
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/api/client/gametest/v1/screenshot/TestScreenshotComparisonOptions.java
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/impl/client/gametest/screenshot/TestScreenshotComparisonOptionsImpl.java
  fabric-rendering-v1/build.gradle
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/HudLayerRegistrationCallback.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/HudRenderCallback.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/IdentifiedLayer.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/LayeredDrawerWrapper.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/LayerInjectionPoint.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/LayeredDrawerWrapperImpl.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/SubLayer.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/impl/client/rendering/WrappedLayer.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/InGameHudMixin.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/LayeredDrawerAccessor.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/LayeredDrawerMixin.java
  fabric-rendering-v1/src/client/resources/fabric-rendering-v1.mixins.json
  fabric-rendering-v1/src/test/java/net/fabricmc/fabric/impl/client/rendering/LayeredDrawerWrapperTest.java
  fabric-rendering-v1/src/testmod/resources/fabric.mod.json
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/HudLayerTests.java
  fabric-rendering-v1/src/testmodClient/resources/templates/hud_layer_test_after_experience_level.png
  fabric-rendering-v1/src/testmodClient/resources/templates/hud_layer_test_after_misc_overlay.png
  fabric-rendering-v1/src/testmodClient/resources/templates/hud_layer_test_after_subtitles.png
  fabric-rendering-v1/src/testmodClient/resources/templates/hud_layer_test_before_chat.png
  fabric-rendering-v1/src/testmodClient/resources/templates/hud_layer_test_before_demo_timer.png
  fabric-rendering-v1/src/testmodClient/resources/templates/hud_layer_test_before_misc_overlay.png
Labels: enhancement, last call, merge me please

#4416 Use page up/down to change creative inventory pages.
  fabric-item-group-api-v1/src/client/java/net/fabricmc/fabric/mixin/itemgroup/client/CreativeInventoryScreenMixin.java
Labels: enhancement, small change

#4440 Initial 25w07a port
  fabric-data-generation-api-v1/src/main/resources/fabric-data-generation-api-v1.accesswidener
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/ServerPlayerEntityMixin.java
  fabric-lifecycle-events-v1/src/client/java/net/fabricmc/fabric/mixin/event/lifecycle/client/ClientChunkManagerMixin.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/trade/TradeOfferHelper.java
  fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/impl/object/builder/TradeOfferInternals.java
  fabric-object-builder-api-v1/src/main/resources/fabric-object-builder-api-v1.accesswidener
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/VillagerTypeTest1.java
  fabric-rendering-v1/src/client/java/net/fabricmc/fabric/mixin/client/rendering/WorldRendererMixin.java
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/DimensionalRenderingTest.java
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/HudAndShaderTest.java
  fabric-rendering-v1/src/testmodClient/java/net/fabricmc/fabric/test/rendering/client/WorldRenderEventsTests.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/SimpleResourceReloadMixin.java
  fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/item/PlayerInventoryStorageImpl.java
  fabric-transfer-api-v1/src/test/java/net/fabricmc/fabric/test/transfer/unittests/PlayerInventoryStorageTests.java
  fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener
  fabric-transitive-access-wideners-v1/template.accesswidener
  gradle.properties
  settings.gradle
Labels: port, priority:high

#4432 Add getAllMatches and getAllOfType method to ServerRecipeManager
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/api/recipe/v1/FabricServerRecipeManager.java
  fabric-recipe-api-v1/src/main/java/net/fabricmc/fabric/mixin/recipe/ServerRecipeManagerMixin.java
  fabric-recipe-api-v1/src/main/resources/fabric-recipe-api-v1.mixins.json
  fabric-recipe-api-v1/src/main/resources/fabric.mod.json
Labels: enhancement, last call, merge me please, small change

#4434 Include template name in the error message if possible
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/api/client/gametest/v1/screenshot/TestScreenshotComparisonOptions.java
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/impl/client/gametest/context/ClientGameTestContextImpl.java
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/impl/client/gametest/screenshot/TestScreenshotComparisonOptionsImpl.java
Labels: enhancement, merge me please, small change

#4070 [1.21.5] Implement builtin mod resource/data pack sorting
  fabric-resource-loader-v0/build.gradle
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModNioResourcePack.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackCreator.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackSorter.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackUtil.java
  fabric-resource-loader-v0/src/testmod/java/net/fabricmc/fabric/test/resource/loader/BuiltinPackSortingTest.java
  fabric-resource-loader-v0/src/testmod/resources/fabric.mod.json
  fabric-resource-loader-v0/src/testmodA/resources/data/fabric-resource-loader-v0-testmod/recipe/disabled_by_b.json
  fabric-resource-loader-v0/src/testmodA/resources/fabric.mod.json
  fabric-resource-loader-v0/src/testmodB/resources/data/fabric-resource-loader-v0-testmod/recipe/disabled_by_b.json
  fabric-resource-loader-v0/src/testmodB/resources/data/fabric-resource-loader-v0-testmod/recipe/disabled_by_c.json
  fabric-resource-loader-v0/src/testmodB/resources/data/fabric-resource-loader-v0-testmod/recipe/enabled_by_c.json
  fabric-resource-loader-v0/src/testmodB/resources/fabric.mod.json
  fabric-resource-loader-v0/src/testmodC/resources/data/fabric-resource-loader-v0-testmod/recipe/disabled_by_c.json
  fabric-resource-loader-v0/src/testmodC/resources/data/fabric-resource-loader-v0-testmod/recipe/enabled_by_c.json
  fabric-resource-loader-v0/src/testmodC/resources/fabric.mod.json
Labels: enhancement, last call, merge me please

#4441 Loom 1.10, remove grgit, work towards config caching.
  .github/workflows/build.yml
  .github/workflows/manage_issues.yml
  .github/workflows/release.yml
  .gitignore
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/net/fabricmc/fabric/impl/build/AbstractGitValueSource.java
  buildSrc/src/main/java/net/fabricmc/fabric/impl/build/CommitHashValueSource.java
  buildSrc/src/main/java/net/fabricmc/fabric/impl/build/GitBranchValueSource.java
  deprecated/build.gradle
  fabric-api-catalog/build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: merge me please

#4448 Fix module dep versioning
  build.gradle
  deprecated/build.gradle
Labels: merge me please, priority:high

#4451 Fix locale-dependent code in GameTest
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/impl/client/gametest/context/ClientGameTestContextImpl.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/impl/gametest/TestAnnotationLocator.java
Labels: bug, merge me please, test, small change

#4384 Convention Drink Tags
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/drink_containing/bottle.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/drink_containing/bucket.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/drinks.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/drinks/honey.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/drinks/juice.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/drinks/magic.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/drinks/milk.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/drinks/ominous.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/drinks/water.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/drinks/watery.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
Labels: last call, merge me please, tags

#4445 Add eggs tag documentation
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
Labels: merge me please, small change, tags

#4446 Add contains method to FabricComponentMapBuilder
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/FabricComponentMapBuilder.java
  fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ComponentMapBuilderMixin.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/DefaultItemComponentGameTest.java
Labels: enhancement, last call, merge me please, small change

#4447 Change elytra event mixin injection point
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/elytra/LivingEntityMixin.java
Labels: bug, merge me please, small change

#4454 Fix chunk attachments not marking the chunk for saving.
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/ChunkMixin.java
Labels: bug, merge me please, small change, priority:high

#4452 Add vararg helper methods for multi-tag support in the FabricTagBuilder
  fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricTagProvider.java
Labels: enhancement, last call, merge me please
