Repository FabricMC/fabric, pull requests merged in 2025-01, with the labels that each got.

#4334 Solve inconsistency issues in client gametests
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/api/client/gametest/v1/package-info.java
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/impl/client/gametest/NetworkSynchronizer.java
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/impl/client/gametest/ThreadingImpl.java
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/gametest/ClientConnectionMixin.java
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/gametest/MinecraftClientMixin.java
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/gametest/MinecraftServerMixin.java
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/gametest/ThreadExecutorMixin.java
  fabric-client-gametest-api-v1/src/client/resources/fabric-client-gametest-api-v1.mixins.json
Labels: enhancement, merge me please, test, priority:high

#4347 Implement toString() for materials to help with debugging
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/material/MaterialFinderImpl.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/material/MaterialViewImpl.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/material/RenderMaterialImpl.java
Labels: merge me please, small change

#4350 Fix `MutableQuadViewImpl#fromVanilla` methods not setting correct normal flags
  fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/mesh/MutableQuadView.java
  fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/mesh/MutableQuadViewImpl.java
Labels: bug, indigo, merge me please, small change, priority:medium

#4356 Fix #4332
  fabric-model-loading-api-v1/src/client/java/net/fabricmc/fabric/mixin/client/model/loading/ReferencedModelsCollectorMixin.java
  fabric-model-loading-api-v1/src/testmodClient/resources/assets/fabric-model-loading-api-v1-testmod/models/half_red_sand.json
  fabric-model-loading-api-v1/src/testmodClient/resources/assets/fabric-model-loading-api-v1-testmod/models/template_half.json
Labels: bug, merge me please, small change, priority:high

#4352 Add `c:flowers`, `c:flowers/tall`, and `c:flowers/small` block and item tags
  deprecated/fabric-convention-tags-v1/src/main/java/net/fabricmc/fabric/impl/tag/convention/ConventionLogWarnings.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BlockTagGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/flowers.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/flowers/small.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/flowers/tall.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/flowers.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/flowers/small.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/flowers/tall.json
  fabric-convention-tags-v2/src/generated/resources/data/fabric-convention-tags-v2/fabric/tag_aliases/block/flowers.json
  fabric-convention-tags-v2/src/generated/resources/data/fabric-convention-tags-v2/fabric/tag_aliases/item/flowers/small.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalBlockTags.java
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
Labels: enhancement, merge me please

#4362 Add waitTick built-in to pressKey and pressMouse
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/api/client/gametest/v1/TestInput.java
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/api/client/gametest/v1/package-info.java
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/impl/client/gametest/NetworkSynchronizer.java
  fabric-client-gametest-api-v1/src/client/java/net/fabricmc/fabric/impl/client/gametest/TestInputImpl.java
  fabric-client-gametest-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/client/gametest/ClientGameTestTest.java
Labels: merge me please, test, small change

#4363 Fix focus script to always include "fabric-client-gametest-api-v1"
  gradle/Focus.java
Labels: merge me please, small change

#4369 Adjust when the EntityTrackingEvents are fired.
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/sync/AttachmentSync.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/EntityTrackerEntryMixin.java
  fabric-data-attachment-api-v1/src/main/resources/fabric-data-attachment-api-v1.mixins.json
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/EntityTrackingEvents.java
  fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/EntityTrackerEntryMixin.java
Labels: enhancement, merge me please

#4366 Fix attachment sync when changing world + migrate to client gametest
  fabric-data-attachment-api-v1/build.gradle
  fabric-data-attachment-api-v1/src/client/java/net/fabricmc/fabric/mixin/attachment/client/ClientPlayNetworkHandlerMixin.java
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/impl/attachment/sync/AttachmentSync.java
  fabric-data-attachment-api-v1/src/testmod/java/net/fabricmc/fabric/test/attachment/AttachmentTestMod.java
  fabric-data-attachment-api-v1/src/testmod/java/net/fabricmc/fabric/test/attachment/SetAttachmentFeature.java
  fabric-data-attachment-api-v1/src/testmod/resources/fabric.mod.json
  fabric-data-attachment-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/attachment/client/AttachmentTestModClient.java
  fabric-data-attachment-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/attachment/client/gametest/PersistenceGametest.java
  fabric-data-attachment-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/attachment/client/gametest/SyncGametest.java
  fabric-data-attachment-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/attachment/client/mixin/ClientWorldAccessor.java
  fabric-data-attachment-api-v1/src/testmodClient/java/net/fabricmc/fabric/test/attachment/client/mixin/DefaultPosArgumentAccessor.java
  fabric-data-attachment-api-v1/src/testmodClient/resources/fabric-data-attachment-api-v1-testmod.client.mixins.json
Labels: bug, merge me please, test

#4380 Add `c:seeds/pitcher_plant` and add Pitcher Pods to `c:seeds`
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/ItemTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/assets/fabric-convention-tags-v2/lang/en_us.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/seeds.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/seeds/pitcher_plant.json
  fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
Labels: merge me please, small change

#4390 Fix syncing block entity attachments on load.
  fabric-data-attachment-api-v1/build.gradle
  fabric-data-attachment-api-v1/src/main/java/net/fabricmc/fabric/mixin/attachment/AttachmentTargetsMixin.java
  fabric-data-attachment-api-v1/src/testmod/java/net/fabricmc/fabric/test/attachment/AttachmentTestMod.java
Labels: bug, merge me please, small change, priority:high

#4391 Fix AFTER_ENTITY_CHANGE_WORLD being invoked for entities teleporting within the same world.
  fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/EntityMixin.java
Labels: bug, merge me please, small change, priority:high

#4385 25w03a game tests
  build.gradle
  fabric-api-base/src/testmod/java/net/fabricmc/fabric/test/base/FabricApiBaseGameTest.java
  fabric-command-api-v2/src/testmod/java/net/fabricmc/fabric/test/command/EntitySelectorGameTest.java
  fabric-content-registries-v0/src/testmod/java/net/fabricmc/fabric/test/content/registry/ContentRegistryGameTest.java
  fabric-content-registries-v0/src/testmod/java/net/fabricmc/fabric/test/content/registry/FlammableTest.java
  fabric-data-attachment-api-v1/src/testmod/java/net/fabricmc/fabric/test/attachment/gametest/AttachmentCopyTests.java
  fabric-data-attachment-api-v1/src/testmod/java/net/fabricmc/fabric/test/attachment/gametest/BlockEntityTests.java
  fabric-events-interaction-v0/src/testmod/java/net/fabricmc/fabric/test/event/interaction/FakePlayerTests.java
  fabric-gametest-api-v1/build.gradle
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/api/gametest/v1/FabricGameTest.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/api/gametest/v1/GameTest.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/api/gametest/v1/package-info.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/impl/gametest/FabricGameTestHelper.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/impl/gametest/FabricGameTestModInitializer.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/impl/gametest/FabricGameTestRunner.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/impl/gametest/GameTestSystemProperties.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/impl/gametest/TestAnnotationLocator.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/ArgumentTypesMixin.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/CommandManagerMixin.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/MinecraftServerMixin.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/RegistryLoaderMixin.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/StructureTemplateManagerMixin.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/TestCommandMixin.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/TestFunctionsMixin.java
  fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/server/MainMixin.java
  fabric-gametest-api-v1/src/main/resources/fabric-gametest-api-v1.accesswidener
  fabric-gametest-api-v1/src/main/resources/fabric-gametest-api-v1.mixins.json
  fabric-gametest-api-v1/src/testmod/java/net/fabricmc/fabric/test/gametest/ExampleFabricTestSuite.java
  fabric-gametest-api-v1/src/testmod/java/net/fabricmc/fabric/test/gametest/ExampleTestSuite.java
  fabric-gametest-api-v1/src/testmod/resources/fabric.mod.json
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/BrewingStandGameTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/CustomEnchantmentEffectsGameTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/DefaultItemComponentGameTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/FurnaceGameTest.java
  fabric-item-api-v1/src/testmod/java/net/fabricmc/fabric/test/item/gametest/RecipeGameTest.java
  fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/ObjectBuilderGameTest.java
  fabric-recipe-api-v1/src/testmod/java/net/fabricmc/fabric/test/recipe/ingredient/ShapelessRecipeMatchTests.java
  fabric-recipe-api-v1/src/testmod/resources/fabric.mod.json
  fabric-resource-conditions-api-v1/src/testmod/java/net/fabricmc/fabric/test/resource/conditions/ConditionalResourcesTest.java
  fabric-resource-conditions-api-v1/src/testmod/java/net/fabricmc/fabric/test/resource/conditions/DefaultResourceConditionsTest.java
  fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModNioResourcePack.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/gametests/VanillaStorageTests.java
  fabric-transfer-api-v1/src/testmod/java/net/fabricmc/fabric/test/transfer/gametests/WorldDependentAttributesTest.java
  gradle.properties
  settings.gradle
Labels: merge me please, port, test, priority:high

#4392 Add pale oak to fence/fence gate tags
  fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BlockTagGenerator.java
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/fence_gates/wooden.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/block/fences/wooden.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/fence_gates/wooden.json
  fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/fences/wooden.json
Labels: bug, merge me please, small change, priority:low, tags

#4404 Fix Client Registry Remapping Only Remapping One Registry
  fabric-registry-sync-v0/src/client/java/net/fabricmc/fabric/impl/client/registry/sync/ClientRegistrySyncHandler.java
  fabric-registry-sync-v0/src/test/java/net/fabricmc/fabric/test/registry/sync/RegistryRemapTest.java
Labels: bug, registry-sync, merge me please, small change, priority:high
